DROP TABLE IF EXISTS `summurystats`;

CREATE TABLE `summurystats` (

  `ItemId` int(11) NOT NULL AUTO_INCREMENT,
  
  `ItemDate` date NOT NULL DEFAULT '1970-01-01',
  
  `TotalNumberOfCustomers` ,
  `TotalNumberOfActiveSavingsCustomers` ,
  `TotalNumberSavingsWithdraws` ,
  `TotalNumberOfSavingsMade` ,
  `TotalValueSavingsWithdraws` ,
  `TotalValueOfSavings` ,
  `TotalValueOfSavingsMade` ,
  `TotalValueOfSavingsWithdrawsMade` ,
  `TotalNumberOfActiveSharesCustomers` ,
  `TotalNumberOfCapitalisations` ,
  `TotalNumberOfDecapitalisations` ,
  `TotalNumberOfDepositsMade` ,
  `TotalNumberOfDepositWithdrawsMade` ,
  `TotalNumberOfActiveLoanCustomers` ,
  `TotalNumberOfAccounts` ,
  `TotalValueOfDeposits` ,
  `TotalValueOfDepositsMade` ,
  `TotalValueOfDepositWithdrawsMade` ,
  `TotalValueOfShares` ,
  `TotalValueOfSharesBought` ,
  `TotalValueOfSharesRemoved` ,
  `TotalNumberOfActiveLoanCustomersCycle1` ,
  `TotalNumberOfActiveLoanCustomersCycle2` ,
  `TotalNumberOfActiveLoanCustomersCycle3` ,
  `TotalNumberOfActiveLoanCustomersCycle4` ,
  `TotalNumberOfActiveLoanCustomersCycle5` ,
  `TotalNumberOfActiveLoanCustomersCycle6` ,
  `TotalNumberOfActiveLoanCustomersCycle7` ,
  `TotalNumberOfActiveLoanCustomersCycleAboveCycle7` ,
  `TotalNumberOfActiveLoans` ,
  `TotalNumberOfLoansDisbursed` ,
  `TotalNumberOfLoansDisbursedCycle1` ,
  `TotalNumberOfLoansDisbursedCycle2` ,
  `TotalNumberOfLoansDisbursedCycle3` ,
  `TotalNumberOfLoansDisbursedCycle4` ,
  `TotalNumberOfLoansDisbursedCycle5` ,
  `TotalNumberOfLoansDisbursedCycle6` ,
  `TotalNumberOfLoansDisbursedCycle7` ,
  `TotalNumberOfLoansDisbursedCycleAbove7` ,
  `TotalNumberOfGroupLoansDisbursed` ,
  `TotalNumberOfIndividualLoansDisbursed` ,
  `TotalNumberOfLoansCompleted` ,
  `TotalNumberOfLoansWrittenOff` ,
  `TotalNumberOfPrincipalLoanRepaymentsDueLoansOnly` ,
  `TotalNumberOfEarlyPrincipalLoanRepayments` ,
  `TotalNumberOfArrearsPrincipalLoanRepayments` ,
  `TotalNumberOfAllPrincipalLoanRepayments` ,
  `TotalNumberOfAllInterestAndPrincipalLoanRepayments` ,
  `TotalNumberOfLoansInArrears` ,
  `TotalValueOfActiveLoans` ,
  `TotalValueOfActiveLoanCustomersCycle1` ,
  `TotalValueOfActiveLoanCustomersCycle2` ,
  `TotalValueOfActiveLoanCustomersCycle3` ,
  `TotalValueOfActiveLoanCustomersCycle4` ,
  `TotalValueOfActiveLoanCustomersCycle5` ,
  `TotalValueOfActiveLoanCustomersCycle6` ,
  `TotalValueOfActiveLoanCustomersCycle7` ,
  `TotalValueOfActiveLoanCustomersCycleAboveCycle7` ,
  `TotalValueOfLoansDisbursed` ,
  `TotalValueOfLoansDisbursedCycle1` ,
  `TotalValueOfLoansDisbursedCycle2` ,
  `TotalValueOfLoansDisbursedCycle3` ,
  `TotalValueOfLoansDisbursedCycle4` ,
  `TotalValueOfLoansDisbursedCycle5` ,
  `TotalValueOfLoansDisbursedCycle6` ,
  `TotalValueOfLoansDisbursedCycle7` ,
  `TotalValueOfLoansDisbursedCycleAbove7` ,
  `TotalValueOfGroupLoansDisbursed` ,
  `TotalValueOfIndividualLoansDisbursed` ,
  `TotalValueOfLoansCompleted` ,
  `TotalValueOfLoansWrittenOff` ,
  `TotalValueOfLoanRepaymentsMinusArrears` ,
  `TotalValueOfPrincipalOutStandingArrears` ,
  `TotalValueOfInterestOutStandingArrears` ,
  `TotalValueOfInterestReceived` ,
  `TotalValueOfPrincipalLoanRepaymentsDueLoansOnly` ,
  `TotalValueOfEarlyPrincipalLoanRepayments` ,
  `TotalValueOfArrearsPrincipalLoanRepayments` ,
  `TotalValueOfAllPrincipalLoanRepayments` ,
  `TotalValueOfAllInterestAndPrincipalLoanRepayments` ,
  `TotalValueOfLoansInArrears` ,
  `TotalValueOfLoanBook` ,
  `TotalValueOfCashBalances` ,
  `TotalValueOfBankBalances` ,
  `TotalValueOfAssets` ,
  `TotalValueOfReceivables` ,
  `TotalValueOfPayables` ,
  `TotalValueOfFixedAssets` ,
  `TotalValueOfCurrentAssetsIncludingInterestReceivable` ,
  `TotalValueOfCurrentAssetsMinusInterestReceivable` ,
  `TotalValueOfMainIncome` ,
  `TotalValueOfOtherIncome` ,
  `TotalValueOfIncome` ,
  `TotalValueOfExpenses` ,
  `TotalValueOfLiabilities` ,
  `TotalValueOfCapital` ,
  PRIMARY KEY (`ItemId`),
  UNIQUE KEY `ItemId` (`ItemId`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;