/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package googo.pmms.project2.frames;

import googo.pmms.project2.loanHelper.MaxmumAmountBorrowedFormulas;
import googo.pmms.project2.accountsHelper.PostingModal;
import googo.pmms.project2.databases.DatabaseQuaries;
import googo.pmms.project2.databases.loanDatabaseQuaries;
import googo.pmms.project2.accountsHelper.fileInputOutPutStreams;
import googo.pmms.project2.databaseConnectors.JdbcConnector;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Stanchart
 */
public class ChangePassword extends javax.swing.JFrame {
  fileInputOutPutStreams fios= new fileInputOutPutStreams();

    DecimalFormat NumberFormat =new DecimalFormat("#,###.##");
    ArrayList<String> data4, column1;
 ArrayList<ArrayList<String>> data5;
          JOptionPane p;
    PostingModal model ;
    JFrame fi, f,fa,fb,fc;
    Date date;
  SimpleDateFormat df;

 DatabaseQuaries dbq= new DatabaseQuaries();
 MaxmumAmountBorrowedFormulas maxValue= new MaxmumAmountBorrowedFormulas();
 loanDatabaseQuaries loan=new loanDatabaseQuaries();
     String userId;
    /**
     * Creates new form ChangePassword
     */
    public ChangePassword(String userId) {
        initComponents();
       this.setLocationRelativeTo(null);   
        Image img = new ImageIcon(System.getProperty("user.dir")+"/"+"ICON_LOGO.jpg").getImage();
      this.setIconImage(img);
       this.setTitle("CHANGE PASSWORD"); 
    Integer xl=1;
   fios.intFileWriterReplace(fios.createFileName("loanAuthorisation", "displayWindow", "authorisationTable.txt"),xl.toString());      
   this.userId=userId;
    }
//public void setUserID(String userid){
//this.userId=userid;
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);
        setMinimumSize(new java.awt.Dimension(410, 320));
        setPreferredSize(new java.awt.Dimension(410, 320));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setText("Enter New Password:");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 70, 150, 30);

        jLabel2.setText("Re-Enter New Password:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 120, 150, 30);

        jLabel3.setText("Enter Current Password:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 150, 30);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(160, 70, 130, 30);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(160, 120, 130, 30);
        jPanel1.add(jPasswordField3);
        jPasswordField3.setBounds(160, 20, 130, 30);

        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 160, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 30, 420, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//    String activeUser =fios.stringFileReader(fios.createFileName("logOut", "completeShutDown", "activeUserId.txt"));
        char [] jpa1= jPasswordField3.getPassword();
        String jpassword1=String.valueOf(jpa1);
        
        char [] jpa2= jPasswordField1.getPassword();
        String jpassword2=String.valueOf(jpa2);
        
        char [] jpa3= jPasswordField2.getPassword();
        String jpassword3=String.valueOf(jpa3);
        
       if(!jpassword1.equals(dbq.password(userId))){
       
       JOptionPane.showConfirmDialog(this, "Old password is incorrect");
       return;
       } 
        if(jpassword1.equals(jpassword2)){
       
       JOptionPane.showConfirmDialog(this, "Old and New Passwords are the same");
       return;
       } 
        
        
        if(jpassword2.equals(jpassword3)){
        
     JdbcConnector ctx = new JdbcConnector(fios.stringFileReader(fios.createFileName("emailDetails", "sendMail", "AccountDBDetails.txt"))); 
        Connection cxs =ctx.createConnection();
        try {
        cxs.setAutoCommit(false);
        PreparedStatement pstmt = cxs.prepareStatement("UPDATE log_in SET p_word_login = ? WHERE user_id = ?");
 
        pstmt.setString(1, jpassword2);
        pstmt.setString(2, userId);
        pstmt.executeUpdate();
       cxs.setAutoCommit(true);
          Integer j=57;
        fios.stringFileWriter(fios.createFileName("logOut", "completeShutDown", "passWordChange"+userId+".txt"),j.toString());
       JOptionPane.showMessageDialog(this, "Password was successfully changed!"); 
       JOptionPane.showMessageDialog(this, "To enable the changes to take effect, the system is going to shut down!");
      System.exit(0);
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex.toString());
        }
        ctx.closeConnection(cxs);
        }else{
          JOptionPane.showMessageDialog(this, "New passwords don't match");  
          
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               JFrame thisf= new ChangePassword();
//               thisf.setVisible(true);
//               thisf.setSize(310, 220);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    // End of variables declaration//GEN-END:variables
}
