/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package googo.pmms.project2.smallFrames;

import googo.pmms.project2.accountsHelper.Formartter;
import googo.pmms.project2.accountsHelper.fileInputOutPutStreams;
import googo.pmms.project2.databases.loanDatabaseQuaries;
import googo.pmms.project2.databases.DatabaseQuaries;
import googo.pmms.project2.frameHelper.IUpdateText;
import googo.pmms.project2.frameHelper.ListDataModel;
import googo.pmms.project2.frames.Calender;
import googo.pmms.project2.frames.email;
import googo.pmms.project2.reportsHelper.OtherLoanReports;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author STAT SOLUTIONS
 */
public class EmailAttachmentAll extends javax.swing.JFrame implements MouseListener, IUpdateText, ActionListener,KeyListener{
String userId;
//JFrame reflection;
//    List amortDetails;
//    DecimalFormat NumberFormat =new DecimalFormat("#,###");
//        SimpleDateFormat sdf =new SimpleDateFormat("dd/MM/yyyy");
    fileInputOutPutStreams fios= new fileInputOutPutStreams();
//    Formartter ffm = new Formartter();
//    Date Trndate,valuedate;
//   ArrayList<String> data4, column1;
//List data5;
//    String text,position;
// Integer Value,Value1;
//    GregorianCalendar cal = new GregorianCalendar(); 
//    
//         BatchPostingHelper bPost=new BatchPostingHelper(); 
//         
//     JdbcConnector csx = new JdbcConnector(fios.stringFileReader(fios.createFileName("emailDetails", "sendMail", "AccountDBDetails.txt"))); ; 
    DatabaseQuaries dbq =new DatabaseQuaries();
    loanDatabaseQuaries loan=new loanDatabaseQuaries();
//    Formartter form= new Formartter();
//    AccountNumberCreationDataBase ancdb=new AccountNumberCreationDataBase();
//   ReportsDatabase report =new ReportsDatabase();
//    BalanceSheet bsheet= new BalanceSheet();
//    PostingMain post= new PostingMain();
//    BackUpRestoreDB dbBackUp= new BackUpRestoreDB();
//    CreatingFolders filesW= new CreatingFolders();
//   private PostingEntryWindow.ProcessLoanRepayment laonPay;
//  String completeStatus="Not Complete",flag="Not Flagged"; int temper=0;
//    String batchNumber;
    OtherLoanReports otherLoans=new  OtherLoanReports();
//     LoanSavingsSharesOthers loanSaveShare=new LoanSavingsSharesOthers();
//         ListDataModel model1;
         ListDataModel result;
//         String theAccount="";
//         
////     OtherLoanReports otherLoans=new  OtherLoanReports();
//     
//    List loanPaymentOrder;
//    SimpleDateFormat sdk =new SimpleDateFormat("dd.MM.yyyy");
//  
//        CreateExcelWorkBook writeExcel= new CreateExcelWorkBook();
//    
// int n=0;
//   
//          JOptionPane p;
//    PostingModal model ;
//    JFrame fi, f,fa,fb,fc;
//    Date date;
//  SimpleDateFormat df;
     Formartter fmt= new Formartter();
// AccountNumberCreationDataBase db =new AccountNumberCreationDataBase();
//NewLoanApplication component;
String accountNumber;
String GroupId;
String category;

email theOne;
    public EmailAttachmentAll(String userId,String comp,String cat,email theComp) {
        
         
          
        initComponents();
        
        this.userId=userId;
        
        theOne=theComp;
        
        category=cat;
        
        accountNumber=comp;

        Image img = new ImageIcon(System.getProperty("user.dir")+"/"+"ICON_LOGO.jpg").getImage();
        this.setIconImage(img);
        this.setTitle("OTHER LOAN DETAILS"); 
//        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jComboBox92 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jCheckBox11 = new javax.swing.JCheckBox();
        jComboBox93 = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton23 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jButton24 = new javax.swing.JButton();
        jCheckBox12 = new javax.swing.JCheckBox();
        jComboBox94 = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jButton26 = new javax.swing.JButton();
        jCheckBox13 = new javax.swing.JCheckBox();
        jComboBox95 = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jButton27 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jButton28 = new javax.swing.JButton();
        jCheckBox14 = new javax.swing.JCheckBox();
        jComboBox98 = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jButton77 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jButton78 = new javax.swing.JButton();
        jCheckBox17 = new javax.swing.JCheckBox();
        jComboBox99 = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jButton79 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jButton80 = new javax.swing.JButton();
        jCheckBox18 = new javax.swing.JCheckBox();
        jButton51 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(983, 497));
        setMinimumSize(new java.awt.Dimension(983, 497));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(983, 497));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 153), new java.awt.Color(0, 204, 153)));
        jPanel1.setLayout(null);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Attach Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(370, 400, 170, 50);

        jComboBox92.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox92.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TrialBalance", "BalanceSheet", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement", "CashLedger" }));
        jComboBox92.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jComboBox92);
        jComboBox92.setBounds(40, 170, 250, 30);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Start Date");
        jLabel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel28);
        jLabel28.setBounds(290, 170, 130, 30);

        jTextField15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel6.add(jTextField15);
        jTextField15.setBounds(420, 170, 130, 30);

        jButton21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton21);
        jButton21.setBounds(550, 170, 20, 30);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("End Date");
        jLabel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel29);
        jLabel29.setBounds(570, 170, 130, 30);
        jPanel6.add(jTextField16);
        jTextField16.setBounds(700, 170, 130, 30);

        jButton22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton22);
        jButton22.setBounds(830, 170, 20, 30);

        jCheckBox11.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox11.setForeground(java.awt.SystemColor.control);
        jCheckBox11.setText("Use");
        jCheckBox11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox11);
        jCheckBox11.setBounds(850, 170, 60, 30);

        jComboBox93.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox93.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TrialBalance", "BalanceSheet", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement", "CashLedger" }));
        jComboBox93.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jComboBox93);
        jComboBox93.setBounds(40, 220, 250, 30);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Start Date");
        jLabel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel30);
        jLabel30.setBounds(290, 220, 130, 30);

        jTextField17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel6.add(jTextField17);
        jTextField17.setBounds(420, 220, 130, 30);

        jButton23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton23);
        jButton23.setBounds(550, 220, 20, 30);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("End Date");
        jLabel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel31);
        jLabel31.setBounds(570, 220, 130, 30);
        jPanel6.add(jTextField18);
        jTextField18.setBounds(700, 220, 130, 30);

        jButton24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton24);
        jButton24.setBounds(830, 220, 20, 30);

        jCheckBox12.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox12.setForeground(java.awt.SystemColor.control);
        jCheckBox12.setText("Use");
        jCheckBox12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox12);
        jCheckBox12.setBounds(850, 220, 60, 30);

        jComboBox94.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox94.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TrialBalance", "BalanceSheet", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement", "CashLedger" }));
        jComboBox94.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jComboBox94);
        jComboBox94.setBounds(40, 270, 250, 30);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Start Date");
        jLabel32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel32);
        jLabel32.setBounds(290, 270, 130, 30);

        jTextField19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel6.add(jTextField19);
        jTextField19.setBounds(420, 270, 130, 30);

        jButton25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton25);
        jButton25.setBounds(550, 270, 20, 30);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("End Date");
        jLabel33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel33);
        jLabel33.setBounds(570, 270, 130, 30);
        jPanel6.add(jTextField20);
        jTextField20.setBounds(700, 270, 130, 30);

        jButton26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton26);
        jButton26.setBounds(830, 270, 20, 30);

        jCheckBox13.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox13.setForeground(java.awt.SystemColor.control);
        jCheckBox13.setText("Use");
        jCheckBox13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox13);
        jCheckBox13.setBounds(850, 270, 60, 30);

        jComboBox95.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox95.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TrialBalance", "BalanceSheet", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement", "CashLedger" }));
        jComboBox95.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jComboBox95);
        jComboBox95.setBounds(40, 320, 250, 30);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setText("Start Date");
        jLabel34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel34);
        jLabel34.setBounds(290, 320, 130, 30);

        jTextField21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel6.add(jTextField21);
        jTextField21.setBounds(420, 320, 130, 30);

        jButton27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton27);
        jButton27.setBounds(550, 320, 20, 30);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setText("End Date");
        jLabel35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel35);
        jLabel35.setBounds(570, 320, 130, 30);
        jPanel6.add(jTextField22);
        jTextField22.setBounds(700, 320, 130, 30);

        jButton28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton28);
        jButton28.setBounds(830, 320, 20, 30);

        jCheckBox14.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox14.setForeground(java.awt.SystemColor.control);
        jCheckBox14.setText("Use");
        jCheckBox14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox14);
        jCheckBox14.setBounds(850, 320, 60, 30);

        jComboBox98.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox98.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CashLedger", "TrialBalance", "BalanceSheet", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement" }));
        jComboBox98.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jComboBox98);
        jComboBox98.setBounds(40, 70, 250, 30);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel40.setText("Start Date");
        jLabel40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel40);
        jLabel40.setBounds(290, 70, 130, 30);

        jTextField27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel6.add(jTextField27);
        jTextField27.setBounds(420, 70, 130, 30);

        jButton77.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton77ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton77);
        jButton77.setBounds(550, 70, 20, 30);

        jLabel41.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel41.setText("End Date");
        jLabel41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel41);
        jLabel41.setBounds(570, 70, 130, 30);
        jPanel6.add(jTextField28);
        jTextField28.setBounds(700, 70, 130, 30);

        jButton78.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton78ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton78);
        jButton78.setBounds(830, 70, 20, 30);

        jCheckBox17.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox17.setForeground(java.awt.SystemColor.control);
        jCheckBox17.setText("Use");
        jCheckBox17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox17);
        jCheckBox17.setBounds(850, 70, 60, 30);

        jComboBox99.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox99.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BalanceSheet", "TrialBalance", "CashLedger", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement" }));
        jComboBox99.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jComboBox99);
        jComboBox99.setBounds(40, 120, 250, 30);

        jLabel42.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel42.setText("Start Date");
        jLabel42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel42);
        jLabel42.setBounds(290, 120, 130, 30);

        jTextField29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel6.add(jTextField29);
        jTextField29.setBounds(420, 120, 130, 30);

        jButton79.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton79ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton79);
        jButton79.setBounds(550, 120, 20, 30);

        jLabel43.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel43.setText("End Date");
        jLabel43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel43);
        jLabel43.setBounds(570, 120, 130, 30);
        jPanel6.add(jTextField30);
        jTextField30.setBounds(700, 120, 130, 30);

        jButton80.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton80ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton80);
        jButton80.setBounds(830, 120, 20, 30);

        jCheckBox18.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox18.setForeground(java.awt.SystemColor.control);
        jCheckBox18.setText("Use");
        jCheckBox18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox18);
        jCheckBox18.setBounds(850, 120, 60, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(30, 20, 940, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 1010, 550);

        jButton51.setBackground(new java.awt.Color(0, 51, 51));
        jButton51.setText("jButton5");
        getContentPane().add(jButton51);
        jButton51.setBounds(1800, 360, 73, 23);

        jButton50.setBackground(java.awt.SystemColor.controlLtHighlight);
        jButton50.setText("jButton5");
        getContentPane().add(jButton50);
        jButton50.setBounds(1790, 330, 73, 23);

        jButton49.setBackground(new java.awt.Color(255, 204, 204));
        jButton49.setText("jButton5");
        getContentPane().add(jButton49);
        jButton49.setBounds(1870, 320, 73, 23);

        jButton31.setBackground(new java.awt.Color(255, 204, 153));
        jButton31.setText("Blue");
        getContentPane().add(jButton31);
        jButton31.setBounds(1810, 310, 53, 23);

        jButton38.setBackground(new java.awt.Color(204, 204, 0));
        jButton38.setText("Blue");
        getContentPane().add(jButton38);
        jButton38.setBounds(1810, 290, 53, 23);

        jButton32.setBackground(new java.awt.Color(0, 153, 153));
        jButton32.setText("Blue");
        getContentPane().add(jButton32);
        jButton32.setBounds(1870, 290, 53, 23);

        jButton47.setBackground(new java.awt.Color(204, 255, 204));
        jButton47.setText("Blue");
        getContentPane().add(jButton47);
        jButton47.setBounds(1930, 290, 53, 23);

        jButton29.setBackground(new java.awt.Color(0, 204, 204));
        jButton29.setText("Blue");
        getContentPane().add(jButton29);
        jButton29.setBounds(1920, 270, 53, 23);

        jButton37.setBackground(new java.awt.Color(204, 153, 255));
        jButton37.setText("Blue");
        getContentPane().add(jButton37);
        jButton37.setBounds(1870, 270, 53, 23);

        jButton33.setBackground(new java.awt.Color(152, 198, 94));
        jButton33.setText("Blue");
        getContentPane().add(jButton33);
        jButton33.setBounds(1810, 270, 53, 23);

        jButton35.setBackground(new java.awt.Color(255, 204, 204));
        jButton35.setText("Blue");
        getContentPane().add(jButton35);
        jButton35.setBounds(1810, 250, 53, 23);

        jButton45.setBackground(new java.awt.Color(255, 255, 204));
        jButton45.setText("Blue");
        getContentPane().add(jButton45);
        jButton45.setBounds(1870, 250, 53, 23);

        jButton42.setBackground(new java.awt.Color(0, 204, 102));
        jButton42.setText("Blue");
        getContentPane().add(jButton42);
        jButton42.setBounds(1920, 230, 53, 23);

        jButton43.setBackground(new java.awt.Color(204, 204, 204));
        jButton43.setText("Blue");
        getContentPane().add(jButton43);
        jButton43.setBounds(1870, 230, 53, 23);

        jButton30.setBackground(new java.awt.Color(0, 153, 255));
        jButton30.setText("Blue");
        getContentPane().add(jButton30);
        jButton30.setBounds(1810, 230, 53, 23);

        jButton36.setBackground(java.awt.SystemColor.activeCaption);
        jButton36.setText("Blue");
        getContentPane().add(jButton36);
        jButton36.setBounds(1810, 210, 53, 23);

        jButton44.setBackground(new java.awt.Color(204, 165, 165));
        jButton44.setText("Blue");
        getContentPane().add(jButton44);
        jButton44.setBounds(1870, 210, 53, 23);

        jButton39.setBackground(new java.awt.Color(204, 204, 255));
        jButton39.setText("Blue");
        getContentPane().add(jButton39);
        jButton39.setBounds(1920, 210, 53, 23);

        jButton41.setBackground(java.awt.SystemColor.activeCaption);
        jButton41.setText("Blue");
        getContentPane().add(jButton41);
        jButton41.setBounds(1920, 190, 53, 23);

        jButton46.setBackground(java.awt.SystemColor.activeCaption);
        jButton46.setText("Blue");
        getContentPane().add(jButton46);
        jButton46.setBounds(1870, 190, 53, 23);

        jButton40.setBackground(java.awt.SystemColor.activeCaption);
        jButton40.setText("Blue");
        getContentPane().add(jButton40);
        jButton40.setBounds(1810, 190, 53, 23);

        jButton48.setBackground(new java.awt.Color(201, 222, 223));
        jButton48.setText("Blue");
        getContentPane().add(jButton48);
        jButton48.setBounds(1870, 170, 53, 23);

        jButton52.setBackground(new java.awt.Color(0, 51, 51));
        jButton52.setText("jButton5");
        getContentPane().add(jButton52);
        jButton52.setBounds(1800, 360, 73, 23);

        jButton53.setBackground(java.awt.SystemColor.controlLtHighlight);
        jButton53.setText("jButton5");
        getContentPane().add(jButton53);
        jButton53.setBounds(1790, 330, 73, 23);

        jButton54.setBackground(new java.awt.Color(255, 204, 204));
        jButton54.setText("jButton5");
        getContentPane().add(jButton54);
        jButton54.setBounds(1870, 320, 73, 23);

        jButton34.setBackground(new java.awt.Color(255, 204, 153));
        jButton34.setText("Blue");
        getContentPane().add(jButton34);
        jButton34.setBounds(1810, 310, 53, 23);

        jButton55.setBackground(new java.awt.Color(204, 204, 0));
        jButton55.setText("Blue");
        getContentPane().add(jButton55);
        jButton55.setBounds(1810, 290, 53, 23);

        jButton56.setBackground(new java.awt.Color(0, 153, 153));
        jButton56.setText("Blue");
        getContentPane().add(jButton56);
        jButton56.setBounds(1870, 290, 53, 23);

        jButton57.setBackground(new java.awt.Color(204, 255, 204));
        jButton57.setText("Blue");
        getContentPane().add(jButton57);
        jButton57.setBounds(1930, 290, 53, 23);

        jButton58.setBackground(new java.awt.Color(0, 204, 204));
        jButton58.setText("Blue");
        getContentPane().add(jButton58);
        jButton58.setBounds(1920, 270, 53, 23);

        jButton59.setBackground(new java.awt.Color(204, 153, 255));
        jButton59.setText("Blue");
        getContentPane().add(jButton59);
        jButton59.setBounds(1870, 270, 53, 23);

        jButton60.setBackground(new java.awt.Color(152, 198, 94));
        jButton60.setText("Blue");
        getContentPane().add(jButton60);
        jButton60.setBounds(1810, 270, 53, 23);

        jButton61.setBackground(new java.awt.Color(255, 204, 204));
        jButton61.setText("Blue");
        getContentPane().add(jButton61);
        jButton61.setBounds(1810, 250, 53, 23);

        jButton62.setBackground(new java.awt.Color(255, 255, 204));
        jButton62.setText("Blue");
        getContentPane().add(jButton62);
        jButton62.setBounds(1870, 250, 53, 23);

        jButton63.setBackground(new java.awt.Color(0, 204, 102));
        jButton63.setText("Blue");
        getContentPane().add(jButton63);
        jButton63.setBounds(1920, 230, 53, 23);

        jButton64.setBackground(new java.awt.Color(204, 204, 204));
        jButton64.setText("Blue");
        getContentPane().add(jButton64);
        jButton64.setBounds(1870, 230, 53, 23);

        jButton65.setBackground(new java.awt.Color(0, 153, 255));
        jButton65.setText("Blue");
        getContentPane().add(jButton65);
        jButton65.setBounds(1810, 230, 53, 23);

        jButton66.setBackground(java.awt.SystemColor.activeCaption);
        jButton66.setText("Blue");
        getContentPane().add(jButton66);
        jButton66.setBounds(1810, 210, 53, 23);

        jButton67.setBackground(new java.awt.Color(204, 165, 165));
        jButton67.setText("Blue");
        getContentPane().add(jButton67);
        jButton67.setBounds(1870, 210, 53, 23);

        jButton68.setBackground(new java.awt.Color(204, 204, 255));
        jButton68.setText("Blue");
        getContentPane().add(jButton68);
        jButton68.setBounds(1920, 210, 53, 23);

        jButton69.setBackground(java.awt.SystemColor.activeCaption);
        jButton69.setText("Blue");
        getContentPane().add(jButton69);
        jButton69.setBounds(1920, 190, 53, 23);

        jButton70.setBackground(java.awt.SystemColor.activeCaption);
        jButton70.setText("Blue");
        getContentPane().add(jButton70);
        jButton70.setBounds(1870, 190, 53, 23);

        jButton71.setBackground(java.awt.SystemColor.activeCaption);
        jButton71.setText("Blue");
        getContentPane().add(jButton71);
        jButton71.setBounds(1810, 190, 53, 23);

        jButton72.setBackground(new java.awt.Color(201, 222, 223));
        jButton72.setText("Blue");
        getContentPane().add(jButton72);
        jButton72.setBounds(1870, 170, 53, 23);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened



    }//GEN-LAST:event_formWindowOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.dispose();
        
//         component.addItemInList(jComboBox3.getSelectedItem().toString());
//          component.addItemInList(jComboBox13.getSelectedItem().toString());
//           component.addItemInList(jComboBox14.getSelectedItem().toString());
//           component.addItemInList(jComboBox15.getSelectedItem().toString());
//            component.addItemInList(jComboBox17.getSelectedItem().toString());
           
//           if(jTextField16.getText().equalsIgnoreCase("")){
//           JOptionPane.showMessageDialog(this, "Please first input the Email Address!!!");
//           }else {
//           component.addItemInList(jTextField16.getText());
//           }
//           
//             if(jTextField16.getText().equalsIgnoreCase("")){
//           JOptionPane.showMessageDialog(this, "Please first input the Email Address!!!");
//           }else {
//           component.addItemInList(jTextField16.getText());
//           }
             
//     component.addItemInList(jComboBox16.getSelectedItem().toString());        
//               if(jTextField16.getText().equalsIgnoreCase("")){
//           JOptionPane.showMessageDialog(this, "Please first input the Email Address!!!");
//           }else {
////           component.addItemInList(jTextField16.getText());
//           }
////          component.addItemInList(jComboBox16.getSelectedItem().toString()); 
//             if(jTextField15.getText().equalsIgnoreCase("")){
//           JOptionPane.showMessageDialog(this, "Please first input the Mobile Number!!!");
//           }else {
////           component.addItemInList(jTextField15.getText());
//           }
//             
//        component.setTheField("Bio Data");   
//        
//          this.dispose();  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int i=1;
     while(i<=5){
     
     JOptionPane.showMessageDialog(this, "SYSTEM LOG OUT ERROR!!!!!!!!!");}
    }//GEN-LAST:event_formWindowClosing

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
   fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"105");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
       fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"106");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
      
        if(jTextField15.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");

        }else{
            if(jTextField16.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");

            }else{

                List de1=new ArrayList();
                de1.add(jComboBox92.getSelectedItem().toString());
                de1.add(jTextField15.getText());
                de1.add(jTextField16.getText());
                theOne.setTheEmailDetails(de1);
            }
        }
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
       fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"108");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
      fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"109");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
           
        if(jTextField17.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");

        }else{
            if(jTextField18.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");

            }else{

                List de1=new ArrayList();
                de1.add(jComboBox93.getSelectedItem().toString());
                de1.add(jTextField17.getText());
                de1.add(jTextField18.getText());
                theOne.setTheEmailDetails(de1);
            }
        }
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
         fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"110");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
           fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"111");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        if(jTextField19.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");

        }else{
            if(jTextField20.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");

            }else{

                List de1=new ArrayList();
                de1.add(jComboBox94.getSelectedItem().toString());
                de1.add(jTextField19.getText());
                de1.add(jTextField20.getText());
                theOne.setTheEmailDetails(de1);
            }
        }
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
         fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"112");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
      fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"113");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        if(jTextField21.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");

        }else{
            if(jTextField22.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");

            }else{

                List de1=new ArrayList();
                de1.add(jComboBox95.getSelectedItem().toString());
                de1.add(jTextField21.getText());
                de1.add(jTextField22.getText());
                theOne.setTheEmailDetails(de1);
            }
        }
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton77ActionPerformed
             fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"101");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton77ActionPerformed

    private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton78ActionPerformed
       fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"102");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton78ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        if(jTextField27.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");

        }else{
            if(jTextField28.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");

            }else{

                List de1=new ArrayList();
                de1.add(jComboBox98.getSelectedItem().toString());
                de1.add(jTextField27.getText());
                de1.add(jTextField28.getText());
                theOne.setTheEmailDetails(de1);
            }
        }
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton79ActionPerformed
        fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"103");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton79ActionPerformed

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"104");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton80ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
            if(jTextField29.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");

        }else{
            if(jTextField30.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");

            }else{

                List de1=new ArrayList();
                de1.add(jComboBox99.getSelectedItem().toString());
                de1.add(jTextField29.getText());
                de1.add(jTextField30.getText());
                theOne.setTheEmailDetails(de1);
            }
        }
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
////        public static String u=AddBatch.this.userId;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddBatch().setVisible(true);
//            }
//        });
//    }
   private void sortTable(JTable table,JTextField textField){

   
    
TableRowSorter<TableModel> rowSorter  = new TableRowSorter<>(table.getModel());
                     
                      table.setRowSorter(rowSorter);
                     textField.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = textField.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = textField.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    

}
   
     
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton80;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JComboBox jComboBox92;
    private javax.swing.JComboBox jComboBox93;
    private javax.swing.JComboBox jComboBox94;
    private javax.swing.JComboBox jComboBox95;
    private javax.swing.JComboBox jComboBox98;
    private javax.swing.JComboBox jComboBox99;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {

    }

    @Override
    public void mousePressed(MouseEvent e) {
      
    }

    @Override
    public void mouseReleased(MouseEvent e) {
     
    }

    @Override
    public void mouseEntered(MouseEvent e) {
     
    }

    @Override
    public void mouseExited(MouseEvent e) {
     
    }

    @Override
    public void updateText(String text) {
  
        switch( fios.intFileReader(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"))){ 
        case 101:jTextField27.setText(text);break;    
        case 102:jTextField28.setText(text);break; 
        case 103:jTextField29.setText(text);break;    
        case 104:jTextField30.setText(text);break; 
        case 105:jTextField15.setText(text);break;    
        case 106:jTextField16.setText(text);break; 
    
            case 108:jTextField17.setText(text);break;    
        case 109:jTextField18.setText(text);break; 
        case 110:jTextField19.setText(text);break;    
        case 111:jTextField20.setText(text);break; 
        case 112:jTextField21.setText(text);break;    
        case 113:jTextField22.setText(text);break; 
        
     }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
 
    }

    @Override
    public void keyTyped(KeyEvent e) {
 
    }

    @Override
    public void keyPressed(KeyEvent e) {

    }

    @Override
    public void keyReleased(KeyEvent e) {
    
    }

    
}

