/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package googo.pmms.project2.smallFrames;

import googo.pmms.project2.accountsHelper.Formartter;
import googo.pmms.project2.accountsHelper.fileInputOutPutStreams;
import googo.pmms.project2.databases.loanDatabaseQuaries;
import googo.pmms.project2.databases.DatabaseQuaries;
import googo.pmms.project2.frameHelper.IUpdateText;
import googo.pmms.project2.frameHelper.ListDataModel;
import googo.pmms.project2.reportsHelper.OtherLoanReports;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import static java.lang.Boolean.parseBoolean;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author STAT SOLUTIONS
 */
public class OtherLoanDetails2 extends javax.swing.JFrame implements MouseListener, IUpdateText, ActionListener,KeyListener{
String userId;
//JFrame reflection;
//    List amortDetails;
//    DecimalFormat NumberFormat =new DecimalFormat("#,###");
//        SimpleDateFormat sdf =new SimpleDateFormat("dd/MM/yyyy");
    fileInputOutPutStreams fios= new fileInputOutPutStreams();
//    Formartter ffm = new Formartter();
//    Date Trndate,valuedate;
//   ArrayList<String> data4, column1;
//List data5;
//    String text,position;
// Integer Value,Value1;
//    GregorianCalendar cal = new GregorianCalendar(); 
//    
//         BatchPostingHelper bPost=new BatchPostingHelper(); 
//         
//     JdbcConnector csx = new JdbcConnector(fios.stringFileReader(fios.createFileName("emailDetails", "sendMail", "AccountDBDetails.txt"))); ; 
    DatabaseQuaries dbq =new DatabaseQuaries();
    loanDatabaseQuaries loan=new loanDatabaseQuaries();
//    Formartter form= new Formartter();
//    AccountNumberCreationDataBase ancdb=new AccountNumberCreationDataBase();
//   ReportsDatabase report =new ReportsDatabase();
//    BalanceSheet bsheet= new BalanceSheet();
//    PostingMain post= new PostingMain();
//    BackUpRestoreDB dbBackUp= new BackUpRestoreDB();
//    CreatingFolders filesW= new CreatingFolders();
//   private PostingEntryWindow.ProcessLoanRepayment laonPay;
//  String completeStatus="Not Complete",flag="Not Flagged"; int temper=0;
//    String batchNumber;
    OtherLoanReports otherLoans=new  OtherLoanReports();
//     LoanSavingsSharesOthers loanSaveShare=new LoanSavingsSharesOthers();
//         ListDataModel model1;
         ListDataModel result;
//         String theAccount="";
//         
////     OtherLoanReports otherLoans=new  OtherLoanReports();
//     
//    List loanPaymentOrder;
//    SimpleDateFormat sdk =new SimpleDateFormat("dd.MM.yyyy");
//  
//        CreateExcelWorkBook writeExcel= new CreateExcelWorkBook();
//    
// int n=0;
//   
//          JOptionPane p;
//    PostingModal model ;
//    JFrame fi, f,fa,fb,fc;
//    Date date;
//  SimpleDateFormat df;
     Formartter fmt= new Formartter();
// AccountNumberCreationDataBase db =new AccountNumberCreationDataBase();
BorrowingCharacteristics1 component;
String cycleNumber;
String GroupId;
    public OtherLoanDetails2(String userId,BorrowingCharacteristics1 comp,String cycleNu) {
        
         
          
        initComponents();
        this.userId=userId;
        cycleNumber=cycleNu;
        component=comp;
   
        Image img = new ImageIcon(System.getProperty("user.dir")+"/"+"ICON_LOGO.jpg").getImage();
        this.setIconImage(img);
        this.setTitle("OTHER LOAN DETAILS"); 
//        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1IncomeLevel = new javax.swing.JComboBox();
        jLabel1IncomeLevel = new javax.swing.JLabel();
        jCheckBox1OccupationCategory = new javax.swing.JCheckBox();
        jLabel2OccupationCategory = new javax.swing.JLabel();
        jComboBox2OccupationCategory = new javax.swing.JComboBox();
        jLabel4PaymentSource = new javax.swing.JLabel();
        jComboBox4PaymentSource = new javax.swing.JComboBox();
        jCheckBox3PaymentSource = new javax.swing.JCheckBox();
        EconomicWelbeingLevel = new javax.swing.JLabel();
        jComboBox5EconomicWelbeingLevel = new javax.swing.JComboBox();
        jCheckBox5EconomicWelbeingLevel = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel21AmountTakenCategory = new javax.swing.JLabel();
        jComboBox21AmountTakenCategory = new javax.swing.JComboBox();
        jCheckBox7AmountTakenCategory = new javax.swing.JCheckBox();
        jLabel22EmploymentCategory = new javax.swing.JLabel();
        jComboBox22EmploymentCategory = new javax.swing.JComboBox();
        jCheckBox8IncomeLevel = new javax.swing.JCheckBox();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6NumberOfCollaterals = new javax.swing.JLabel();
        jComboBox6NumberOfCollaterals = new javax.swing.JComboBox();
        jCheckBox6NumberOfCollaterals = new javax.swing.JCheckBox();
        jComboBox7TenureType = new javax.swing.JComboBox();
        jLabel7TenureType = new javax.swing.JLabel();
        jLabel9PreviousHistory = new javax.swing.JLabel();
        jComboBox9PreviousHistory = new javax.swing.JComboBox();
        jLabel10LoanPurpose = new javax.swing.JLabel();
        jComboBox10LoanPurpose = new javax.swing.JComboBox();
        jCheckBox11LoanPurpose = new javax.swing.JCheckBox();
        jLabel11MarketingChannel = new javax.swing.JLabel();
        jComboBox11MarketingChannel = new javax.swing.JComboBox();
        jCheckBox12MarketingChannel = new javax.swing.JCheckBox();
        jCheckBox13LoanProduct = new javax.swing.JCheckBox();
        jComboBox12LoanProduct = new javax.swing.JComboBox();
        jLabel20ClientLoyalty = new javax.swing.JLabel();
        ClientLoyalty = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel23LoanProduct = new javax.swing.JLabel();
        jCheckBox2CollateralUsed = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel3Sex = new javax.swing.JLabel();
        jComboBox3Sex = new javax.swing.JComboBox();
        jLabel13MaritalStatus = new javax.swing.JLabel();
        jComboBox13MaritalStatus = new javax.swing.JComboBox();
        jLabel14AgeGroup = new javax.swing.JLabel();
        jComboBox14AgeGroup = new javax.swing.JComboBox();
        jLabel15EducationLevel = new javax.swing.JLabel();
        jComboBox15EducationLevel = new javax.swing.JComboBox();
        jLabel16PersonalCharacter = new javax.swing.JLabel();
        jComboBox16PersonalCharacter = new javax.swing.JComboBox();
        jLabel17Email = new javax.swing.JLabel();
        jLabel18PhoneNumber = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField15PhoneNumber = new javax.swing.JTextField();
        jLabel19PreferedContactChannel = new javax.swing.JLabel();
        jComboBox17PreferedContactChannel = new javax.swing.JComboBox();
        jTextField16Email = new javax.swing.JTextField();
        jButton51 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(983, 497));
        setMinimumSize(new java.awt.Dimension(983, 497));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(983, 497));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 153), new java.awt.Color(0, 204, 153)));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jComboBox1IncomeLevel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jComboBox1IncomeLevel);
        jComboBox1IncomeLevel.setBounds(640, 100, 180, 40);

        jLabel1IncomeLevel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1IncomeLevel.setText("Income Level");
        jLabel1IncomeLevel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel1IncomeLevel);
        jLabel1IncomeLevel.setBounds(470, 100, 170, 40);

        jCheckBox1OccupationCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox1OccupationCategory.setText("Specify");
        jCheckBox1OccupationCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox1OccupationCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1OccupationCategoryActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1OccupationCategory);
        jCheckBox1OccupationCategory.setBounds(820, 160, 80, 40);

        jLabel2OccupationCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2OccupationCategory.setText("Occupation Category");
        jLabel2OccupationCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel2OccupationCategory);
        jLabel2OccupationCategory.setBounds(470, 160, 170, 40);

        jComboBox2OccupationCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jComboBox2OccupationCategory);
        jComboBox2OccupationCategory.setBounds(640, 160, 180, 40);

        jLabel4PaymentSource.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4PaymentSource.setText("Payment Source");
        jLabel4PaymentSource.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel4PaymentSource);
        jLabel4PaymentSource.setBounds(470, 30, 170, 40);

        jComboBox4PaymentSource.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jComboBox4PaymentSource);
        jComboBox4PaymentSource.setBounds(640, 30, 180, 40);

        jCheckBox3PaymentSource.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox3PaymentSource.setText("Specify");
        jCheckBox3PaymentSource.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox3PaymentSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3PaymentSourceActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox3PaymentSource);
        jCheckBox3PaymentSource.setBounds(820, 30, 80, 40);

        EconomicWelbeingLevel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EconomicWelbeingLevel.setText("Economic Welbeing Level");
        EconomicWelbeingLevel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(EconomicWelbeingLevel);
        EconomicWelbeingLevel.setBounds(40, 30, 170, 40);

        jComboBox5EconomicWelbeingLevel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox5EconomicWelbeingLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5EconomicWelbeingLevelActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox5EconomicWelbeingLevel);
        jComboBox5EconomicWelbeingLevel.setBounds(210, 30, 180, 40);

        jCheckBox5EconomicWelbeingLevel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox5EconomicWelbeingLevel.setText("Specify");
        jCheckBox5EconomicWelbeingLevel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox5EconomicWelbeingLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5EconomicWelbeingLevelActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox5EconomicWelbeingLevel);
        jCheckBox5EconomicWelbeingLevel.setBounds(390, 30, 80, 40);

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(340, 260, 170, 50);

        jLabel21AmountTakenCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21AmountTakenCategory.setText("Amount Taken Category");
        jLabel21AmountTakenCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel21AmountTakenCategory);
        jLabel21AmountTakenCategory.setBounds(40, 100, 170, 40);

        jComboBox21AmountTakenCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jComboBox21AmountTakenCategory);
        jComboBox21AmountTakenCategory.setBounds(210, 100, 180, 40);

        jCheckBox7AmountTakenCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox7AmountTakenCategory.setText("Specify");
        jCheckBox7AmountTakenCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox7AmountTakenCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7AmountTakenCategoryActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox7AmountTakenCategory);
        jCheckBox7AmountTakenCategory.setBounds(390, 100, 80, 40);

        jLabel22EmploymentCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22EmploymentCategory.setText("Employment Category");
        jLabel22EmploymentCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel22EmploymentCategory);
        jLabel22EmploymentCategory.setBounds(40, 160, 170, 40);

        jComboBox22EmploymentCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox22EmploymentCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Employment Category", "Formal Employment", "Self Employment", "Other Employment" }));
        jPanel2.add(jComboBox22EmploymentCategory);
        jComboBox22EmploymentCategory.setBounds(210, 160, 220, 40);

        jCheckBox8IncomeLevel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox8IncomeLevel.setText("Specify");
        jCheckBox8IncomeLevel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox8IncomeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8IncomeLevelActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox8IncomeLevel);
        jCheckBox8IncomeLevel.setBounds(820, 100, 80, 40);

        jTextField9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jTextField9);
        jTextField9.setBounds(210, 30, 180, 40);
        jTextField9.setText("");

        jTextField10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jTextField10);
        jTextField10.setBounds(210, 100, 180, 40);
        jTextField12.setBounds(640, 30, 180, 40);
        jTextField10.setText("");

        jTextField11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jTextField11);
        jTextField11.setBounds(210, 160, 180, 40);
        jTextField13.setText("");

        jTextField12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jTextField12);
        jTextField12.setBounds(640, 30, 180, 40);
        jTextField12.setText("");

        jTextField13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jTextField13);
        jTextField13.setBounds(640, 100, 180, 40);
        jTextField13.setText("");

        jTextField14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(jTextField14);
        jTextField14.setBounds(640, 160, 180, 40);
        jTextField13.setText("");

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 20, 930, 470);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(null);

        jLabel6NumberOfCollaterals.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6NumberOfCollaterals.setText("Number Of Collaterals");
        jLabel6NumberOfCollaterals.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel6NumberOfCollaterals);
        jLabel6NumberOfCollaterals.setBounds(460, 290, 170, 40);
        jLabel6NumberOfCollaterals.setVisible(false);

        jComboBox6NumberOfCollaterals.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jComboBox6NumberOfCollaterals);
        jComboBox6NumberOfCollaterals.setBounds(630, 290, 180, 40);
        jComboBox6NumberOfCollaterals.setVisible(false);

        jCheckBox6NumberOfCollaterals.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox6NumberOfCollaterals.setText("Specify");
        jCheckBox6NumberOfCollaterals.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox6NumberOfCollaterals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6NumberOfCollateralsActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox6NumberOfCollaterals);
        jCheckBox6NumberOfCollaterals.setBounds(820, 290, 90, 40);
        jCheckBox6NumberOfCollaterals.setVisible(false);

        jComboBox7TenureType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox7TenureType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Security Type", "Land", "Titled Land", "Kibanja Land", "Real Estate", "Commercial Building", "Plant and Equipment", "Vehicle", "Vehicles", "Commercial Vehicles", "Marketable Securities", "Government Bond", "Treasury Bills", "Inventory", "Business Assets", "Chattels", "Bank Instruments", "Post Dated Cheque", "Other Collaterals", "Guarantors", "Guarantor1", "Guarantor2", "Guarantor3", "Savings", "Shares", "MontlyIncome" }));
        jPanel5.add(jComboBox7TenureType);
        jComboBox7TenureType.setBounds(190, 160, 180, 40);

        jLabel7TenureType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7TenureType.setText("Security Type");
        jLabel7TenureType.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel7TenureType);
        jLabel7TenureType.setBounds(20, 160, 170, 40);

        jLabel9PreviousHistory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9PreviousHistory.setText("Previous History");
        jLabel9PreviousHistory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel9PreviousHistory);
        jLabel9PreviousHistory.setBounds(20, 220, 170, 40);

        jComboBox9PreviousHistory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox9PreviousHistory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Previous History", "No History", "All Payments On Time", "Some Payments Over Due", "All Payments Over Due" }));
        jPanel5.add(jComboBox9PreviousHistory);
        jComboBox9PreviousHistory.setBounds(190, 220, 180, 40);

        jLabel10LoanPurpose.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10LoanPurpose.setText("Security Location");
        jLabel10LoanPurpose.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel10LoanPurpose);
        jLabel10LoanPurpose.setBounds(460, 160, 170, 40);

        jComboBox10LoanPurpose.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jComboBox10LoanPurpose);
        jComboBox10LoanPurpose.setBounds(630, 160, 180, 40);

        jCheckBox11LoanPurpose.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox11LoanPurpose.setText("Specify");
        jCheckBox11LoanPurpose.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox11LoanPurpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11LoanPurposeActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox11LoanPurpose);
        jCheckBox11LoanPurpose.setBounds(810, 160, 90, 40);

        jLabel11MarketingChannel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11MarketingChannel.setText("Client Location");
        jLabel11MarketingChannel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel11MarketingChannel);
        jLabel11MarketingChannel.setBounds(460, 90, 170, 40);

        jComboBox11MarketingChannel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jComboBox11MarketingChannel);
        jComboBox11MarketingChannel.setBounds(630, 90, 180, 40);

        jCheckBox12MarketingChannel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox12MarketingChannel.setText("Specify");
        jCheckBox12MarketingChannel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox12MarketingChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12MarketingChannelActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox12MarketingChannel);
        jCheckBox12MarketingChannel.setBounds(810, 90, 90, 40);

        jCheckBox13LoanProduct.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox13LoanProduct.setText("Specify");
        jCheckBox13LoanProduct.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox13LoanProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13LoanProductActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox13LoanProduct);
        jCheckBox13LoanProduct.setBounds(370, 90, 90, 40);

        jComboBox12LoanProduct.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jComboBox12LoanProduct);
        jComboBox12LoanProduct.setBounds(190, 90, 180, 40);

        jLabel20ClientLoyalty.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20ClientLoyalty.setText("Client Loyalty");
        jLabel20ClientLoyalty.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel20ClientLoyalty);
        jLabel20ClientLoyalty.setBounds(460, 220, 170, 40);

        ClientLoyalty.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ClientLoyalty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Client Loyalty", "Very Old Loyal Customer", "Old Loyal Customer", "Relatively New Loyal Customer", "New Loyal Customer", "Very New Loyal Customer", "Can't Tell" }));
        jPanel5.add(ClientLoyalty);
        ClientLoyalty.setBounds(630, 220, 200, 40);

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(320, 350, 170, 50);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jTextField1);
        jTextField1.setBounds(640, 220, 180, 40);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jTextField2);
        jTextField2.setBounds(190, 90, 180, 40);
        jTextField2.setText("");

        jTextField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jTextField3);
        jTextField3.setBounds(630, 290, 180, 40);
        jTextField3.setVisible(false);

        jTextField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jTextField4);
        jTextField4.setBounds(190, 160, 180, 40);

        jTextField6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jTextField6);
        jTextField6.setBounds(190, 220, 180, 40);

        jTextField7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jTextField7);
        jTextField7.setBounds(630, 160, 180, 40);

        jTextField8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(jTextField8);
        jTextField8.setBounds(630, 90, 180, 40);

        jLabel23LoanProduct.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23LoanProduct.setText("Loan Product");
        jLabel23LoanProduct.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel23LoanProduct);
        jLabel23LoanProduct.setBounds(20, 90, 170, 40);

        jCheckBox2CollateralUsed.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox2CollateralUsed.setText("Collateral Used");
        jCheckBox2CollateralUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2CollateralUsedActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox2CollateralUsed);
        jCheckBox2CollateralUsed.setBounds(30, 280, 340, 40);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(30, 20, 930, 470);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel3Sex.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3Sex.setText("Sex");
        jLabel3Sex.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel3Sex);
        jLabel3Sex.setBounds(40, 60, 170, 40);

        jComboBox3Sex.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox3Sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel6.add(jComboBox3Sex);
        jComboBox3Sex.setBounds(210, 60, 180, 40);

        jLabel13MaritalStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13MaritalStatus.setText("Marital Status");
        jLabel13MaritalStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel13MaritalStatus);
        jLabel13MaritalStatus.setBounds(480, 60, 170, 40);

        jComboBox13MaritalStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox13MaritalStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married", "Devorced", "Separated", "Corting" }));
        jPanel6.add(jComboBox13MaritalStatus);
        jComboBox13MaritalStatus.setBounds(650, 60, 180, 40);

        jLabel14AgeGroup.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14AgeGroup.setText("Age Group");
        jLabel14AgeGroup.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel14AgeGroup);
        jLabel14AgeGroup.setBounds(40, 120, 170, 40);

        jComboBox14AgeGroup.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox14AgeGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Minor", "Below 18Yrs", "Between 18Yrs-35Yrs", "Between 36Yrs-60Yrs", "Above 60Yrs" }));
        jPanel6.add(jComboBox14AgeGroup);
        jComboBox14AgeGroup.setBounds(210, 120, 180, 40);

        jLabel15EducationLevel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15EducationLevel.setText("Education Level");
        jLabel15EducationLevel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel15EducationLevel);
        jLabel15EducationLevel.setBounds(480, 120, 170, 40);

        jComboBox15EducationLevel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox15EducationLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Education", "Pre-Primary", "Secondary", "Tertiary", "Under Graduate", "Post Graduate" }));
        jPanel6.add(jComboBox15EducationLevel);
        jComboBox15EducationLevel.setBounds(650, 120, 180, 40);

        jLabel16PersonalCharacter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16PersonalCharacter.setText("Personal Character");
        jLabel16PersonalCharacter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel16PersonalCharacter);
        jLabel16PersonalCharacter.setBounds(40, 240, 170, 40);

        jComboBox16PersonalCharacter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox16PersonalCharacter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Excellent", "Very Good", "Good", "Bad", "Very Bad" }));
        jPanel6.add(jComboBox16PersonalCharacter);
        jComboBox16PersonalCharacter.setBounds(210, 240, 180, 40);

        jLabel17Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17Email.setText("Email");
        jLabel17Email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel17Email);
        jLabel17Email.setBounds(480, 180, 60, 40);

        jLabel18PhoneNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18PhoneNumber.setText("Phone Number");
        jLabel18PhoneNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel18PhoneNumber);
        jLabel18PhoneNumber.setBounds(480, 240, 110, 40);

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(340, 310, 170, 50);

        jTextField15PhoneNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel6.add(jTextField15PhoneNumber);
        jTextField15PhoneNumber.setBounds(590, 240, 240, 40);

        jLabel19PreferedContactChannel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19PreferedContactChannel.setText("Prefered Contact Channel");
        jLabel19PreferedContactChannel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel19PreferedContactChannel);
        jLabel19PreferedContactChannel.setBounds(40, 180, 170, 40);

        jComboBox17PreferedContactChannel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox17PreferedContactChannel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Email", "Phone Call", "Sms", "WhatsApp", "Letter" }));
        jPanel6.add(jComboBox17PreferedContactChannel);
        jComboBox17PreferedContactChannel.setBounds(210, 180, 180, 40);

        jTextField16Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField16Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16EmailActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField16Email);
        jTextField16Email.setBounds(540, 180, 290, 40);
        jTextField16Email.setText("");

        jPanel1.add(jPanel6);
        jPanel6.setBounds(30, 20, 930, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 970, 550);

        jButton51.setBackground(new java.awt.Color(0, 51, 51));
        jButton51.setText("jButton5");
        getContentPane().add(jButton51);
        jButton51.setBounds(1800, 360, 73, 23);

        jButton50.setBackground(java.awt.SystemColor.controlLtHighlight);
        jButton50.setText("jButton5");
        getContentPane().add(jButton50);
        jButton50.setBounds(1790, 330, 73, 23);

        jButton49.setBackground(new java.awt.Color(255, 204, 204));
        jButton49.setText("jButton5");
        getContentPane().add(jButton49);
        jButton49.setBounds(1870, 320, 73, 23);

        jButton31.setBackground(new java.awt.Color(255, 204, 153));
        jButton31.setText("Blue");
        getContentPane().add(jButton31);
        jButton31.setBounds(1810, 310, 53, 23);

        jButton38.setBackground(new java.awt.Color(204, 204, 0));
        jButton38.setText("Blue");
        getContentPane().add(jButton38);
        jButton38.setBounds(1810, 290, 53, 23);

        jButton32.setBackground(new java.awt.Color(0, 153, 153));
        jButton32.setText("Blue");
        getContentPane().add(jButton32);
        jButton32.setBounds(1870, 290, 53, 23);

        jButton47.setBackground(new java.awt.Color(204, 255, 204));
        jButton47.setText("Blue");
        getContentPane().add(jButton47);
        jButton47.setBounds(1930, 290, 53, 23);

        jButton29.setBackground(new java.awt.Color(0, 204, 204));
        jButton29.setText("Blue");
        getContentPane().add(jButton29);
        jButton29.setBounds(1920, 270, 53, 23);

        jButton37.setBackground(new java.awt.Color(204, 153, 255));
        jButton37.setText("Blue");
        getContentPane().add(jButton37);
        jButton37.setBounds(1870, 270, 53, 23);

        jButton33.setBackground(new java.awt.Color(152, 198, 94));
        jButton33.setText("Blue");
        getContentPane().add(jButton33);
        jButton33.setBounds(1810, 270, 53, 23);

        jButton35.setBackground(new java.awt.Color(255, 204, 204));
        jButton35.setText("Blue");
        getContentPane().add(jButton35);
        jButton35.setBounds(1810, 250, 53, 23);

        jButton45.setBackground(new java.awt.Color(255, 255, 204));
        jButton45.setText("Blue");
        getContentPane().add(jButton45);
        jButton45.setBounds(1870, 250, 53, 23);

        jButton42.setBackground(new java.awt.Color(0, 204, 102));
        jButton42.setText("Blue");
        getContentPane().add(jButton42);
        jButton42.setBounds(1920, 230, 53, 23);

        jButton43.setBackground(new java.awt.Color(204, 204, 204));
        jButton43.setText("Blue");
        getContentPane().add(jButton43);
        jButton43.setBounds(1870, 230, 53, 23);

        jButton30.setBackground(new java.awt.Color(0, 153, 255));
        jButton30.setText("Blue");
        getContentPane().add(jButton30);
        jButton30.setBounds(1810, 230, 53, 23);

        jButton36.setBackground(java.awt.SystemColor.activeCaption);
        jButton36.setText("Blue");
        getContentPane().add(jButton36);
        jButton36.setBounds(1810, 210, 53, 23);

        jButton44.setBackground(new java.awt.Color(204, 165, 165));
        jButton44.setText("Blue");
        getContentPane().add(jButton44);
        jButton44.setBounds(1870, 210, 53, 23);

        jButton39.setBackground(new java.awt.Color(204, 204, 255));
        jButton39.setText("Blue");
        getContentPane().add(jButton39);
        jButton39.setBounds(1920, 210, 53, 23);

        jButton41.setBackground(java.awt.SystemColor.activeCaption);
        jButton41.setText("Blue");
        getContentPane().add(jButton41);
        jButton41.setBounds(1920, 190, 53, 23);

        jButton46.setBackground(java.awt.SystemColor.activeCaption);
        jButton46.setText("Blue");
        getContentPane().add(jButton46);
        jButton46.setBounds(1870, 190, 53, 23);

        jButton40.setBackground(java.awt.SystemColor.activeCaption);
        jButton40.setText("Blue");
        getContentPane().add(jButton40);
        jButton40.setBounds(1810, 190, 53, 23);

        jButton48.setBackground(new java.awt.Color(201, 222, 223));
        jButton48.setText("Blue");
        getContentPane().add(jButton48);
        jButton48.setBounds(1870, 170, 53, 23);

        jButton52.setBackground(new java.awt.Color(0, 51, 51));
        jButton52.setText("jButton5");
        getContentPane().add(jButton52);
        jButton52.setBounds(1800, 360, 73, 23);

        jButton53.setBackground(java.awt.SystemColor.controlLtHighlight);
        jButton53.setText("jButton5");
        getContentPane().add(jButton53);
        jButton53.setBounds(1790, 330, 73, 23);

        jButton54.setBackground(new java.awt.Color(255, 204, 204));
        jButton54.setText("jButton5");
        getContentPane().add(jButton54);
        jButton54.setBounds(1870, 320, 73, 23);

        jButton34.setBackground(new java.awt.Color(255, 204, 153));
        jButton34.setText("Blue");
        getContentPane().add(jButton34);
        jButton34.setBounds(1810, 310, 53, 23);

        jButton55.setBackground(new java.awt.Color(204, 204, 0));
        jButton55.setText("Blue");
        getContentPane().add(jButton55);
        jButton55.setBounds(1810, 290, 53, 23);

        jButton56.setBackground(new java.awt.Color(0, 153, 153));
        jButton56.setText("Blue");
        getContentPane().add(jButton56);
        jButton56.setBounds(1870, 290, 53, 23);

        jButton57.setBackground(new java.awt.Color(204, 255, 204));
        jButton57.setText("Blue");
        getContentPane().add(jButton57);
        jButton57.setBounds(1930, 290, 53, 23);

        jButton58.setBackground(new java.awt.Color(0, 204, 204));
        jButton58.setText("Blue");
        getContentPane().add(jButton58);
        jButton58.setBounds(1920, 270, 53, 23);

        jButton59.setBackground(new java.awt.Color(204, 153, 255));
        jButton59.setText("Blue");
        getContentPane().add(jButton59);
        jButton59.setBounds(1870, 270, 53, 23);

        jButton60.setBackground(new java.awt.Color(152, 198, 94));
        jButton60.setText("Blue");
        getContentPane().add(jButton60);
        jButton60.setBounds(1810, 270, 53, 23);

        jButton61.setBackground(new java.awt.Color(255, 204, 204));
        jButton61.setText("Blue");
        getContentPane().add(jButton61);
        jButton61.setBounds(1810, 250, 53, 23);

        jButton62.setBackground(new java.awt.Color(255, 255, 204));
        jButton62.setText("Blue");
        getContentPane().add(jButton62);
        jButton62.setBounds(1870, 250, 53, 23);

        jButton63.setBackground(new java.awt.Color(0, 204, 102));
        jButton63.setText("Blue");
        getContentPane().add(jButton63);
        jButton63.setBounds(1920, 230, 53, 23);

        jButton64.setBackground(new java.awt.Color(204, 204, 204));
        jButton64.setText("Blue");
        getContentPane().add(jButton64);
        jButton64.setBounds(1870, 230, 53, 23);

        jButton65.setBackground(new java.awt.Color(0, 153, 255));
        jButton65.setText("Blue");
        getContentPane().add(jButton65);
        jButton65.setBounds(1810, 230, 53, 23);

        jButton66.setBackground(java.awt.SystemColor.activeCaption);
        jButton66.setText("Blue");
        getContentPane().add(jButton66);
        jButton66.setBounds(1810, 210, 53, 23);

        jButton67.setBackground(new java.awt.Color(204, 165, 165));
        jButton67.setText("Blue");
        getContentPane().add(jButton67);
        jButton67.setBounds(1870, 210, 53, 23);

        jButton68.setBackground(new java.awt.Color(204, 204, 255));
        jButton68.setText("Blue");
        getContentPane().add(jButton68);
        jButton68.setBounds(1920, 210, 53, 23);

        jButton69.setBackground(java.awt.SystemColor.activeCaption);
        jButton69.setText("Blue");
        getContentPane().add(jButton69);
        jButton69.setBounds(1920, 190, 53, 23);

        jButton70.setBackground(java.awt.SystemColor.activeCaption);
        jButton70.setText("Blue");
        getContentPane().add(jButton70);
        jButton70.setBounds(1870, 190, 53, 23);

        jButton71.setBackground(java.awt.SystemColor.activeCaption);
        jButton71.setText("Blue");
        getContentPane().add(jButton71);
        jButton71.setBounds(1810, 190, 53, 23);

        jButton72.setBackground(new java.awt.Color(201, 222, 223));
        jButton72.setText("Blue");
        getContentPane().add(jButton72);
        jButton72.setBounds(1870, 170, 53, 23);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//JOptionPane.showMessageDialog(this, cycleNumber);
        String activeAccountNumber=fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+userId+".txt"));
        List theItems=loan.otherLoanDetailsForUpatex(activeAccountNumber,cycleNumber);
        switch(fios.intFileReader(fios.createFileName("loanApplication", "amortValues", "OtherLoanDetails"+this.userId+".txt"))){
        case 7:
        jPanel5.setVisible(true);
        jPanel2.setVisible(false);
        jPanel6.setVisible(false);
//        jPanel4.setVisible(false);
        
           loan.fillOtherDetailsComboOptionsLoanProduct(jComboBox12LoanProduct);
        jComboBox12LoanProduct.setEnabled(true);
        jComboBox12LoanProduct.getModel().setSelectedItem(theItems.get(4).toString());
   loan.fillOtherDetailsComboOptionsNumberOfCollaterals(jComboBox6NumberOfCollaterals);
//   JOptionPane.showMessageDialog(this, theItems.get(9).toString());
  if(theItems.get(10).toString().equalsIgnoreCase("Yes")){
jCheckBox2CollateralUsed.setSelected(true);
jComboBox6NumberOfCollaterals.getModel().setSelectedItem(theItems.get(11).toString());
jComboBox6NumberOfCollaterals.setVisible(true);
jLabel6NumberOfCollaterals.setVisible(true);
  }else if(theItems.get(10).toString().equalsIgnoreCase("No")){
  jCheckBox2CollateralUsed.setSelected(false);
  jComboBox6NumberOfCollaterals.setVisible(false);
  }
   loan.fillOtherDetailsComboOptionsMarketingSource(jComboBox11MarketingChannel);
jComboBox11MarketingChannel.getModel().setSelectedItem(theItems.get(5).toString());
    jComboBox7TenureType  .getModel().setSelectedItem(theItems.get(6).toString());  
        loan.fillOtherDetailsComboOptionsLoanPurpose(jComboBox10LoanPurpose);
        
       jComboBox10LoanPurpose.getModel().setSelectedItem(theItems.get(7).toString());
        
jComboBox9PreviousHistory.getModel().setSelectedItem(theItems.get(8).toString());

ClientLoyalty.getModel().setSelectedItem(theItems.get(9).toString());
        break;
        case 77:
        jPanel5.setVisible(false);
        jPanel2.setVisible(true);
        jPanel6.setVisible(false);
//        jPanel4.setVisible(false); 


        loan.fillOtherDetailsComboOptionsEconomicWelbeingLevel(jComboBox5EconomicWelbeingLevel);
        
                jComboBox5EconomicWelbeingLevel.getModel().setSelectedItem(theItems.get(12).toString());
                
        loan.fillOtherDetailsComboOptionsRepaymentSource(jComboBox4PaymentSource);
        jComboBox4PaymentSource.getModel().setSelectedItem(theItems.get(13).toString());
        loan.fillOtherDetailsComboOptionsAmountTakenCategory(jComboBox21AmountTakenCategory);
        jComboBox21AmountTakenCategory.getModel().setSelectedItem(theItems.get(14).toString());
        loan.fillOtherDetailsComboOptionsIncomeLevel(jComboBox1IncomeLevel);
        jComboBox1IncomeLevel.getModel().setSelectedItem(theItems.get(15).toString());
        loan.fillOtherDetailsComboOptionsCycleOccupation(jComboBox2OccupationCategory);
        jComboBox22EmploymentCategory.getModel().setSelectedItem(theItems.get(16).toString());
        jComboBox2OccupationCategory.getModel().setSelectedItem(theItems.get(17).toString());
        break;
        case 777:
        jPanel5.setVisible(false);
        jPanel2.setVisible(false);
        jPanel6.setVisible(true);
          jComboBox3Sex.getModel().setSelectedItem(theItems.get(18).toString());
          jComboBox13MaritalStatus.getModel().setSelectedItem(theItems.get(19).toString());
           jComboBox14AgeGroup.getModel().setSelectedItem(theItems.get(20).toString());
           jComboBox15EducationLevel.getModel().setSelectedItem(theItems.get(21).toString());
           jComboBox17PreferedContactChannel.getModel().setSelectedItem(theItems.get(22).toString());
//             dbq.fillWithBiodataContactNumberIfExists(jTextField16Email,activeAccountNumber);
           jTextField16Email.setText(theItems.get(23).toString());
      jTextField15PhoneNumber.setText(theItems.get(25).toString());
//          dbq.fillWithBiodataContactMobileIfExists(jTextField15PhoneNumber,activeAccountNumber);
        
        break;
        case 7777:
        jPanel5.setVisible(false);
        jPanel2.setVisible(false);
        jPanel6.setVisible(false);
//        jPanel4.setVisible(true); 

        break;   
        }

    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(jCheckBox5EconomicWelbeingLevel.isSelected()){
        
              if(jTextField9.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the Economic Welbeing!!!");
            return;
            }else{
            component.addItemInList(jTextField9.getText());
            }
            
            
        }else if(!jCheckBox5EconomicWelbeingLevel.isSelected()){
        
            if(jComboBox5EconomicWelbeingLevel.getSelectedItem().toString().equalsIgnoreCase("Select EconomicWelbeingLevel")){
        
         JOptionPane.showMessageDialog(this, "Please first Select the Economic Welbeing!!!");
            return;
        
        
        }else {
        
         component.addItemInList(jComboBox5EconomicWelbeingLevel.getSelectedItem().toString());
        
        }
            
            
            
        
        }
        
        if(jCheckBox3PaymentSource.isSelected()){
        
              if(jTextField12.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the Payment Source!!!");
            return;
            }else{
            component.addItemInList(jTextField12.getText());
            }
            
            
        }else if(!jCheckBox3PaymentSource.isSelected()){
        
            if(jComboBox4PaymentSource.getSelectedItem().toString().equalsIgnoreCase("Select RepaymentSource")){
        
         JOptionPane.showMessageDialog(this, "Please first Select the Payment Source!!!");
            return;
        
        
        }else {
        
         component.addItemInList(jComboBox4PaymentSource.getSelectedItem().toString());
        
        }
            
            
            
        
        }
        if(jCheckBox7AmountTakenCategory.isSelected()){
        
              if(jTextField10.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the Amount Taken Category!!!");
            return;
            }else{
            component.addItemInList(jTextField10.getText());
            }
            
            
        }else if(!jCheckBox7AmountTakenCategory.isSelected()){
        
            if(jComboBox21AmountTakenCategory.getSelectedItem().toString().equalsIgnoreCase("Select amountTakenCat")){
        
         JOptionPane.showMessageDialog(this, "Please first Select the Amount Taken Category!!!");
            return;
        
        
        }else {
        
         component.addItemInList(jComboBox21AmountTakenCategory.getSelectedItem().toString());
        
        }
            
            
            
        
        }
         if(jCheckBox8IncomeLevel.isSelected()){
        
              if(jTextField13.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the Income Level Category!!!");
            return;
            }else{
            component.addItemInList(jTextField13.getText());
            }
            
            
        }else if(!jCheckBox8IncomeLevel.isSelected()){
        
            if(jComboBox1IncomeLevel.getSelectedItem().toString().equalsIgnoreCase("Select Income Level")){
        
         JOptionPane.showMessageDialog(this, "Please first Select the Income Level Category!!!");
            return;
        
        
        }else {
        
         component.addItemInList(jComboBox1IncomeLevel.getSelectedItem().toString());
        
        }
        }
        
//               if(jCheckBox8.isSelected()){
//        
//              if(jTextField13.getText().equalsIgnoreCase("")){
//            JOptionPane.showMessageDialog(this, "Please first input the Income Level Category!!!");
//            return;
//            }else{
//            component.addItemInList(jTextField13.getText());
//            }
//            
//            
//        }else if(!jCheckBox8.isSelected()){
//        
//            if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Select Income Level")){
//        
//         JOptionPane.showMessageDialog(this, "Please first Select the Income Level Category!!!");
//            return;
//        
//        
//        }else {
//        
//         component.addItemInList(jComboBox1.getSelectedItem().toString());
//        
//        }
//        }
       
                if(jComboBox22EmploymentCategory.getSelectedItem().toString().equalsIgnoreCase("Select Employment Category")){
        
         JOptionPane.showMessageDialog(this, "Please first Select the Employment Category!!!");
            return;
        
        
        }else {
        
         component.addItemInList(jComboBox22EmploymentCategory.getSelectedItem().toString());
        
        }
          
                
        if(jCheckBox1OccupationCategory.isSelected()){
        
              if(jTextField14.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the Occupation Category!!!");
            return;
            }else{
            component.addItemInList(jTextField14.getText());
            }
            
            
        }else if(!jCheckBox1OccupationCategory.isSelected()){
        
            if(jComboBox2OccupationCategory.getSelectedItem().toString().equalsIgnoreCase("Select Occupation")){
        
         JOptionPane.showMessageDialog(this, "Please first Select the Occupation Category!!!");
            return;
        
        
        }else {
        
         component.addItemInList(jComboBox2OccupationCategory.getSelectedItem().toString());
        
        }
            
            
            
        
        }
        
               
         
        component.setTheField("Economic Status");   
        
          this.dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(jCheckBox13LoanProduct.isSelected()){
        
            if(jTextField2.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the Loan Product!!!");
            return;
            }else{
            component.addItemInList(jTextField2.getText());
            }
            
        }else if(!jCheckBox13LoanProduct.isSelected()){
            
        if(jComboBox12LoanProduct.getSelectedItem().toString().equalsIgnoreCase("Select Loan Product")){
        
         JOptionPane.showMessageDialog(this, "Please first Select the Loan Product!!!");
            return;
        
        
        }else {
        
         component.addItemInList(jComboBox12LoanProduct.getSelectedItem().toString());
        
        }
            
            
        
        }
        
        
        
         if(jCheckBox12MarketingChannel.isSelected()){
        
            if(jTextField8.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the Marketing Channel!!!");
            return;
            }else{
            component.addItemInList(jTextField8.getText());
            }
            
        }else if(!jCheckBox12MarketingChannel.isSelected()){
        if(jComboBox11MarketingChannel.getSelectedItem().toString().equalsIgnoreCase("Select MarketingChannel")){
        
         JOptionPane.showMessageDialog(this, "Please first Select The Marketing Channel Used!!!");
            return;
        }else {
        
         component.addItemInList(jComboBox11MarketingChannel.getSelectedItem().toString());
        
        }
        }
        
         
        if(jComboBox7TenureType.getSelectedItem().toString().equalsIgnoreCase("Select Tenure Type")){
        
         JOptionPane.showMessageDialog(this, "Please first Select The Tenure Type!!!");
            return;
        }else {
        
         component.addItemInList(jComboBox7TenureType.getSelectedItem().toString());
        
        }
        
         if(jCheckBox11LoanPurpose.isSelected()){
        
            if(jTextField7.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the Loan Purpose!!!");
            return;
            }else{
            component.addItemInList(jTextField7.getText());
            }
            
        }else if(!jCheckBox11LoanPurpose.isSelected()){
        if(jComboBox10LoanPurpose.getSelectedItem().toString().equalsIgnoreCase("Select Loan Purpose")){
        
         JOptionPane.showMessageDialog(this, "Please first Select Loan Purpose!!!");
            return;
        }else {
        
         component.addItemInList(jComboBox10LoanPurpose.getSelectedItem().toString());
        
        }
        }
        
        if(jComboBox9PreviousHistory.getSelectedItem().toString().equalsIgnoreCase("Select Previous History")){
        
         JOptionPane.showMessageDialog(this, "Please first Select The Previous History!!!");
            return;
        }else {
        
         component.addItemInList(jComboBox9PreviousHistory.getSelectedItem().toString());
        
        }
        
        
          if(ClientLoyalty.getSelectedItem().toString().equalsIgnoreCase("Select Client Loyalty")){
        
         JOptionPane.showMessageDialog(this, "Please first Select The  Client Loyalty!!!");
            return;
        }else {
        
         component.addItemInList(ClientLoyalty.getSelectedItem().toString());
        
        }
          
       if(jCheckBox2CollateralUsed.isSelected()){
       component.addItemInList("Yes");
       
         if(jCheckBox6NumberOfCollaterals.isSelected()){
        
            if(jTextField3.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Please first input the Number of collaterals Used!!!");
            return;
            }else{
            component.addItemInList(jTextField3.getText());
            }
            
        }else if(!jCheckBox6NumberOfCollaterals.isSelected()){
        if(jComboBox6NumberOfCollaterals.getSelectedItem().toString().equalsIgnoreCase("Select NumberOfCollaterals")){
        
         JOptionPane.showMessageDialog(this, "Please first Select The Number Of Collaterals Used!!!");
            return;
        }else {
        
         component.addItemInList(jComboBox6NumberOfCollaterals.getSelectedItem().toString());
        
        }
        }
       
       
       }else if(!jCheckBox2CollateralUsed.isSelected()){
       component.addItemInList("No");
        component.addItemInList("0");
       
       }   
          
          
        
        component.setTheField("Other Loan Details");   
        
          this.dispose();  
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
         component.addItemInList(jComboBox3Sex.getSelectedItem().toString());
          component.addItemInList(jComboBox13MaritalStatus.getSelectedItem().toString());
           component.addItemInList(jComboBox14AgeGroup.getSelectedItem().toString());
           component.addItemInList(jComboBox15EducationLevel.getSelectedItem().toString());
            component.addItemInList(jComboBox17PreferedContactChannel.getSelectedItem().toString());
           
//           if(jTextField16.getText().equalsIgnoreCase("")){
//           JOptionPane.showMessageDialog(this, "Please first input the Email Address!!!");
//           }else {
//           component.addItemInList(jTextField16.getText());
//           }
//           
//             if(jTextField16.getText().equalsIgnoreCase("")){
//           JOptionPane.showMessageDialog(this, "Please first input the Email Address!!!");
//           }else {
//           component.addItemInList(jTextField16.getText());
//           }
             
//     component.addItemInList(jComboBox16.getSelectedItem().toString());        
               if(jTextField16Email.getText().equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(this, "Please first input the Email Address!!!");
           return;
           }else {
           component.addItemInList(jTextField16Email.getText());
           
           }
          component.addItemInList(jComboBox16PersonalCharacter.getSelectedItem().toString()); 
             if(jTextField15PhoneNumber.getText().equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(this, "Please first input the Mobile Number!!!");
            return;
           }else {
           component.addItemInList(jTextField15PhoneNumber.getText());
           }
            component.jPanel2GroupAssignmentPanel.setEnabled(false);
             component.jPanel2GroupAssignmentPanel.setVisible(false);
            component.updateOnlyGroups.setEnabled(false);
                   component. updateAllDetails.setEnabled(false);
                 component.   jLabel125.setEnabled(false);
                  component. jCheckBox15.setEnabled(false);
                       component.    newLoanPanel1.setEnabled(false);
                        component.   jCheckBox16.setEnabled(false);
                              component.     jLabel123.setEnabled(false);
                                component.   jTextField13.setEnabled(false);
                                        component.   jLabel124.setEnabled(false);
                                         component.  jTextField14.setEnabled(false);
                                               component.    jComboBox1.setEnabled(false);
                                                component.addItemInList(fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+userId+".txt")));
        component.setTheField("Bio Data");   
        
          this.dispose();  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox6NumberOfCollateralsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6NumberOfCollateralsActionPerformed
      if(jCheckBox6NumberOfCollaterals.isSelected()){
     jComboBox6NumberOfCollaterals.setVisible(false);
     jTextField3.setVisible(true);
     }else if(!jCheckBox6NumberOfCollaterals.isSelected()){
     
       jComboBox6NumberOfCollaterals.setVisible(true);
     jTextField3.setVisible(false);
     
     }
    }//GEN-LAST:event_jCheckBox6NumberOfCollateralsActionPerformed

    private void jCheckBox11LoanPurposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11LoanPurposeActionPerformed
       if(jCheckBox11LoanPurpose.isSelected()){
     jComboBox10LoanPurpose.setVisible(false);
     jTextField7.setVisible(true);
     }else if(!jCheckBox11LoanPurpose.isSelected()){
     
       jComboBox10LoanPurpose.setVisible(true);
     jTextField7.setVisible(false);
     
     }
    }//GEN-LAST:event_jCheckBox11LoanPurposeActionPerformed

    private void jCheckBox12MarketingChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12MarketingChannelActionPerformed
        if(jCheckBox12MarketingChannel.isSelected()){
     jComboBox11MarketingChannel.setVisible(false);
     jTextField8.setVisible(true);
     }else if(!jCheckBox12MarketingChannel.isSelected()){
     
       jComboBox11MarketingChannel.setVisible(true);
     jTextField8.setVisible(false);
     
     }
    }//GEN-LAST:event_jCheckBox12MarketingChannelActionPerformed

    private void jCheckBox13LoanProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13LoanProductActionPerformed
        if(jCheckBox13LoanProduct.isSelected()){
            jComboBox12LoanProduct.setVisible(false);
            jTextField2.setVisible(true);
        }else if(!jCheckBox13LoanProduct.isSelected()){

            jComboBox12LoanProduct.setVisible(true);
            jTextField2.setVisible(false);

        }
    }//GEN-LAST:event_jCheckBox13LoanProductActionPerformed

    private void jCheckBox5EconomicWelbeingLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5EconomicWelbeingLevelActionPerformed
       if(jCheckBox5EconomicWelbeingLevel.isSelected()){
            jComboBox5EconomicWelbeingLevel.setVisible(false);
            jTextField9.setVisible(true);
        }else if(!jCheckBox5EconomicWelbeingLevel.isSelected()){

            jComboBox5EconomicWelbeingLevel.setVisible(true);
            jTextField9.setVisible(false);

        }
    }//GEN-LAST:event_jCheckBox5EconomicWelbeingLevelActionPerformed

    private void jCheckBox3PaymentSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3PaymentSourceActionPerformed
           if(jCheckBox3PaymentSource.isSelected()){
            jComboBox4PaymentSource.setVisible(false);
            jTextField12.setVisible(true);
        }else if(!jCheckBox3PaymentSource.isSelected()){

            jComboBox4PaymentSource.setVisible(true);
            jTextField12.setVisible(false);

        }
    }//GEN-LAST:event_jCheckBox3PaymentSourceActionPerformed

    private void jCheckBox7AmountTakenCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7AmountTakenCategoryActionPerformed
           if(jCheckBox7AmountTakenCategory.isSelected()){
            jComboBox21AmountTakenCategory.setVisible(false);
            jTextField10.setVisible(true);
        }else if(!jCheckBox7AmountTakenCategory.isSelected()){

            jComboBox21AmountTakenCategory.setVisible(true);
            jTextField10.setVisible(false);

        }
    }//GEN-LAST:event_jCheckBox7AmountTakenCategoryActionPerformed

    private void jCheckBox8IncomeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8IncomeLevelActionPerformed
          if(jCheckBox8IncomeLevel.isSelected()){
            jComboBox1IncomeLevel.setVisible(false);
            jTextField13.setVisible(true);
        }else if(!jCheckBox8IncomeLevel.isSelected()){

            jComboBox1IncomeLevel.setVisible(true);
            jTextField13.setVisible(false);

        }
    }//GEN-LAST:event_jCheckBox8IncomeLevelActionPerformed

    private void jCheckBox1OccupationCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1OccupationCategoryActionPerformed
         if(jCheckBox1OccupationCategory.isSelected()){
            jComboBox2OccupationCategory.setVisible(false);
            jTextField14.setVisible(true);
        }else if(!jCheckBox1OccupationCategory.isSelected()){

            jComboBox2OccupationCategory.setVisible(true);
            jTextField14.setVisible(false);

        }
    }//GEN-LAST:event_jCheckBox1OccupationCategoryActionPerformed

    private void jCheckBox2CollateralUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2CollateralUsedActionPerformed
     if(jCheckBox2CollateralUsed.isSelected()){
     jLabel6NumberOfCollaterals.setVisible(true);
     jComboBox6NumberOfCollaterals.setVisible(true);
     jCheckBox6NumberOfCollaterals.setVisible(true);
     }else if(!jCheckBox2CollateralUsed.isSelected()){
     
      jLabel6NumberOfCollaterals.setVisible(false);
     jComboBox6NumberOfCollaterals.setVisible(false);
     jCheckBox6NumberOfCollaterals.setVisible(false);
     }
    }//GEN-LAST:event_jCheckBox2CollateralUsedActionPerformed

    private void jTextField16EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16EmailActionPerformed

    }//GEN-LAST:event_jTextField16EmailActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int i=1;
     while(i<=5){
     
     JOptionPane.showMessageDialog(this, "SYSTEM LOG OUT ERROR!!!!!!!!!");}
    }//GEN-LAST:event_formWindowClosing

    private void jComboBox5EconomicWelbeingLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5EconomicWelbeingLevelActionPerformed
    
    }//GEN-LAST:event_jComboBox5EconomicWelbeingLevelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
////        public static String u=AddBatch.this.userId;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddBatch().setVisible(true);
//            }
//        });
//    }
   private void sortTable(JTable table,JTextField textField){

   
    
TableRowSorter<TableModel> rowSorter  = new TableRowSorter<>(table.getModel());
                     
                      table.setRowSorter(rowSorter);
                     textField.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = textField.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = textField.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    

}
   
     
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ClientLoyalty;
    private javax.swing.JLabel EconomicWelbeingLevel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JCheckBox jCheckBox11LoanPurpose;
    private javax.swing.JCheckBox jCheckBox12MarketingChannel;
    private javax.swing.JCheckBox jCheckBox13LoanProduct;
    private javax.swing.JCheckBox jCheckBox1OccupationCategory;
    private javax.swing.JCheckBox jCheckBox2CollateralUsed;
    private javax.swing.JCheckBox jCheckBox3PaymentSource;
    private javax.swing.JCheckBox jCheckBox5EconomicWelbeingLevel;
    private javax.swing.JCheckBox jCheckBox6NumberOfCollaterals;
    private javax.swing.JCheckBox jCheckBox7AmountTakenCategory;
    private javax.swing.JCheckBox jCheckBox8IncomeLevel;
    private javax.swing.JComboBox jComboBox10LoanPurpose;
    private javax.swing.JComboBox jComboBox11MarketingChannel;
    private javax.swing.JComboBox jComboBox12LoanProduct;
    private javax.swing.JComboBox jComboBox13MaritalStatus;
    private javax.swing.JComboBox jComboBox14AgeGroup;
    private javax.swing.JComboBox jComboBox15EducationLevel;
    private javax.swing.JComboBox jComboBox16PersonalCharacter;
    private javax.swing.JComboBox jComboBox17PreferedContactChannel;
    private javax.swing.JComboBox jComboBox1IncomeLevel;
    private javax.swing.JComboBox jComboBox21AmountTakenCategory;
    private javax.swing.JComboBox jComboBox22EmploymentCategory;
    private javax.swing.JComboBox jComboBox2OccupationCategory;
    private javax.swing.JComboBox jComboBox3Sex;
    private javax.swing.JComboBox jComboBox4PaymentSource;
    private javax.swing.JComboBox jComboBox5EconomicWelbeingLevel;
    private javax.swing.JComboBox jComboBox6NumberOfCollaterals;
    private javax.swing.JComboBox jComboBox7TenureType;
    private javax.swing.JComboBox jComboBox9PreviousHistory;
    private javax.swing.JLabel jLabel10LoanPurpose;
    private javax.swing.JLabel jLabel11MarketingChannel;
    private javax.swing.JLabel jLabel13MaritalStatus;
    private javax.swing.JLabel jLabel14AgeGroup;
    private javax.swing.JLabel jLabel15EducationLevel;
    private javax.swing.JLabel jLabel16PersonalCharacter;
    private javax.swing.JLabel jLabel17Email;
    private javax.swing.JLabel jLabel18PhoneNumber;
    private javax.swing.JLabel jLabel19PreferedContactChannel;
    private javax.swing.JLabel jLabel1IncomeLevel;
    private javax.swing.JLabel jLabel20ClientLoyalty;
    private javax.swing.JLabel jLabel21AmountTakenCategory;
    private javax.swing.JLabel jLabel22EmploymentCategory;
    private javax.swing.JLabel jLabel23LoanProduct;
    private javax.swing.JLabel jLabel2OccupationCategory;
    private javax.swing.JLabel jLabel3Sex;
    private javax.swing.JLabel jLabel4PaymentSource;
    private javax.swing.JLabel jLabel6NumberOfCollaterals;
    private javax.swing.JLabel jLabel7TenureType;
    private javax.swing.JLabel jLabel9PreviousHistory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15PhoneNumber;
    private javax.swing.JTextField jTextField16Email;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {

    }

    @Override
    public void mousePressed(MouseEvent e) {
      
    }

    @Override
    public void mouseReleased(MouseEvent e) {
     
    }

    @Override
    public void mouseEntered(MouseEvent e) {
     
    }

    @Override
    public void mouseExited(MouseEvent e) {
     
    }

    @Override
    public void updateText(String text) {
  
    }

    @Override
    public void actionPerformed(ActionEvent e) {
 
    }

    @Override
    public void keyTyped(KeyEvent e) {
 
    }

    @Override
    public void keyPressed(KeyEvent e) {

    }

    @Override
    public void keyReleased(KeyEvent e) {
    
    }

    
}

