/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package googo.pmms.project2.frames;

import googo.pmms.project2.accountsHelper.Formartter;
import googo.pmms.project2.accountsHelper.fileInputOutPutStreams;
import googo.pmms.project2.databases.DatabaseQuaries;
import googo.pmms.project2.databases.loanDatabaseQuaries;
import googo.pmms.project2.frameHelper.IUpdateText;
import googo.pmms.project2.frameHelper.ListDataModel;
import googo.pmms.project2.frameHelper.MyTableModel;
import googo.pmms.project2.loanHelper.MaxmumAmountBorrowedFormulas;
import googo.pmms.project2.reportsHelper.OtherLoanReports;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author STAT SOLUTIONS
 */
public class CollateralSecurity extends javax.swing.JFrame implements MouseListener, IUpdateText, ActionListener{
    String activeAccountNumber="";
    fileInputOutPutStreams fios= new fileInputOutPutStreams();
    ArrayList<ArrayList<String>> data5;
    JOptionPane p;
    MyTableModel model;
    JFrame fi, f, fa, fb, fc;
    String staffid;
    Date date;
    SimpleDateFormat df;
List amortDetails;
 DatabaseQuaries dbq= new DatabaseQuaries();
 MaxmumAmountBorrowedFormulas maxValue= new MaxmumAmountBorrowedFormulas();
 loanDatabaseQuaries loan=new loanDatabaseQuaries();
    String userId, accountNumbergggggg,securitygggggggggg;
    
    
    OtherLoanReports otherLoans=new  OtherLoanReports();

     Formartter fmt= new Formartter();


    public CollateralSecurity(String userId) {
        
         
          
        initComponents();
 this.userId=userId;

        Image img = new ImageIcon(System.getProperty("user.dir")+"/"+"ICON_LOGO.jpg").getImage();
      this.setIconImage(img);
       this.setTitle("ADD NEW ITEM"); 
//        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jComboBox48 = new javax.swing.JComboBox();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jComboBox49 = new javax.swing.JComboBox();
        jComboBox50 = new javax.swing.JComboBox();
        jComboBox51 = new javax.swing.JComboBox();
        jComboBox52 = new javax.swing.JComboBox();
        jComboBox53 = new javax.swing.JComboBox();
        jComboBox54 = new javax.swing.JComboBox();
        jComboBox55 = new javax.swing.JComboBox();
        jLabel46 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1013, 547));
        setResizable(false);
        setSize(new java.awt.Dimension(2147483647, 2147483647));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 153), new java.awt.Color(0, 204, 153)));
        jPanel1.setLayout(null);

        jPanel7.setBackground(java.awt.SystemColor.activeCaption);
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(null);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel40.setText("Security Type2");
        jLabel40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel40);
        jLabel40.setBounds(0, 70, 140, 30);
        jLabel40.setVisible(false);

        jLabel45.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel45.setText("Description");
        jLabel45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel45);
        jLabel45.setBounds(360, 70, 90, 30);
        jLabel45.setVisible(false);

        jTextField22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField22);
        jTextField22.setBounds(460, 270, 550, 30);
        jTextField22.setVisible(false);
        jTextField22.setText("");

        jButton13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton13.setText("Cancel");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13);
        jButton13.setBounds(470, 360, 150, 40);

        jComboBox48.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox48.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vehicle", "Vehicles", "Commercial Vehicles", "Marketable Securities", "Shares", "MontlyIncome", "Government Bond", "Treasury Bills", "Inventory", "Business Assets", "Chattels", "Bank Instruments", "Post Dated Cheque", "Other Collaterals", "Guarantors", "Guarantor1", "Guarantor2", "Guarantor3", "Savings", "Land", "Titled Land", "Kibanja Land", "Real Estate", "Commercial Building", "Plant and Equipment" }));
        jComboBox48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox48ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox48);
        jComboBox48.setBounds(150, 70, 200, 30);
        jComboBox48.setVisible(false);

        jButton86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/add.png"))); // NOI18N
        jButton86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton86ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton86);
        jButton86.setBounds(10, 0, 20, 30);
        jButton86.setVisible(false);

        jButton87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/add.png"))); // NOI18N
        jButton87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton87ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton87);
        jButton87.setBounds(10, 0, 20, 30);
        jButton87.setVisible(true);

        jButton90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/add.png"))); // NOI18N
        jButton90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton90ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton90);
        jButton90.setBounds(10, 0, 20, 30);
        jButton90.setVisible(false);

        jButton91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/add.png"))); // NOI18N
        jButton91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton91ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton91);
        jButton91.setBounds(10, 0, 20, 30);
        jButton91.setVisible(false);

        jButton92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/add.png"))); // NOI18N
        jButton92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton92ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton92);
        jButton92.setBounds(10, 0, 20, 30);
        jButton92.setVisible(false);

        jButton93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/add.png"))); // NOI18N
        jButton93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton93ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton93);
        jButton93.setBounds(10, 0, 20, 30);
        jButton93.setVisible(false);

        jButton94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/add.png"))); // NOI18N
        jButton94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton94ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton94);
        jButton94.setBounds(10, 0, 20, 30);
        jButton94.setVisible(false);

        jButton95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/add.png"))); // NOI18N
        jButton95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton95ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton95);
        jButton95.setBounds(10, 0, 20, 30);
        jButton95.setVisible(false);

        jButton14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton14.setText("Submit");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton14);
        jButton14.setBounds(320, 360, 150, 40);

        jLabel48.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel48.setText("Security Type3");
        jLabel48.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel48);
        jLabel48.setBounds(0, 110, 140, 30);
        jLabel48.setVisible(false);

        jLabel49.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel49.setText("Security Type4");
        jLabel49.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel49);
        jLabel49.setBounds(0, 150, 140, 30);
        jLabel49.setVisible(false);

        jLabel50.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel50.setText("Security Type5");
        jLabel50.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel50);
        jLabel50.setBounds(0, 190, 140, 30);
        jLabel50.setVisible(false);

        jLabel51.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel51.setText("Security Type6");
        jLabel51.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel51);
        jLabel51.setBounds(0, 230, 140, 30);
        jLabel51.setVisible(false);

        jLabel52.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel52.setText("Security Type7");
        jLabel52.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel52);
        jLabel52.setBounds(0, 270, 140, 30);
        jLabel52.setVisible(false);

        jLabel55.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel55.setText("Security Type8");
        jLabel55.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel55);
        jLabel55.setBounds(0, 310, 140, 30);
        jLabel55.setVisible(false);

        jLabel57.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel57.setText("Security Type1");
        jLabel57.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel57);
        jLabel57.setBounds(0, 30, 140, 30);
        jLabel57.setVisible(false);

        jComboBox49.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox49.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guarantors", "Guarantor1", "Guarantor2", "Guarantor3", "Savings", "Land", "Titled Land", "Kibanja Land", "Real Estate", "Commercial Building", "Plant and Equipment", "Vehicle", "Vehicles", "Commercial Vehicles", "Marketable Securities", "Shares", "MontlyIncome", "Government Bond", "Treasury Bills", "Inventory", "Business Assets", "Chattels", "Bank Instruments", "Post Dated Cheque", "Other Collaterals" }));
        jComboBox49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox49ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox49);
        jComboBox49.setBounds(150, 110, 200, 30);
        jComboBox49.setVisible(false);

        jComboBox50.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox50.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Post Dated Cheque", "Other Collaterals", "Guarantors", "Guarantor1", "Guarantor2", "Guarantor3", "Savings", "Land", "Titled Land", "Kibanja Land", "Real Estate", "Commercial Building", "Plant and Equipment", "Vehicle", "Vehicles", "Commercial Vehicles", "Marketable Securities", "Shares", "MontlyIncome", "Government Bond", "Treasury Bills", "Inventory", "Business Assets", "Chattels", "Bank Instruments" }));
        jComboBox50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox50ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox50);
        jComboBox50.setBounds(150, 150, 200, 30);
        jComboBox50.setVisible(false);

        jComboBox51.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox51.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Government Bond", "Treasury Bills", "Inventory", "Business Assets", "Chattels", "Bank Instruments", "Post Dated Cheque", "Other Collaterals", "Guarantors", "Guarantor1", "Guarantor2", "Guarantor3", "Savings", "Land", "Titled Land", "Kibanja Land", "Real Estate", "Commercial Building", "Plant and Equipment", "Vehicle", "Vehicles", "Commercial Vehicles", "Marketable Securities", "Shares", "MontlyIncome" }));
        jComboBox51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox51ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox51);
        jComboBox51.setBounds(150, 190, 200, 30);
        jComboBox51.setVisible(false);

        jComboBox52.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox52.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chattels", "Bank Instruments", "Post Dated Cheque", "Other Collaterals", "Guarantors", "Guarantor1", "Guarantor2", "Guarantor3", "Savings", "Land", "Titled Land", "Kibanja Land", "Real Estate", "Commercial Building", "Plant and Equipment", "Vehicle", "Vehicles", "Commercial Vehicles", "Marketable Securities", "Shares", "MontlyIncome", "Government Bond", "Treasury Bills", "Inventory", "Business Assets" }));
        jComboBox52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox52ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox52);
        jComboBox52.setBounds(150, 230, 200, 30);
        jComboBox52.setVisible(false);

        jComboBox53.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox53.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Savings", "Land", "Titled Land", "Kibanja Land", "Real Estate", "Commercial Building", "Plant and Equipment", "Vehicle", "Vehicles", "Commercial Vehicles", "Marketable Securities", "Shares", "MontlyIncome", "Government Bond", "Treasury Bills", "Inventory", "Business Assets", "Chattels", "Bank Instruments", "Post Dated Cheque", "Other Collaterals", "Guarantors", "Guarantor1", "Guarantor2", "Guarantor3" }));
        jComboBox53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox53ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox53);
        jComboBox53.setBounds(150, 270, 200, 30);
        jComboBox53.setVisible(false);

        jComboBox54.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox54.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Shares", "MontlyIncome", "Government Bond", "Treasury Bills", "Inventory", "Business Assets", "Savings", "Land", "Titled Land", "Kibanja Land", "Real Estate", "Commercial Building", "Plant and Equipment", "Vehicle", "Vehicles", "Commercial Vehicles", "Marketable Securities" }));
        jComboBox54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox54ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox54);
        jComboBox54.setBounds(150, 310, 200, 30);
        jComboBox54.setVisible(false);

        jComboBox55.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox55.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Land", "Titled Land", "Kibanja Land", "Real Estate", "Commercial Building", "Plant and Equipment", "Vehicle", "Vehicles", "Commercial Vehicles", "Marketable Securities", "Government Bond", "Treasury Bills", "Inventory", "Business Assets", "Chattels", "Bank Instruments", "Post Dated Cheque", "Other Collaterals", "Guarantors", "Guarantor1", "Guarantor2", "Guarantor3", "Savings", "Shares", "MontlyIncome" }));
        jComboBox55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox55ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox55);
        jComboBox55.setBounds(150, 30, 200, 30);
        jComboBox55.setVisible(false);

        jLabel46.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel46.setText("Description");
        jLabel46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel46);
        jLabel46.setBounds(360, 110, 90, 30);
        jLabel46.setVisible(false);

        jLabel53.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel53.setText("Description");
        jLabel53.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel53);
        jLabel53.setBounds(360, 150, 90, 30);
        jLabel53.setVisible(false);

        jLabel56.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel56.setText("Description");
        jLabel56.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel56);
        jLabel56.setBounds(360, 190, 90, 30);
        jLabel56.setVisible(false);

        jLabel58.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel58.setText("Description");
        jLabel58.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel58);
        jLabel58.setBounds(360, 230, 90, 30);
        jLabel58.setVisible(false);

        jLabel59.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel59.setText("Description");
        jLabel59.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel59);
        jLabel59.setBounds(360, 270, 90, 30);
        jLabel59.setVisible(false);

        jLabel60.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel60.setText("Description");
        jLabel60.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel60);
        jLabel60.setBounds(360, 310, 90, 30);
        jLabel60.setVisible(false);

        jLabel62.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel62.setText("Description");
        jLabel62.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel62);
        jLabel62.setBounds(360, 30, 90, 30);
        jLabel62.setVisible(false);

        jTextField23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField23);
        jTextField23.setBounds(460, 110, 550, 30);
        jTextField23.setVisible(false);
        jTextField23.setText("");

        jTextField24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField24);
        jTextField24.setBounds(460, 150, 550, 30);
        jTextField24.setVisible(false);
        jTextField24.setText("");

        jTextField25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField25);
        jTextField25.setBounds(460, 190, 550, 30);
        jTextField25.setVisible(false);
        jTextField25.setText("");

        jTextField26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField26);
        jTextField26.setBounds(460, 230, 550, 30);
        jTextField26.setVisible(false);
        jTextField26.setText("");

        jTextField27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField27);
        jTextField27.setBounds(460, 310, 550, 30);
        jTextField27.setVisible(false);
        jTextField27.setText("");

        jTextField28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField28);
        jTextField28.setBounds(460, 70, 550, 30);
        jTextField28.setVisible(false);
        jTextField28.setText("");

        jTextField29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField29);
        jTextField29.setBounds(460, 30, 550, 30);
        jTextField29.setVisible(false);
        jTextField29.setText("");

        jButton15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton15.setText("UploadSecuirty");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton15);
        jButton15.setBounds(620, 360, 150, 40);
        jButton15.setVisible(false);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 80, 990, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 550);

        jButton51.setBackground(new java.awt.Color(0, 51, 51));
        jButton51.setText("jButton5");
        getContentPane().add(jButton51);
        jButton51.setBounds(1800, 360, 73, 23);

        jButton50.setBackground(java.awt.SystemColor.controlLtHighlight);
        jButton50.setText("jButton5");
        getContentPane().add(jButton50);
        jButton50.setBounds(1790, 330, 73, 23);

        jButton49.setBackground(new java.awt.Color(255, 204, 204));
        jButton49.setText("jButton5");
        getContentPane().add(jButton49);
        jButton49.setBounds(1870, 320, 73, 23);

        jButton31.setBackground(new java.awt.Color(255, 204, 153));
        jButton31.setText("Blue");
        getContentPane().add(jButton31);
        jButton31.setBounds(1810, 310, 53, 23);

        jButton38.setBackground(new java.awt.Color(204, 204, 0));
        jButton38.setText("Blue");
        getContentPane().add(jButton38);
        jButton38.setBounds(1810, 290, 53, 23);

        jButton32.setBackground(new java.awt.Color(0, 153, 153));
        jButton32.setText("Blue");
        getContentPane().add(jButton32);
        jButton32.setBounds(1870, 290, 53, 23);

        jButton47.setBackground(new java.awt.Color(204, 255, 204));
        jButton47.setText("Blue");
        getContentPane().add(jButton47);
        jButton47.setBounds(1930, 290, 53, 23);

        jButton29.setBackground(new java.awt.Color(0, 204, 204));
        jButton29.setText("Blue");
        getContentPane().add(jButton29);
        jButton29.setBounds(1920, 270, 53, 23);

        jButton37.setBackground(new java.awt.Color(204, 153, 255));
        jButton37.setText("Blue");
        getContentPane().add(jButton37);
        jButton37.setBounds(1870, 270, 53, 23);

        jButton33.setBackground(new java.awt.Color(152, 198, 94));
        jButton33.setText("Blue");
        getContentPane().add(jButton33);
        jButton33.setBounds(1810, 270, 53, 23);

        jButton35.setBackground(new java.awt.Color(255, 204, 204));
        jButton35.setText("Blue");
        getContentPane().add(jButton35);
        jButton35.setBounds(1810, 250, 53, 23);

        jButton45.setBackground(new java.awt.Color(255, 255, 204));
        jButton45.setText("Blue");
        getContentPane().add(jButton45);
        jButton45.setBounds(1870, 250, 53, 23);

        jButton42.setBackground(new java.awt.Color(0, 204, 102));
        jButton42.setText("Blue");
        getContentPane().add(jButton42);
        jButton42.setBounds(1920, 230, 53, 23);

        jButton43.setBackground(new java.awt.Color(204, 204, 204));
        jButton43.setText("Blue");
        getContentPane().add(jButton43);
        jButton43.setBounds(1870, 230, 53, 23);

        jButton30.setBackground(new java.awt.Color(0, 153, 255));
        jButton30.setText("Blue");
        getContentPane().add(jButton30);
        jButton30.setBounds(1810, 230, 53, 23);

        jButton36.setBackground(java.awt.SystemColor.activeCaption);
        jButton36.setText("Blue");
        getContentPane().add(jButton36);
        jButton36.setBounds(1810, 210, 53, 23);

        jButton44.setBackground(new java.awt.Color(204, 165, 165));
        jButton44.setText("Blue");
        getContentPane().add(jButton44);
        jButton44.setBounds(1870, 210, 53, 23);

        jButton39.setBackground(new java.awt.Color(204, 204, 255));
        jButton39.setText("Blue");
        getContentPane().add(jButton39);
        jButton39.setBounds(1920, 210, 53, 23);

        jButton41.setBackground(java.awt.SystemColor.activeCaption);
        jButton41.setText("Blue");
        getContentPane().add(jButton41);
        jButton41.setBounds(1920, 190, 53, 23);

        jButton46.setBackground(java.awt.SystemColor.activeCaption);
        jButton46.setText("Blue");
        getContentPane().add(jButton46);
        jButton46.setBounds(1870, 190, 53, 23);

        jButton40.setBackground(java.awt.SystemColor.activeCaption);
        jButton40.setText("Blue");
        getContentPane().add(jButton40);
        jButton40.setBounds(1810, 190, 53, 23);

        jButton48.setBackground(new java.awt.Color(201, 222, 223));
        jButton48.setText("Blue");
        getContentPane().add(jButton48);
        jButton48.setBounds(1870, 170, 53, 23);

        jButton52.setBackground(new java.awt.Color(0, 51, 51));
        jButton52.setText("jButton5");
        getContentPane().add(jButton52);
        jButton52.setBounds(1800, 360, 73, 23);

        jButton53.setBackground(java.awt.SystemColor.controlLtHighlight);
        jButton53.setText("jButton5");
        getContentPane().add(jButton53);
        jButton53.setBounds(1790, 330, 73, 23);

        jButton54.setBackground(new java.awt.Color(255, 204, 204));
        jButton54.setText("jButton5");
        getContentPane().add(jButton54);
        jButton54.setBounds(1870, 320, 73, 23);

        jButton34.setBackground(new java.awt.Color(255, 204, 153));
        jButton34.setText("Blue");
        getContentPane().add(jButton34);
        jButton34.setBounds(1810, 310, 53, 23);

        jButton55.setBackground(new java.awt.Color(204, 204, 0));
        jButton55.setText("Blue");
        getContentPane().add(jButton55);
        jButton55.setBounds(1810, 290, 53, 23);

        jButton56.setBackground(new java.awt.Color(0, 153, 153));
        jButton56.setText("Blue");
        getContentPane().add(jButton56);
        jButton56.setBounds(1870, 290, 53, 23);

        jButton57.setBackground(new java.awt.Color(204, 255, 204));
        jButton57.setText("Blue");
        getContentPane().add(jButton57);
        jButton57.setBounds(1930, 290, 53, 23);

        jButton58.setBackground(new java.awt.Color(0, 204, 204));
        jButton58.setText("Blue");
        getContentPane().add(jButton58);
        jButton58.setBounds(1920, 270, 53, 23);

        jButton59.setBackground(new java.awt.Color(204, 153, 255));
        jButton59.setText("Blue");
        getContentPane().add(jButton59);
        jButton59.setBounds(1870, 270, 53, 23);

        jButton60.setBackground(new java.awt.Color(152, 198, 94));
        jButton60.setText("Blue");
        getContentPane().add(jButton60);
        jButton60.setBounds(1810, 270, 53, 23);

        jButton61.setBackground(new java.awt.Color(255, 204, 204));
        jButton61.setText("Blue");
        getContentPane().add(jButton61);
        jButton61.setBounds(1810, 250, 53, 23);

        jButton62.setBackground(new java.awt.Color(255, 255, 204));
        jButton62.setText("Blue");
        getContentPane().add(jButton62);
        jButton62.setBounds(1870, 250, 53, 23);

        jButton63.setBackground(new java.awt.Color(0, 204, 102));
        jButton63.setText("Blue");
        getContentPane().add(jButton63);
        jButton63.setBounds(1920, 230, 53, 23);

        jButton64.setBackground(new java.awt.Color(204, 204, 204));
        jButton64.setText("Blue");
        getContentPane().add(jButton64);
        jButton64.setBounds(1870, 230, 53, 23);

        jButton65.setBackground(new java.awt.Color(0, 153, 255));
        jButton65.setText("Blue");
        getContentPane().add(jButton65);
        jButton65.setBounds(1810, 230, 53, 23);

        jButton66.setBackground(java.awt.SystemColor.activeCaption);
        jButton66.setText("Blue");
        getContentPane().add(jButton66);
        jButton66.setBounds(1810, 210, 53, 23);

        jButton67.setBackground(new java.awt.Color(204, 165, 165));
        jButton67.setText("Blue");
        getContentPane().add(jButton67);
        jButton67.setBounds(1870, 210, 53, 23);

        jButton68.setBackground(new java.awt.Color(204, 204, 255));
        jButton68.setText("Blue");
        getContentPane().add(jButton68);
        jButton68.setBounds(1920, 210, 53, 23);

        jButton69.setBackground(java.awt.SystemColor.activeCaption);
        jButton69.setText("Blue");
        getContentPane().add(jButton69);
        jButton69.setBounds(1920, 190, 53, 23);

        jButton70.setBackground(java.awt.SystemColor.activeCaption);
        jButton70.setText("Blue");
        getContentPane().add(jButton70);
        jButton70.setBounds(1870, 190, 53, 23);

        jButton71.setBackground(java.awt.SystemColor.activeCaption);
        jButton71.setText("Blue");
        getContentPane().add(jButton71);
        jButton71.setBounds(1810, 190, 53, 23);

        jButton72.setBackground(new java.awt.Color(201, 222, 223));
        jButton72.setText("Blue");
        getContentPane().add(jButton72);
        jButton72.setBounds(1870, 170, 53, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        activeAccountNumber=fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+this.userId+".txt"));
//JOptionPane.showMessageDialog(this, activeAccountNumber);
  fios.stringFileWriter(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+this.userId+".txt"), "Not Yet Select");
  fios.stringFileWriter(fios.createFileName("loanApplication", "amortValues", "creditLedger"+userId+".txt"), activeAccountNumber);
//  JOptionPane.showMessageDialog(this, activeAccountNumber);

    }//GEN-LAST:event_formWindowOpened

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        Object[] optionsSGS1 = {"Yes",  "No"};
        int nSGS1 = JOptionPane.showOptionDialog(this,  "Are you sure you want to cance creation of Security??",
            "SAVE PLEASE", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,optionsSGS1, optionsSGS1[0]);
        if(nSGS1==JOptionPane.YES_OPTION){
           
            this.dispose();
        }
        else if (nSGS1==JOptionPane.NO_OPTION){ this.setVisible(true);}
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jComboBox48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox48ActionPerformed
        if(!jComboBox48.getSelectedItem().toString().equals("")){
            fios.stringFileWriter(fios.createFileName("persistence", "collateralSecurity", "collateralType1.txt"), jComboBox48.getSelectedItem().toString());

        }
    }//GEN-LAST:event_jComboBox48ActionPerformed

    private void jButton86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton86ActionPerformed

//        String accountnumbDocS1= fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+this.userId+".txt"));
       
        jLabel49.setVisible(true);
        jComboBox50.setVisible(true);
        jLabel53.setVisible(true);
        jTextField24.setVisible(true);
        jButton86.setVisible(false);
        jButton92.setVisible(true);

        fios.intFileWriterReplace(fios.createFileName("loanApplication", "collateralSDocumentation", "numberOfSecurity"+activeAccountNumber+userId+".txt"),"4");

        //        Integer xh = 0;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity1.txt"), xh.toString());
        //        Integer xj = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity2.txt"), xj.toString());
        //
        //        jLabel32.setVisible(true);
        //        jComboBox48.setVisible(true);
        //        jLabel37.setVisible(true);
        //        jTextField19.setVisible(true);
        //        jButton86.setVisible(false);
        //        jButton87.setVisible(true);
        //        Integer x = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "AllowUseOfCollateralSecurity1.txt"), x.toString());
        //
        //        fios.stringFileWriterAppend(fios.createFileName("loanApplication", "amortValues", "amortizeMe.txt"), ",");
        //        Integer xiy=1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "numberOfCallaterals.txt"), xiy.toString());
    }//GEN-LAST:event_jButton86ActionPerformed

    private void jButton87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton87ActionPerformed
//        String accountnumbDocS1= fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+userId+".txt"));
        jLabel57.setVisible(true);
        jComboBox55.setVisible(true);
        jLabel62.setVisible(true);
        jTextField29.setVisible(true);
        jButton87.setVisible(false);
        jButton91.setVisible(true);
        fios.intFileWriterReplace(fios.createFileName("loanApplication", "collateralSDocumentation", "numberOfSecurity"+activeAccountNumber+userId+".txt"),"1");
    }//GEN-LAST:event_jButton87ActionPerformed

    private void jButton90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton90ActionPerformed
//        String accountnumbDocS1= fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+this.userId+".txt"));
        jLabel55.setVisible(true);
        jComboBox54.setVisible(true);
        jLabel60.setVisible(true);
        jTextField27.setVisible(true);
        jButton90.setVisible(false);
        fios.intFileWriterReplace(fios.createFileName("loanApplication", "collateralSDocumentation", "numberOfSecurity"+activeAccountNumber+userId+".txt"),"8");

        //        Integer xh = 0;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity3.txt"), xh.toString());
        //        Integer xj = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity4.txt"), xj.toString());
        //        Integer x = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "AllowUseOfCollateralSecurity3.txt"), x.toString());
        //
        //        jLabel28.setVisible(true);
        //        jComboBox43.setVisible(true);
        //        jLabel33.setVisible(true);
        //        jTextField15.setVisible(true);
        //        jButton90.setVisible(false);
        //        jButton91.setVisible(true);
        //        Integer xiy=3;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "numberOfCallaterals.txt"), xiy.toString());
    }//GEN-LAST:event_jButton90ActionPerformed

    private void jButton91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton91ActionPerformed
//        String accountnumbDocS1= fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+this.userId+".txt"));
        jLabel40.setVisible(true);
        jComboBox48.setVisible(true);
        jLabel45.setVisible(true);
        jTextField28.setVisible(true);
        jButton91.setVisible(false);
        jButton94.setVisible(true);
        fios.intFileWriterReplace(fios.createFileName("loanApplication", "collateralSDocumentation", "numberOfSecurity"+activeAccountNumber+userId+".txt"),"2");

        //        Integer xh = 0;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity4.txt"), xh.toString());
        //        Integer xj = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity5.txt"), xj.toString());
        //
        //        Integer x = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "AllowUseOfCollateralSecurity4.txt"), x.toString());
        //
        //        jLabel29.setVisible(true);
        //        jComboBox44.setVisible(true);
        //        jLabel34.setVisible(true);
        //        jTextField16.setVisible(true);
        //        jButton91.setVisible(false);
        //        jButton92.setVisible(true);
        //        Integer xiy=4;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "numberOfCallaterals.txt"), xiy.toString());
    }//GEN-LAST:event_jButton91ActionPerformed

    private void jButton92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton92ActionPerformed
//        String accountnumbDocS1= fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+this.userId+".txt"));
        jLabel50.setVisible(true);
        jComboBox51.setVisible(true);
        jLabel56.setVisible(true);
        jTextField25.setVisible(true);
        jButton92.setVisible(false);
        jButton93.setVisible(true);
        fios.intFileWriterReplace(fios.createFileName("loanApplication", "collateralSDocumentation", "numberOfSecurity"+activeAccountNumber+userId+".txt"),"5");
        //        Integer xh = 0;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity5.txt"), xh.toString());
        //        Integer xj = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity6.txt"), xj.toString());
        //
        //        Integer x = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "AllowUseOfCollateralSecurity5.txt"), x.toString());
        //        jLabel30.setVisible(true);
        //        jComboBox45.setVisible(true);
        //        jLabel35.setVisible(true);
        //        jTextField17.setVisible(true);
        //        jButton92.setVisible(false);
        //        jButton93.setVisible(true);
        //        Integer xiy=5;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "numberOfCallaterals.txt"), xiy.toString());
    }//GEN-LAST:event_jButton92ActionPerformed

    private void jButton93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton93ActionPerformed
//        String accountnumbDocS1= fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+this.userId+".txt"));
        jLabel51.setVisible(true);
        jComboBox52.setVisible(true);
        jLabel58.setVisible(true);
        jTextField26.setVisible(true);
        jButton93.setVisible(false);
        jButton95.setVisible(true);
        fios.intFileWriterReplace(fios.createFileName("loanApplication", "collateralSDocumentation", "numberOfSecurity"+activeAccountNumber+userId+".txt"),"6");
        //        Integer xh = 0;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity6.txt"), xh.toString());
        //        Integer xj = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity7.txt"), xj.toString());
        //
        //        Integer x = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "AllowUseOfCollateralSecurity6.txt"), x.toString());
        //        jLabel42.setVisible(true);
        //        jComboBox46.setVisible(true);
        //        jLabel43.setVisible(true);
        //        jTextField35.setVisible(true);
        //        jButton93.setVisible(false);
        //        jButton95.setVisible(true);
        //        Integer xiy=6;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "numberOfCallaterals.txt"), xiy.toString());
    }//GEN-LAST:event_jButton93ActionPerformed

    private void jButton94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton94ActionPerformed
//        String accountnumbDocS1= fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+this.userId+".txt"));
        jLabel48.setVisible(true);
        jComboBox49.setVisible(true);
        jLabel46.setVisible(true);
        jTextField23.setVisible(true);
        jButton94.setVisible(false);
        jButton86.setVisible(true);
        fios.intFileWriterReplace(fios.createFileName("loanApplication", "collateralSDocumentation", "numberOfSecurity"+activeAccountNumber+userId+".txt"),"3");
        //        jLabel31.setVisible(true);
        //        jComboBox47.setVisible(true);
        //        jLabel36.setVisible(true);
        //        jTextField18.setVisible(true);
        //        jButton94.setVisible(false);
        //        jCheckBox1.setText("You Can Add Up To A Max Of 8 Securities");
        //        jCheckBox1.setBackground(Color.red);
        //        Integer xiy=8;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "numberOfCallaterals.txt"), xiy.toString());
    }//GEN-LAST:event_jButton94ActionPerformed

    private void jButton95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton95ActionPerformed
//        String accountnumbDocS1= fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+this.userId+".txt"));
        jLabel52.setVisible(true);
        jComboBox53.setVisible(true);
        jLabel59.setVisible(true);
        jTextField22.setVisible(true);
        jButton95.setVisible(false);
        jButton90.setVisible(true);
        fios.intFileWriterReplace(fios.createFileName("loanApplication", "collateralSDocumentation", "numberOfSecurity"+activeAccountNumber+userId+".txt"),"7");

        //        Integer xh = 0;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity7.txt"), xh.toString());
        //        Integer xj = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "buttonCollateralSecurity8.txt"), xj.toString());
        //
        //        Integer x = 1;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "AllowUseOfCollateralSecurity7.txt"), x.toString());
        //        jLabel54.setVisible(true);
        //        jComboBox49.setVisible(true);
        //        jLabel53.setVisible(true);
        //        jTextField37.setVisible(true);
        //        jButton95.setVisible(false);
        //        jButton94.setVisible(true);
        //        Integer xiy=7;
        //        fios.intFileWriterReplace(fios.createFileName("persistence", "collateralSecurity", "numberOfCallaterals.txt"), xiy.toString());
    }//GEN-LAST:event_jButton95ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

//        String accountnumbDocS1= fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccountvv"+userId+".txt"));
        JOptionPane.showConfirmDialog(this, fios.intFileReader( fios.createFileName("loanApplication", "collateralSDocumentation", "numberOfSecurity"+activeAccountNumber+userId+".txt"))+"");
        switch(fios.intFileReader( fios.createFileName("loanApplication", "collateralSDocumentation", "numberOfSecurity"+activeAccountNumber+userId+".txt"))){
            case 1:
            if(jTextField29.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Please first put details of surity one!!");
                return;
            }else if(!Pattern.compile("^;$").matcher("jTextField29.getText()").find()){

                String security="1"+";"+jComboBox55.getSelectedItem().toString()+";"+jTextField29.getText();
                jButton14.setEnabled(false);
//                jLabel3.setEnabled(true);
                jButton95.setEnabled(false);
                jButton86.setEnabled(false);
                jButton87.setEnabled(false);
                jButton90.setEnabled(false);
                jButton91.setEnabled(false);
                jButton92.setEnabled(false);
                jButton93.setEnabled(false);
                jButton94.setEnabled(false);
                
                
                fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "theSecurityForLoan"+activeAccountNumber+userId+".txt"), security);
                  
                fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "collatoeralSet"+activeAccountNumber+userId+".txt"), "Yes");  
//                JOptionPane.showMessageDialog(this, activeAccountNumber);
//JOptionPane.showMessageDialog(this, fios.stringFileReader(fios.createFileName("loanApplication", "collateralSDocumentation", "theSecurityForLoan"+activeAccountNumber+userId+".txt")));

//                SwingWorker<Void,Void>submittedSecurity=new SwingWorker(){
//                    @Override
//                    protected Object doInBackground() throws Exception {
//                        loan. processSecurity(activeAccountNumber,security);
//                        return null;
//                    }
//                };
//                submittedSecurity.execute();

            }else{

                JOptionPane.showMessageDialog(this, "The character ; is not allowed in the field");
                return;
            }

            break;
            case 2:
            String security2="2"+";"+jComboBox55.getSelectedItem().toString()+";"+jTextField29.getText()+";"+jComboBox48.getSelectedItem().toString()+";"+jTextField28.getText();
            jButton14.setEnabled(false);
//            jLabel3.setEnabled(true);
            jButton95.setEnabled(false);
            jButton86.setEnabled(false);
            jButton87.setEnabled(false);
            jButton90.setEnabled(false);
            jButton91.setEnabled(false);
            jButton92.setEnabled(false);
            jButton93.setEnabled(false);
            jButton94.setEnabled(false);
//            SwingWorker<Void,Void>submittedSecurity1=new SwingWorker(){
//                @Override
//                protected Object doInBackground() throws Exception {
//                    loan. processSecurity(activeAccountNumber,security2);
//                    return null;
//                }
//            };
//            submittedSecurity1.execute();
            
               fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "theSecurityForLoan"+activeAccountNumber+userId+".txt"), security2);
                  fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "collatoeralSet"+activeAccountNumber+userId+".txt"), "Yes");   
            break;
            case 3:
            String security3="3"+";"+jComboBox55.getSelectedItem().toString()+";"+jTextField29.getText()+";"+jComboBox48.getSelectedItem().toString()+";"+jTextField28.getText()+";"+jComboBox49.getSelectedItem().toString()+";"+jTextField23.getText();
            jButton14.setEnabled(false);
//            jLabel3.setEnabled(true);
//            SwingWorker<Void,Void>submittedSecurity2=new SwingWorker(){
//                @Override
//                protected Object doInBackground() throws Exception {
//                    loan. processSecurity(activeAccountNumber,security3);
//                    return null;
//                }
//            };
//            submittedSecurity2.execute();
            
               fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "theSecurityForLoan"+activeAccountNumber+userId+".txt"), security3);
                     fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "collatoeralSet"+activeAccountNumber+userId+".txt"), "Yes");   
            break;
            case 4:
            String security4="4"+";"+jComboBox55.getSelectedItem().toString()+";"+jTextField29.getText()+";"+jComboBox48.getSelectedItem().toString()+";"+jTextField28.getText()+";"+jComboBox49.getSelectedItem().toString()+";"+jTextField23.getText()+";"+jComboBox50.getSelectedItem().toString()+";"+jTextField24.getText();
            jButton14.setEnabled(false);
//            jLabel3.setEnabled(true);
            jButton95.setEnabled(false);
            jButton86.setEnabled(false);
            jButton87.setEnabled(false);
            jButton90.setEnabled(false);
            jButton91.setEnabled(false);
            jButton92.setEnabled(false);
            jButton93.setEnabled(false);
            jButton94.setEnabled(false);
               fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "theSecurityForLoan"+activeAccountNumber+userId+".txt"), security4);
                     fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "collatoeralSet"+activeAccountNumber+userId+".txt"), "Yes");   
//            SwingWorker<Void,Void>submittedSecurity4=new SwingWorker(){
//                @Override
//                protected Object doInBackground() throws Exception {
//                    loan. processSecurity(activeAccountNumber,security4);
//                    return null;
//                }
//            };
//            submittedSecurity4.execute();
            break;
            case 5:
            String security5="5"+";"+jComboBox55.getSelectedItem().toString()+";"+jTextField29.getText()+";"+jComboBox48.getSelectedItem().toString()+";"+jTextField28.getText()+";"+jComboBox49.getSelectedItem().toString()+";"+jTextField23.getText()+";"+jComboBox50.getSelectedItem().toString()+";"+jTextField24.getText()+";"+jComboBox51.getSelectedItem().toString()+";"+jTextField25.getText();
            jButton14.setEnabled(false);
//            jLabel3.setEnabled(true);
            jButton95.setEnabled(false);
            jButton86.setEnabled(false);
            jButton87.setEnabled(false);
            jButton90.setEnabled(false);
            jButton91.setEnabled(false);
            jButton92.setEnabled(false);
            jButton93.setEnabled(false);
            jButton94.setEnabled(false);
            
            
               fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "theSecurityForLoan"+activeAccountNumber+userId+".txt"), security5);
                     fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "collatoeralSet"+activeAccountNumber+userId+".txt"), "Yes");   
//            SwingWorker<Void,Void>submittedSecurity5=new SwingWorker(){
//                @Override
//                protected Object doInBackground() throws Exception {
//                    loan. processSecurity(activeAccountNumber,security5);
//                    return null;
//                }
//            };
//            submittedSecurity5.execute();
            break;
            case 6:
            String security6="6"+";"+jComboBox55.getSelectedItem().toString()+";"+jTextField29.getText()+";"+jComboBox48.getSelectedItem().toString()+";"+jTextField28.getText()+";"+jComboBox49.getSelectedItem().toString()+";"+jTextField23.getText()+";"+jComboBox50.getSelectedItem().toString()+";"+jTextField24.getText()+";"+jComboBox51.getSelectedItem().toString()+";"+jTextField25.getText()+";"+jComboBox52.getSelectedItem().toString()+";"+jTextField26.getText();
            jButton14.setEnabled(false);
//            jLabel3.setEnabled(true);
            jButton95.setEnabled(false);
            jButton86.setEnabled(false);
            jButton87.setEnabled(false);
            jButton90.setEnabled(false);
            jButton91.setEnabled(false);
            jButton92.setEnabled(false);
            jButton93.setEnabled(false);
            jButton94.setEnabled(false);
//            SwingWorker<Void,Void>submittedSecurity6=new SwingWorker(){
//                @Override
//                protected Object doInBackground() throws Exception {
//                    loan. processSecurity(activeAccountNumber,security6);
//                    return null;
//                }
//            };
//            submittedSecurity6.execute();
            
              fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "theSecurityForLoan"+activeAccountNumber+userId+".txt"), security6);
              
                    fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "collatoeralSet"+activeAccountNumber+userId+".txt"), "Yes");   
            break;
            case 7:
            String security7="7"+";"+jComboBox55.getSelectedItem().toString()+";"+jTextField29.getText()+";"+jComboBox48.getSelectedItem().toString()+";"+jTextField28.getText()+";"+jComboBox49.getSelectedItem().toString()+";"+jTextField23.getText()+";"+jComboBox50.getSelectedItem().toString()+";"+jTextField24.getText()+";"+jComboBox51.getSelectedItem().toString()+";"+jTextField25.getText()+";"+jComboBox52.getSelectedItem().toString()+";"+jTextField26.getText()+";"+jComboBox53.getSelectedItem().toString()+";"+jTextField22.getText();
            jButton14.setEnabled(false);
//            jLabel3.setEnabled(true);
            jButton95.setEnabled(false);
            jButton86.setEnabled(false);
            jButton87.setEnabled(false);
            jButton90.setEnabled(false);
            jButton91.setEnabled(false);
            jButton92.setEnabled(false);
            jButton93.setEnabled(false);
            jButton94.setEnabled(false);
//            SwingWorker<Void,Void>submittedSecurity7=new SwingWorker(){
//                @Override
//                protected Object doInBackground() throws Exception {
//                    loan. processSecurity(activeAccountNumber,security7);
//                    return null;
//                }
//            };
//            submittedSecurity7.execute();
            
            
             fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "theSecurityForLoan"+activeAccountNumber+userId+".txt"), security7);
            break;
            case 8:
            String security8="8"+";"+jComboBox55.getSelectedItem().toString()+";"+jTextField29.getText()+";"+jComboBox48.getSelectedItem().toString()+";"+jTextField28.getText()+";"+jComboBox49.getSelectedItem().toString()+";"+jTextField23.getText()+";"+jComboBox50.getSelectedItem().toString()+";"+jTextField24.getText()+";"+jComboBox51.getSelectedItem().toString()+";"+jTextField25.getText()+";"+jComboBox52.getSelectedItem().toString()+";"+jTextField26.getText()+";"+jComboBox53.getSelectedItem().toString()+";"+jTextField22.getText()+";"+jComboBox54.getSelectedItem().toString()+";"+jTextField27.getText();
            jButton14.setEnabled(false);
//            jLabel3.setEnabled(true);
            jButton95.setEnabled(false);
            jButton86.setEnabled(false);
            jButton87.setEnabled(false);
            jButton90.setEnabled(false);
            jButton91.setEnabled(false);
            jButton92.setEnabled(false);
            jButton93.setEnabled(false);
            jButton94.setEnabled(false);
            
     fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "theSecurityForLoan"+activeAccountNumber+userId+".txt"), security8);         
       fios.stringFileWriter(fios.createFileName("loanApplication", "collateralSDocumentation", "collatoeralSet"+activeAccountNumber+userId+".txt"), "Yes");        
//            SwingWorker<Void,Void>submittedSecurity8=new SwingWorker(){
//                @Override
//                protected Object doInBackground() throws Exception {
//                    loan. processSecurity(activeAccountNumber,security8);
//                    return null;
//                }
//            };
//            submittedSecurity8.execute();
            break;
        }
  JOptionPane.showMessageDialog(this, "Loan security was successfully created!!!!");
  
      this.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jComboBox49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox49ActionPerformed

    private void jComboBox50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox50ActionPerformed

    private void jComboBox51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox51ActionPerformed

    private void jComboBox52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox52ActionPerformed

    private void jComboBox53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox53ActionPerformed

    private void jComboBox54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox54ActionPerformed

    private void jComboBox55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox55ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        boolean updaloadsuccessful=false;

        JFileChooser fileChooser = new JFileChooser();

        int returnValue = fileChooser.showOpenDialog(null);

        FileInputStream fis=null;File selectedFile=null;XSSFWorkbook workbook=null;XSSFSheet spreadSheet=null;XSSFRow row=null;
        int t=0;
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            selectedFile = fileChooser.getSelectedFile();

            try {
                //               String     filename = selectedFile.getAbsolutePath();

                fis=new FileInputStream(selectedFile);

                workbook=new XSSFWorkbook(fis);

                spreadSheet=workbook.getSheetAt(0);

            } catch (FileNotFoundException ex) {

                JOptionPane.showMessageDialog(this, ex.toString());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.toString());
            }

            Iterator <Row>   rowIterator=spreadSheet.iterator();

            while(rowIterator.hasNext()){

                row=(XSSFRow)rowIterator.next();

                Iterator <Cell>  cellIterator=row.iterator();

                jButton14.setEnabled(false);

                while(cellIterator.hasNext()){

                    if(t==0){

                        accountNumbergggggg=   cellIterator.next().toString();
                    }

                    if(t==1){
                        securitygggggggggg=cellIterator.next().toString();
                    }

                    t++;
                }
                SwingWorker<Void,Void>submittedSecurity=new SwingWorker(){
                    @Override
                    protected Object doInBackground() throws Exception {

//                        updloadSecuirty(accountNumbergggggg,securitygggggggggg);

                        return null;
                    }};
                    submittedSecurity.execute();
                }

                updaloadsuccessful=true;
            }

    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
////        public static String u=AddBatch.this.userId;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddBatch().setVisible(true);
//            }
//        });
//    }
   private void sortTable(JTable table,JTextField textField){

   
    
TableRowSorter<TableModel> rowSorter  = new TableRowSorter<>(table.getModel());
                     
                      table.setRowSorter(rowSorter);
                     textField.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = textField.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = textField.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JComboBox jComboBox48;
    private javax.swing.JComboBox jComboBox49;
    private javax.swing.JComboBox jComboBox50;
    private javax.swing.JComboBox jComboBox51;
    private javax.swing.JComboBox jComboBox52;
    private javax.swing.JComboBox jComboBox53;
    private javax.swing.JComboBox jComboBox54;
    private javax.swing.JComboBox jComboBox55;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
      
    }

    @Override
    public void mousePressed(MouseEvent e) {
      
    }

    @Override
    public void mouseReleased(MouseEvent e) {
      
    }

    @Override
    public void mouseEntered(MouseEvent e) {
      
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }

    @Override
    public void updateText(String text) {
      
    }

    @Override
    public void actionPerformed(ActionEvent e) {
       
    }
}

