/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package googo.pmms.project2.frames;

//import googo.generalUse.project1.email.GmailService;

import googo.pmms.project2.accountsHelper.fileInputOutPutStreams;
import googo.pmms.project2.databases.AccountNumberCreationDataBase;
import googo.pmms.project2.databases.DatabaseQuaries;
import googo.pmms.project2.databases.loanDatabaseQuaries;
import googo.pmms.project2.email.SendMail;
import googo.pmms.project2.email.emailManager;
import googo.pmms.project2.frameHelper.IUpdateText;
import googo.pmms.project2.frameHelper.MyComboBoxModel;
import googo.pmms.project2.frameHelper.MyTableModel;
import googo.pmms.project2.smallFrames.EmailAttachmentAll;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Stanchart
 */
public class email extends javax.swing.JFrame implements MouseListener , IUpdateText {
 String userId;
    Component cc;
    fileInputOutPutStreams fios= new fileInputOutPutStreams();
DatabaseQuaries dbq =new DatabaseQuaries();
SendMail send= new SendMail();
emailManager emailMe =new emailManager();
    JOptionPane p;
    MyTableModel model;
    JFrame fi, f, fa, fb, fc;
    Date date; String filename;
    SimpleDateFormat df;
    MyComboBoxModel modelcombo;
    ArrayList<String> data4, column1;
     int master;
     List accountDetails, customerDetails;
     AccountNumberCreationDataBase ancdb=new AccountNumberCreationDataBase();
      loanDatabaseQuaries loanDb=new loanDatabaseQuaries();
       SimpleDateFormat sdf =new SimpleDateFormat("dd/MM/yyyy");
          Graphics g;
         private BufferedImage image;
         String accountNumber="05502000110";
   List<List> reportDetails= new ArrayList();
   List attachements; List amortDetails;
    /**
     * Creates new form email
     * @param userId
     */
    public email( String userId) {
        this.userId=userId;
        initComponents();
        cc=this;
         jTable2.setAlignmentX(LEFT_ALIGNMENT);
jTable2.setAlignmentY(CENTER_ALIGNMENT);
jTable2.setAutoscrolls(true);
jTable2.setShowHorizontalLines(true);
jTable2.setShowGrid(true);
jTable2.setRowHeight(35);
jTable2.setGridColor(Color.gray);
        switch(dbq.title(userId)){
            case "Loans Officer":
                break;
            case "Accountant":
                break;
            case "Supervisor":
                break;
           case "Manager":
                break;
         case "Cashier":
                break;
               case "System Admin":
       
                break;
        }
//       jTree1.addMouseListener( this);
        java.awt.Image img = new ImageIcon(System.getProperty("user.dir")+"/"+"ICON_LOGO.jpg").getImage();
      this.setIconImage(img);
      this.setTitle("EMAIL MODULE-"+dbq.title(userId)); 
     jTable2.addMouseListener(this);
    }
//public void setUserID(String userid){
//this.userId=userid;
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jComboBox68 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jComboBox15 = new javax.swing.JComboBox();
        jComboBox71 = new javax.swing.JComboBox();
        jComboBox72 = new javax.swing.JComboBox();
        jComboBox73 = new javax.swing.JComboBox();
        jComboBox92 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton11 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jCheckBox1.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox1.setForeground(java.awt.SystemColor.control);
        jCheckBox1.setText("Use");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(850, 170, 60, 30);

        jCheckBox2.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox2.setForeground(java.awt.SystemColor.control);
        jCheckBox2.setText("Use");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2);
        jCheckBox2.setBounds(850, 320, 60, 30);

        jCheckBox3.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox3.setForeground(java.awt.SystemColor.control);
        jCheckBox3.setText("Use");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox3);
        jCheckBox3.setBounds(850, 270, 60, 30);

        jCheckBox4.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox4.setForeground(java.awt.SystemColor.control);
        jCheckBox4.setText("Use");
        jCheckBox4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox4);
        jCheckBox4.setBounds(850, 220, 60, 30);

        jComboBox68.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox68.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Customer/Member", "BoardMembers/Staff" }));
        jComboBox68.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox68ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox68);
        jComboBox68.setBounds(500, 20, 230, 30);

        jComboBox11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TrialBalance", "BalanceSheet", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement", "CashLedger" }));
        jComboBox11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jComboBox11);
        jComboBox11.setBounds(40, 120, 250, 30);

        jCheckBox11.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox11.setForeground(java.awt.SystemColor.control);
        jCheckBox11.setText("Use");
        jCheckBox11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox11);
        jCheckBox11.setBounds(850, 70, 60, 30);

        jCheckBox12.setBackground(java.awt.SystemColor.activeCaption);
        jCheckBox12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox12.setForeground(java.awt.SystemColor.control);
        jCheckBox12.setText("Use");
        jCheckBox12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox12);
        jCheckBox12.setBounds(850, 120, 60, 30);

        jComboBox15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BalanceSheet", "TrialBalance", "CashLedger", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement" }));
        jComboBox15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jComboBox15);
        jComboBox15.setBounds(40, 170, 250, 30);

        jComboBox71.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox71.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TrialBalance", "BalanceSheet", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement", "CashLedger" }));
        jComboBox71.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jComboBox71);
        jComboBox71.setBounds(40, 320, 250, 30);

        jComboBox72.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox72.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TrialBalance", "BalanceSheet", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement", "CashLedger" }));
        jComboBox72.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jComboBox72);
        jComboBox72.setBounds(40, 270, 250, 30);

        jComboBox73.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox73.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TrialBalance", "BalanceSheet", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement", "CashLedger" }));
        jComboBox73.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jComboBox73);
        jComboBox73.setBounds(40, 220, 250, 30);

        jComboBox92.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox92.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CashLedger", "TrialBalance", "BalanceSheet", "ProfitAndLoss", "Ledger Statement", "Savings Statement", "Loan Statement", "Shares Statement", "Daily Individual ROI", "Aging Statement" }));
        jComboBox92.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jComboBox92);
        jComboBox92.setBounds(40, 70, 250, 30);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setForeground(java.awt.SystemColor.control);
        jLabel23.setText("Select Recepient Group");
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel23);
        jLabel23.setBounds(270, 20, 230, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Start Date");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel10);
        jLabel10.setBounds(290, 320, 130, 30);

        jTextField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(jTextField4);
        jTextField4.setBounds(420, 320, 130, 30);

        jButton12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12);
        jButton12.setBounds(550, 320, 20, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("End Date");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel15);
        jLabel15.setBounds(570, 320, 130, 30);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(700, 320, 130, 30);

        jButton10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(830, 320, 20, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Subject:");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel14);
        jLabel14.setBounds(110, 400, 100, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Body");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel13);
        jLabel13.setBounds(110, 450, 100, 30);

        jTextField5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel3.add(jTextField5);
        jTextField5.setBounds(210, 400, 670, 30);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setToolTipText("Please type colons (:) at the end of statement to create a new paragraph");
        jScrollPane1.setViewportView(jTextArea5);
        jTextArea5.setWrapStyleWord(true);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(210, 450, 670, 90);

        jButton11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton11.setText("Email Reports");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(390, 590, 150, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Start Date");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel11);
        jLabel11.setBounds(290, 270, 130, 30);

        jTextField7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(jTextField7);
        jTextField7.setBounds(420, 270, 130, 30);

        jButton13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);
        jButton13.setBounds(550, 270, 20, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("End Date");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel17);
        jLabel17.setBounds(570, 270, 130, 30);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(700, 270, 130, 30);

        jButton14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14);
        jButton14.setBounds(830, 270, 20, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Start Date");
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel18);
        jLabel18.setBounds(290, 220, 130, 30);

        jTextField9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(jTextField9);
        jTextField9.setBounds(420, 220, 130, 30);

        jButton15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15);
        jButton15.setBounds(550, 220, 20, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("End Date");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel19);
        jLabel19.setBounds(570, 220, 130, 30);
        jPanel3.add(jTextField10);
        jTextField10.setBounds(700, 220, 130, 30);

        jButton16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16);
        jButton16.setBounds(830, 220, 20, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Start Date");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel20);
        jLabel20.setBounds(290, 170, 130, 30);

        jTextField11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(jTextField11);
        jTextField11.setBounds(420, 170, 130, 30);

        jButton17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17);
        jButton17.setBounds(550, 170, 20, 30);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("End Date");
        jLabel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel25);
        jLabel25.setBounds(570, 170, 130, 30);
        jPanel3.add(jTextField12);
        jTextField12.setBounds(700, 170, 130, 30);

        jButton18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton18);
        jButton18.setBounds(830, 170, 20, 30);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Start Date");
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel26);
        jLabel26.setBounds(290, 120, 130, 30);

        jTextField13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(jTextField13);
        jTextField13.setBounds(420, 120, 130, 30);

        jButton19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton19);
        jButton19.setBounds(550, 120, 20, 30);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("End Date");
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel27);
        jLabel27.setBounds(570, 120, 130, 30);
        jPanel3.add(jTextField14);
        jTextField14.setBounds(700, 120, 130, 30);

        jButton20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton20);
        jButton20.setBounds(830, 120, 20, 30);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Start Date");
        jLabel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel28);
        jLabel28.setBounds(290, 70, 130, 30);

        jTextField15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(jTextField15);
        jTextField15.setBounds(420, 70, 130, 30);

        jButton21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton21);
        jButton21.setBounds(550, 70, 20, 30);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("End Date");
        jLabel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel29);
        jLabel29.setBounds(570, 70, 130, 30);
        jPanel3.add(jTextField16);
        jTextField16.setBounds(700, 70, 130, 30);

        jButton22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton22);
        jButton22.setBounds(830, 70, 20, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(5, 38, 1180, 700);
        jPanel3.setVisible(false);

        jPanel7.setBackground(java.awt.SystemColor.activeCaption);
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(null);

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTable1);

        jPanel7.add(jScrollPane6);
        jScrollPane6.setBounds(12, 12, 1152, 640);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(180, 770, 40, 50);
        jPanel7.setVisible(false);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("BODY:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 200, 80, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Add Attachment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(860, 130, 150, 30);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(50);
        jTextArea4.setToolTipText("Please type colons (:) at the end of statement to create a new paragraph");
        jTextArea4.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextArea4);
        jTextArea4.setLineWrap(true);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(90, 200, 710, 240);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("TO:");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 40, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("SEND TO:");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel8);
        jLabel8.setBounds(860, 40, 80, 30);

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "All Customers/Members", "BoardMembers/Staff", "Customer/Member" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(940, 40, 190, 30);

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Send Email");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(390, 450, 140, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("SUBJECT:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 160, 80, 30);

        jTextField6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField6);
        jTextField6.setBounds(90, 160, 710, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);
        jTextArea1.setLineWrap(true);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(90, 40, 770, 120);

        jCheckBox5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox5.setText("Add Attachment from Computer");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(860, 100, 270, 30);

        jCheckBox6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox6.setText("Add Attachement From Reports");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(860, 70, 270, 30);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jTable2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(9, 7, 350, 220);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Search Here:");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel1);
        jLabel1.setBounds(10, 230, 110, 40);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel4.add(jTextField1);
        jTextField1.setBounds(120, 230, 240, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(800, 160, 370, 280);
        jPanel4.setVisible(false);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(5, 38, 1175, 700);
        jPanel1.setVisible(false);

        jPanel6.setBackground(java.awt.SystemColor.activeCaption);
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(820, 0, 150, 40);

        jButton5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5.setText("Send General Mail");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(10, 0, 150, 40);

        jButton6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton6.setText("Send System Data");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(180, 0, 170, 40);

        jButton7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7);
        jButton7.setBounds(980, 0, 150, 40);

        jButton8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton8.setText("Mail Home");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);
        jButton8.setBounds(660, 0, 150, 40);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 0, 1180, 40);

        jButton9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton9.setText("Refresh");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(1020, 0, 150, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1220, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

//        JOptionPane.showMessageDialog(this, reportDetails.get(0).get(2));
//          for(Object the:reportDetails){
//       
//       JOptionPane.showMessageDialog(this, the);
//       
//       }
        if(jTextArea1.getText().equalsIgnoreCase("")){
JOptionPane.showMessageDialog(this, "Please first input the Recepient's email addresses separated by semi colons!!!!!!!!");
return;
}else{


  if(jTextField6.getText().equalsIgnoreCase("")){
JOptionPane.showMessageDialog(this, "Please first input the Subject!!!!!!!!");
return;
}else{


   if(jTextArea4.getText().equalsIgnoreCase("")){
JOptionPane.showMessageDialog(this, "Please first input the email content!!!!!!!!");
return;
}else{
// SwingWorker<Void,Void> processAtPerforming = new SwingWorker(){
//        @Override
//        protected Object doInBackground() throws Exception { 
       if(jCheckBox6.isSelected()){//Add attachements from reports
       
       
       switch(jComboBox2.getSelectedItem().toString()){

           case "All Customers/Members":
       List theSendingDetails=new ArrayList();
    theSendingDetails.add(jTextArea1.getText());
     theSendingDetails.add(jTextField6.getText());  
     
     String[] message=jTextArea4.getText().split("[:]");
     int t=0;String actualMessage="";
     
     while(t<message.length){
         
     actualMessage=actualMessage.concat("<p style=\"color:Green;\">"+message[t]+"</p>");
         
         t++;
     }
     
String out2= "<h3>"+actualMessage+"</h3>".concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:#cc0066\">"+"Sent Directly from <u>Pink Apple</u>, a computer accounting and loan management software for Microfinance Institutions,Money Lenders,SACCOs,Credit Unions etc, a product of <u><b>Stat Solutions Research Network Ltd</b></u>. For more details call or whatsapp <u>Bazirake Augustine Googo</u> at 0782231039 or email him at: augbazi@gmail.com"+"</p>");
  
 
    theSendingDetails.add(out2);
  
    
   emailMe. processRecepientsEmailManyWithReports(reportDetails,theSendingDetails,email.this );
    
    JOptionPane.showMessageDialog(cc, "Sent Successfully");
  
          break;
            case "BoardMembers/Staff":
       List theSendingDetailsA=new ArrayList();
    theSendingDetailsA.add(jTextArea1.getText());
     theSendingDetailsA.add(jTextField6.getText());  
     
     String[] messageA=jTextArea4.getText().split("[:]");
     int tA=0;String actualMessageA="";
     
     while(tA<messageA.length){
     actualMessageA=actualMessageA.concat("<p style=\"color:Green;\">"+messageA[tA]+"</p>");
         
         tA++;
     }
String out= "<h3>"+actualMessageA+"</h3>".concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:#cc0066\">"+"Sent Directly from <u>Pink Apple</u>, a computer accounting and loan management software for Microfinance Institutions,Money Lenders,SACCOs,Credit Unions etc, a product of <u><b>Stat Solutions Research Network Ltd</b></u>. For more details call or whatsapp <u>Bazirake Augustine Googo</u> at 0782231039 or email him at: augbazi@gmail.com"+"</p>");
  
 
    theSendingDetailsA.add(out);
    
    
   emailMe. processRecepientsEmailManyWithReports(reportDetails,theSendingDetailsA,email.this );
    
    JOptionPane.showMessageDialog(cc, "Sent Successfully");
        break; 
                
       case "Customer/Member":
           
           String[] test=jTextArea1.getText().split("[;]");
           if(test.length==1){
       List theSendingDetailsA1=new ArrayList();
    theSendingDetailsA1.add(jTextArea1.getText());
     theSendingDetailsA1.add(jTextField6.getText());  
     
     String[] messageA1=jTextArea4.getText().split("[:]");
     int tA1=0;String actualMessageA1="";
     
     while(tA1<messageA1.length){
     actualMessageA1=actualMessageA1.concat("<p style=\"color:Green;\">"+messageA1[tA1]+"</p>");
         
         tA1++;
     }
    String out1= "<h3>"+actualMessageA1+"</h3>".concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:#cc0066\">"+"Sent Directly from <u>Pink Apple</u>, a computer accounting and loan management software for Microfinance Institutions,Money Lenders,SACCOs,Credit Unions etc, a product of <u><b>Stat Solutions Research Network Ltd</b></u>. For more details call or whatsapp <u>Bazirake Augustine Googo</u> at 0782231039 or email him at: augbazi@gmail.com"+"</p>");
  
 
    theSendingDetailsA1.add(out1);
    
    
   emailMe. processRecepientsEmailIndividualWithReports(reportDetails,theSendingDetailsA1,email.this );
    
    JOptionPane.showMessageDialog(cc, "Sent Successfully");
           }else{
         JOptionPane.showMessageDialog(cc, "You cannot send to more than one recepient");  
//           return;
           }
        break;           
                
                
       }
       
       }else{
       
        switch(jComboBox2.getSelectedItem().toString()){

           case "All Customers/Members":
       List theSendingDetails=new ArrayList();
    theSendingDetails.add(jTextArea1.getText());
     theSendingDetails.add(jTextField6.getText());  
     
     String[] message=jTextArea4.getText().split("[:]");
     int t=0;String actualMessage="";
     
     while(t<message.length){
     actualMessage=actualMessage.concat("<p style=\"color:Green;\">"+message[t]+"</p>");
         
         t++;
     }
     
String out2= "<h3>"+actualMessage+"</h3>".concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:#cc0066\">"+"Sent Directly from <u>Pink Apple</u>, a computer accounting and loan management software for Microfinance Institutions,Money Lenders,SACCOs,Credit Unions etc, a product of <u><b>Stat Solutions Research Network Ltd</b></u>. For more details call or whatsapp <u>Bazirake Augustine Googo</u> at 0782231039 or email him at: augbazi@gmail.com"+"</p>");
  
 
    theSendingDetails.add(out2);
    
    
   emailMe. processRecepientsEmailManyWithReports(attachements,theSendingDetails,email.this );
    
    JOptionPane.showMessageDialog(cc, "Sent Successfully");
  
          break;
            case "BoardMembers/Staff":
       List theSendingDetailsA=new ArrayList();
    theSendingDetailsA.add(jTextArea1.getText());
     theSendingDetailsA.add(jTextField6.getText());  
     
     String[] messageA=jTextArea4.getText().split("[:]");
     int tA=0;String actualMessageA="";
     
     while(tA<messageA.length){
     actualMessageA=actualMessageA.concat("<p style=\"color:Green;\">"+messageA[tA]+"</p>");
         
         tA++;
     }
String out= "<h3>"+actualMessageA+"</h3>".concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:#cc0066\">"+"Sent Directly from <u>Pink Apple</u>, a computer accounting and loan management software for Microfinance Institutions,Money Lenders,SACCOs,Credit Unions etc, a product of <u><b>Stat Solutions Research Network Ltd</b></u>. For more details call or whatsapp <u>Bazirake Augustine Googo</u> at 0782231039 or email him at: augbazi@gmail.com"+"</p>");
  
 
    theSendingDetailsA.add(out);
    
    
   emailMe. processRecepientsEmailManyWithReports(theSendingDetailsA,attachements,email.this );
    
    JOptionPane.showMessageDialog(cc, "Sent Successfully");
        break; 
                
       case "Customer/Member":
           
           String[] test=jTextArea1.getText().split("[;]");
           if(test.length==1){
       List theSendingDetailsA1=new ArrayList();
    theSendingDetailsA1.add(jTextArea1.getText());
     theSendingDetailsA1.add(jTextField6.getText());  
     
     String[] messageA1=jTextArea4.getText().split("[:]");
     int tA1=0;String actualMessageA1="";
     
     while(tA1<messageA1.length){
     actualMessageA1=actualMessageA1.concat("<p style=\"color:Green;\">"+messageA1[tA1]+"</p>");
         
         tA1++;
     }
    String out1= "<h3>"+actualMessageA1+"</h3>".concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:#cc0066\">"+"Sent Directly from <u>Pink Apple</u>, a computer accounting and loan management software for Microfinance Institutions,Money Lenders,SACCOs,Credit Unions etc, a product of <u><b>Stat Solutions Research Network Ltd</b></u>. For more details call or whatsapp <u>Bazirake Augustine Googo</u> at 0782231039 or email him at: augbazi@gmail.com"+"</p>");
  
 
    theSendingDetailsA1.add(out1);
    
    
   emailMe. processRecepientsEmailIndividual(theSendingDetailsA1,attachements,email.this );
    
    JOptionPane.showMessageDialog(cc, "Sent Successfully");
           }else{
         JOptionPane.showMessageDialog(cc, "You cannot send to more than one recepient");  
//           return;
           }
        break;           
                
                
       }
       
          
       
       }
       
//       return null;
//        }
//        };
//        processAtPerforming.execute(); 
        
        
        
       email f = new email (userId);
        f.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        f.setSize(screen.getSize());
        f.pack();
        this.dispose();
         
}
   
}
    
}
    
    }//GEN-LAST:event_jButton2ActionPerformed
//private void updateRoleCombo(JComboBox box){
//        int v=0; ArrayList <String> userRoles=new ArrayList();
//       
//        String [] roles=fios.stringFileReader(fios.createFileName("resources", "roles", "role1.txt")).split("[;]");     
//        
//        while(v<=roles.length-1){if(v==roles.length-1){userRoles.add(roles[v].replace(";", ""));}else{ userRoles.add(roles[v]);} v++; }
//       
//        modelcombo = new MyComboBoxModel(userRoles);
//       
//        box.setModel(modelcombo); 
//}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      attachements=new ArrayList();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int i=1;
     while(i<=5){
     
     JOptionPane.showMessageDialog(this, "SYSTEM LOG OUT ERROR!!!!!!!!!");
     }
    }//GEN-LAST:event_formWindowClosing

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      jPanel1.setVisible(true);
      jPanel3.setVisible(false);
      jPanel7.setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

                 Object[] optionsSGS = {"Continue",  "Cancel"};
    int nSGS = JOptionPane.showOptionDialog(this,  "Work may not be saved!!!\n"+"Do you want to  continue ?",
    "SAVE PLEASE", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,optionsSGS, optionsSGS[0]);
    if(nSGS==JOptionPane.YES_OPTION){
     switch(dbq.title(userId)){
            case "Loans Officer":
         LoanManagmentWindow ffx = new LoanManagmentWindow (userId);
        ffx.setVisible(true);
        Dimension screensx = Toolkit.getDefaultToolkit().getScreenSize();
        ffx.setSize(screensx.getSize());
        ffx.pack();
        this.dispose();
                break;
            case "Accountant":
          PostingEntryWindow fh = new  PostingEntryWindow(userId,amortDetails);
        fh.setVisible(true);
        Dimension screenh = Toolkit.getDefaultToolkit().getScreenSize();
        fh.setSize(screenh.getSize());
        fh.pack();
        this.dispose();
                
                
                break;
            case "Supervisor":
        PostingEntryWindow f = new  PostingEntryWindow(userId,amortDetails);
        f.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        f.setSize(screen.getSize());
        f.pack();
        this.dispose();
                break;
        
        
           case "Manager":
            LoanApprovals fx = new LoanApprovals (userId);
        fx.setVisible(true);
        Dimension screenx = Toolkit.getDefaultToolkit().getScreenSize();
        fx.setSize(screenx.getSize());
        fx.pack();
        this.dispose();
                break;
         case "Cashier":
       PostingEntryWindow fg = new  PostingEntryWindow(userId,amortDetails);
        fg.setVisible(true);
        Dimension screeng = Toolkit.getDefaultToolkit().getScreenSize();
        fg.setSize(screeng.getSize());
        fg.pack();
        this.dispose();
                break;
               case "System Admin":
            CreateNewStaff fxs1 = new CreateNewStaff (userId);
        fxs1.setVisible(true);
        Dimension screenxs1 = Toolkit.getDefaultToolkit().getScreenSize();
        fxs1.setSize(screenxs1.getSize());
        fxs1.pack();
        this.dispose();
                break;
        }
    }
    else if (nSGS==JOptionPane.NO_OPTION){ this.setVisible(true);}
               


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         jPanel1.setVisible(false);
      jPanel3.setVisible(true);
      jPanel7.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       jPanel1.setVisible(false);
      jPanel3.setVisible(false);
      jPanel7.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

                email fxs1 = new email (userId);
        fxs1.setVisible(true);
        Dimension screenxs1 = Toolkit.getDefaultToolkit().getScreenSize();
        fxs1.setSize(screenxs1.getSize());
        fxs1.pack();
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"102");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      
        
        if(reportDetails.isEmpty()){
          
          
         JOptionPane.showMessageDialog(this, "Please first select the type of report");
         
      return;
      }else{
          
    if(fios.intFileReader(fios.createFileName("emailDetails", "sendMail", "emailIDPW.txt"))==2){
    
    JOptionPane.showMessageDialog(this, "Please first set the email password");
    return;
    }else{
    
     if(fios.intFileReader(fios.createFileName("emailDetails", "sendMail", "emailID.txt"))==2){
    
    JOptionPane.showMessageDialog(this, "Please first set the email ID!!!!");
    return;
    }else{
    
         if(jTextField5.getText().equalsIgnoreCase("")){
          JOptionPane.showMessageDialog(this, "Please first input the subject message!!!");
         return;
         }else{
          
           if(jTextArea5.getText().equalsIgnoreCase("")){
          JOptionPane.showMessageDialog(this, "Please first input the Body message!!!");
         return;
         }else{
          
//               SwingWorker<Void,Void> processAtPerforming = new SwingWorker(){
//        @Override
//        protected Object doInBackground() throws Exception {   
               
               
      List thedays=new ArrayList();
      
      thedays.add(jTextField5.getText());
      
      String[] message=jTextArea5.getText().split("[:]");
      
     int t=0;
     
     String actualMessage="";
     
     while(t<message.length){
         
     actualMessage=actualMessage.concat("<p style=\"color:Green;\">"+message[t]+"</p>");
         
         t++;
     }

String out21= "<h3>"+actualMessage+"</h3>".concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:Green;\">"+" "+"</p>").concat("<p style=\"color:#cc0066\">"+"Sent Directly from <u>Pink Apple</u>, a computer accounting and loan management software for Microfinance Institutions,Money Lenders,SACCOs,Credit Unions etc, a product of <u><b>Stat Solutions Research Network Ltd</b></u>. For more details call or whatsapp <u>Bazirake Augustine Googo</u> at 0782231039 or email him at: augbazi@gmail.com"+"<i> We make sense out of scratch</i></p>");
  
    thedays.add(out21);

      
      thedays.add(fios.stringFileReader(fios.createFileName("emailDetails", "sendMail", "authenticatePW.txt")));
      
  
          
   if(emailMe.sendFinalEmailReports(reportDetails, thedays,jComboBox68.getSelectedItem().toString(),email.this)){
       
   JOptionPane.showMessageDialog(cc, "The email was sent successfully");
   
   }else{
     JOptionPane.showMessageDialog(cc, "The email sending failed!!");
   
   }   
           
//      return null;
//        }
//        };
//        processAtPerforming.execute();   
        
        } 
         } 
    
    }
    }
      
      }
      JOptionPane.showMessageDialog(cc, "Email sending was done successfully!!"); 
      email fxs1 = new email (userId);
        fxs1.setVisible(true);
        Dimension screenxs1 = Toolkit.getDefaultToolkit().getScreenSize();
        fxs1.setSize(screenxs1.getSize());
        fxs1.pack();
        this.dispose();  
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
            fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"101");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
           if(jTextField13.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");
       
       }else{
            if(jTextField14.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");
       
       }else{
        
        
        
           List de1=new ArrayList();
         de1.add(jComboBox11.getSelectedItem().toString());
        de1.add(jTextField13.getText());
        de1.add(jTextField14.getText());
       setTheEmailDetails(de1);
       }
       }
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
    
        if(jTextField15.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");
       
       }else{
            if(jTextField16.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");
       
       }else{
        
        
        
           List de1=new ArrayList();
         de1.add(jComboBox92.getSelectedItem().toString());
        de1.add(jTextField15.getText());
        de1.add(jTextField16.getText());
        setTheEmailDetails(de1);
       }
       }
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
      if(jTextField9.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");
       
       }else{
            if(jTextField10.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");
       
       }else{
        
        
        
           List de1=new ArrayList();
         de1.add(jComboBox73.getSelectedItem().toString());
        de1.add(jTextField9.getText());
        de1.add(jTextField10.getText());
        setTheEmailDetails(de1);
       }
       }
  
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
       if(jTextField7.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");
       
       }else{
            if(jTextField8.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");
       
       }else{
        
        
        
           List de1=new ArrayList();
         de1.add(jComboBox72.getSelectedItem().toString());
        de1.add(jTextField7.getText());
        de1.add(jTextField8.getText());
        setTheEmailDetails(de1);
       }
       }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
          if(jTextField4.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");
       
       }else{
            if(jTextField3.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");
       
       }else{
        
        
        
           List de1=new ArrayList();
         de1.add(jComboBox71.getSelectedItem().toString());
        de1.add(jTextField4.getText());
        de1.add(jTextField3.getText());
       setTheEmailDetails(de1);
       }
       }
        
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
           if(jTextField11.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the start date for the report range!!");
       
       }else{
            if(jTextField12.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(this, "Please first input the end date for the report range!!");
       
       }else{
        
        
        
           List de1=new ArrayList();
         de1.add(jComboBox15.getSelectedItem().toString());
        de1.add(jTextField11.getText());
        de1.add(jTextField12.getText());
        setTheEmailDetails(de1);
       }
       }
      
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

     
jTextArea1.setText("");
        
        if(jComboBox2.getSelectedItem().toString().equalsIgnoreCase("All Customers/Members")){
jPanel4.setVisible(false);
   List theEmails=     dbq.feelTextAreaWithCustomerEmails(email.this);
   
   
    for(Object finalE:theEmails){
    if(!finalE.toString().equalsIgnoreCase("")){
    jTextArea1.append(finalE.toString());
    jTextArea1.append(";");
    }
    
    }
        
        } else if(jComboBox2.getSelectedItem().toString().equalsIgnoreCase("BoardMembers/Staff")){
          jPanel4.setVisible(false);
   List theEmails=     dbq.feelTextAreaWithBoardStaffD(email.this);
   
   
    for(Object finalE:theEmails){
    if(!finalE.toString().equalsIgnoreCase("")){
    jTextArea1.append(finalE.toString());
    jTextArea1.append(";");
    }}
        
        }else if(jComboBox2.getSelectedItem().toString().equalsIgnoreCase("Customer/Member")){
        jPanel4.setVisible(true);
          dbq.fillMeWithAllAccountsCSpecial(jTable2);
          sortTable(jTable2,jTextField1);
        JOptionPane.showMessageDialog(this, "Please Select Customer/Member from the Table");
        
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Customer/Member
        
        if(jCheckBox6.isSelected()){
        
        if(jComboBox2.getSelectedItem().toString().equalsIgnoreCase("Customer/Member")){
            
            if(!fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "accountLedger2"+accountNumber+".txt")).equalsIgnoreCase("AccountSelected")){
            
            JOptionPane.showMessageDialog(this, "Please first select member's account Number");
            return;
            }else{
                
            fios.stringFileWriter(fios.createFileName("loanApplication", "amortValues", "accountLedger2"+accountNumber+".txt"), "NotAccountSelected");

            EmailAttachmentAll fo15 = new EmailAttachmentAll(userId,accountNumber,"Individual",(email)this);
            fo15.setVisible(true);
            Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
            fo15.setSize(screen.getSize());
            fo15.pack();
            
                
                
            }
        
        }else{
        
         EmailAttachmentAll fo15 = new EmailAttachmentAll(userId,accountNumber,"General",(email)this);
        fo15.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        fo15.setSize(screen.getSize());
        fo15.pack();
        
        
        }
        }else if(jCheckBox5.isSelected()){
        
         JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            
              List de1=new ArrayList();
                de1.add("Other External");
                de1.add("Miss1");
                de1.add(fileChooser.getSelectedFile().getAbsolutePath());
                setTheEmailDetails(de1);
            
           
        }
        }else{
        
        JOptionPane.showMessageDialog(this, "Please Specify the source of the attachment first!!!!!");
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
      if(jCheckBox6.isSelected()){
      
      jCheckBox5.setSelected(false);
      
      }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
         if(jCheckBox5.isSelected()){
      
      jCheckBox6.setSelected(false);
      
      }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jComboBox68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox68ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
     fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"103");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"108");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"104");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
          fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"109");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"105");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
   fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"110");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
       fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"106");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"111");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
       fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"107");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
       fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"112");  
      Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);  
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new email().setVisible(true);
//            }
//        });
//    }
    
public void setTheEmailDetails(List theDetails){

reportDetails.add(theDetails);

}
    
     private void sortTable(JTable table,JTextField textField){

   
    
TableRowSorter<TableModel> rowSorter  = new TableRowSorter<>(table.getModel());
                     
                      table.setRowSorter(rowSorter);
                     textField.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = textField.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = textField.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    

}
             
         
         
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox68;
    private javax.swing.JComboBox jComboBox71;
    private javax.swing.JComboBox jComboBox72;
    private javax.swing.JComboBox jComboBox73;
    private javax.swing.JComboBox jComboBox92;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables



    @Override
    public void mouseClicked(MouseEvent me) {
        
  if(me.getSource()==jTable2){
          
     int selectedRow =jTable2.getSelectedRow();
                    int selectedColumn =jTable2.getSelectedColumn();
		   if (selectedRow > -1&&selectedColumn>-1)
	   {
	
          Object cvalue1 = jTable2.getModel().getValueAt(jTable2.convertRowIndexToModel(selectedRow), 2); 
//           fios.stringFileWriter(fios.createFileName("loanApplication", "amortValues", "sweetieSusanLove.txt"), "suzanlove");
 jTextArea1.setText("");
          accountNumber = cvalue1.toString();
   
      fios.stringFileWriter(fios.createFileName("loanApplication", "amortValues", "accountLedger2"+accountNumber+".txt"), "AccountSelected");
   String email=dbq.feelTextAreaWithCustomerEmailsA(email.this,accountNumber);
   
   if(!email.isEmpty()){
    jTextArea1.append(email);
  
   }else{ 
   JOptionPane.showMessageDialog(this, "There is no email Address found. Please first set the customer's email address");
   }
    
     }
    
    }
     
    
    }

    @Override
    public void mousePressed(MouseEvent e) {
      
    }

    @Override
    public void mouseReleased(MouseEvent e) {
       
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }

    @Override
    public void updateText(String text) {
     switch( fios.intFileReader(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"))){ 
        case 101:jTextField4.setText(text);break;    
        case 102:jTextField3.setText(text);break; 
        case 103:jTextField7.setText(text);break;    
        case 104:jTextField9.setText(text);break; 
        case 105:jTextField11.setText(text);break;    
        case 106:jTextField13.setText(text);break; 
        case 107:jTextField15.setText(text);break;  
            
            case 108:jTextField8.setText(text);break;    
        case 109:jTextField10.setText(text);break; 
        case 110:jTextField12.setText(text);break;    
        case 111:jTextField14.setText(text);break; 
        case 112:jTextField16.setText(text);break;
        
     }
    }


    


}