/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package googo.pmms.project2.frames;

import googo.pmms.project2.loanHelper.Amortization;
import googo.pmms.project2.loanHelper.MaxmumAmountBorrowedFormulas;
import googo.pmms.project2.frameHelper.ObjectTableModel;
import googo.pmms.project2.databases.DatabaseQuaries;
import googo.pmms.project2.databases.loanDatabaseQuaries;
import googo.pmms.project2.accountsHelper.fileInputOutPutStreams;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author Stanchart
 */
public class loanApprovalsMaker extends javax.swing.JFrame implements MouseListener {
 loanDatabaseQuaries loan=new loanDatabaseQuaries();
   
     fileInputOutPutStreams fios= new fileInputOutPutStreams();
  
DecimalFormat df1 = new DecimalFormat("#.##");
DecimalFormat df2 = new DecimalFormat("#");
 DecimalFormat NumberFormat =new DecimalFormat("#,###.##");
     Calendar cal = Calendar.getInstance();
    int n,s;
ArrayList<Object> data4;
List amortDetails;
ArrayList<String>  column1, data,data1 ;

 ArrayList<ArrayList<Object>> data5;
   double loanAmount,loanTerm,interestRate, annualInterest=0.0,interest=0.0;
   Calendar startDate;
   ButtonGroup group1,group2,group3,group4;
   ObjectTableModel  model;

    JFrame fi, f,fa,fb,fc;
    Date date;
  SimpleDateFormat df;

 DatabaseQuaries dbq= new DatabaseQuaries();
 MaxmumAmountBorrowedFormulas maxValue= new MaxmumAmountBorrowedFormulas();
   String userId;
    public loanApprovalsMaker(String userId) {
        this.userId=userId;
        initComponents();
        java.awt.Image img = new ImageIcon(System.getProperty("user.dir")+"/"+"ICON_LOGO.jpg").getImage();
      this.setIconImage(img);
      this.setTitle("LOAN APPROVAL INPUTTER");
    
           jTree2.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
         jTree2.addMouseListener( this);
       
         
    }
public void setUserID(String userid){
this.userId=userid;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/tick.png"))); // NOI18N
        jButton1.setText("Documentation Approved");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(190, 320, 240, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/submit.png"))); // NOI18N
        jButton2.setText("Proceed To Loan Processing");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(190, 440, 240, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/loan Application.jpg"))); // NOI18N
        jButton3.setText("Loan Details Approved");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(190, 170, 240, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/submit.png"))); // NOI18N
        jButton4.setText("Submited For Approval");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(190, 140, 240, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/rejected.jpg"))); // NOI18N
        jButton5.setText("Loan Details  Rejected");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(190, 200, 240, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/EDIT.jpg"))); // NOI18N
        jButton6.setText("Edit Documentaion and Collateral");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(190, 380, 240, 30);
        jButton6.setEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 153, 153));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(430, 140, 370, 330);

        jTree2.setBackground(java.awt.SystemColor.activeCaption);
        jTree2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.SystemColor.activeCaption, null));
        jTree2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTree2.setForeground(new java.awt.Color(255, 255, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Navigation Guide");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Log Out");
        treeNode1.add(treeNode2);
        jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTree2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 40, 190, 580);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/EDIT IT.jpg"))); // NOI18N
        jButton8.setText("Edit Loan Details");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(190, 230, 240, 30);

        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(800, 140, 90, 30);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.controlLtHighlight);
        jLabel1.setText("l");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(190, 40, 700, 40);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/cancel.jpg"))); // NOI18N
        jButton9.setText("Documentation  Rejected");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(190, 350, 240, 30);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/tick.png"))); // NOI18N
        jButton10.setText("Collateral  Approved");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(190, 260, 240, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/cancel.jpg"))); // NOI18N
        jButton11.setText("Collateral  Rejected");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);
        jButton11.setBounds(190, 290, 240, 30);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/loan Application.jpg"))); // NOI18N
        jButton12.setText(" Loan Approval Status");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);
        jButton12.setBounds(190, 410, 240, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

           
        String statusOfLoanApprovalsAccount = fios.stringFileReader(fios.createFileName("loanApplication", "fromLoanApprovals", "statusOfLoanApprovalsAccountAp.txt")); 
        int statusOfLoanApprovals = fios.intFileReader(fios.createFileName("loanApplication", "fromLoanApprovals", "statusOfLoanApprovals"+statusOfLoanApprovalsAccount+".txt")); 
        switch(statusOfLoanApprovals){
            case 1:
 jButton4.setEnabled(true);
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false); 

jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"loan has been succefully submited for processing."+"\n\n"+"Please avail documentation and collateral evidance to the supervisor and notify them for approvals."+"\n\n"+"Thanks Boss");

                break;
        case 2:
    if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==1){
     jButton4.setEnabled(true);
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false); 
 jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"Loan Request resubmitted for Approval"+"\n\n"+"Thank Thank you");   
    }        
            
            
            if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==1){
jButton4.setEnabled(false); 
jButton3.setEnabled(true);
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false); 
jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"loan details have sofar been approved and we're still waiting for the documentation and collateral to also be approved."+"\n\n"+"Kindly be a little bit patient or otherwise contact your supervisor for action"+"\n\n"+"Thanks Boss");

            }else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==1){           
   jButton4.setEnabled(false); 
jButton3.setEnabled(true);
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(true); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);     
jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"loan details and collateral have sofar been approved and we're still waiting for the documentation  to also be approved."+"\n\n"+"Kindly be a little bit patient or otherwise contact your supervisor for action"+"\n\n"+"Thanks Boss");

            }else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==2){           
   jButton4.setEnabled(false); 
jButton3.setEnabled(true);
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(true); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);            
  jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"documentation and loan details have sofar been approved and we're still waiting for the collateral  to also be approved."+"\n\n"+"Kindly be a little bit patient or otherwise contact your supervisor for action"+"\n\n"+"Thanks Boss");
 
            }else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==2){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(true); 
jButton11.setEnabled(false); 
jButton1.setEnabled(true); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);            
    jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" documentation and collateral have sofar been approved  and we're still waiting for the  loan details to  be approved."+"\n\n"+"Kindly be a little bit patient or otherwise contact your supervisor for action"+"\n\n"+"Thanks Boss");
  
            }else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==2){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(true); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(true); 
jButton11.setEnabled(false); 
jButton1.setEnabled(true); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"loan details, documentation and collateral have all been been approved and we're still waiting for the whole loan to  be approved."+"\n\n"+"Kindly be a little bit patient or otherwise contact your supervisor for action"+"\n\n"+"Thanks Boss");
       
            
            
            }else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==1){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(true); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"collateral has  been been approved and we're still waiting for documentation and loan details to be approved."+"\n\n"+"Kindly be a little bit patient or otherwise contact your supervisor for action"+"\n\n"+"Thanks Boss");
       
            
            
            }
            else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==2){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(true); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"documentation has  been been approved and we're still waiting for collateral and loan details to be approved."+"\n\n"+"Kindly be a little bit patient or otherwise contact your supervisor for action"+"\n\n"+"Thanks Boss");
       
            
            
            }
       if (fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==1){
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(true);
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false); 
jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"loan details has sofar been rejected and we're still waiting for the documentation and collateral to also be approved."+"\n\n"+"But you can proceed and edit the laon details and resubmit to your supervisors for approval"+"\n\n"+"Thank you");

            }else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==1){           
   jButton4.setEnabled(false); 
jButton3.setEnabled(false);
jButton5.setEnabled(true);
jButton8.setEnabled(false); 
jButton10.setEnabled(true); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);     
jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"loan details has been rejected but  collateral was approved though documentation is still waiting  to also be approved."+"\n\n"+"Kindly be a little bit patient but meanwhile you can go ahead and edit the loan details and resubmit to your supervisors for approval"+"\n\n"+"Thank you");

            }else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==2){           
   jButton4.setEnabled(false); 
jButton3.setEnabled(false);
jButton5.setEnabled(true); 
jButton8.setEnabled(false); 
jButton10.setEnabled(true); 
jButton11.setEnabled(false); 
jButton1.setEnabled(true); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);            
  jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"documentation and collateral were approved though loan details was rejected."+"\n\n"+"Kindly edit the loan details and submit to supervisors for approval"+"\n\n"+"Thank you");
 
            }else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==1){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(true); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(true); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);            
    jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"loan details and collateral were both rejected and documentation  is pending approval."+"\n\n"+"Kindly go ahead and edit loan details and  collateral as you wait for documentation approval"+"\n\n"+"Thank you");
  
            }else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==2){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(true); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(true); 
jButton1.setEnabled(true); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"loan details and  collateral have both been rejected though documentation was approved."+"\n\n"+"Kindly go ahead and correct loan details and collateral and resubmit to  supervisors for approval"+"\n\n"+"Thank you");
       
            
            
            }else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==3){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(true); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(true); 
jButton1.setEnabled(false); 
jButton9.setEnabled(true); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"collateral, loan details and documentaion have all  been been rejected."+"\n\n"+"Kindly edit them and resumit to your supervisors for approval."+"\n\n"+"Thank you");
       
            
            
            }
            else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==3){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(true); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(true); 
jButton1.setEnabled(false); 
jButton9.setEnabled(true); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" collateral and documentation have  been rejected but the loan details was  approved."+"\n\n"+"Kindly edit the two rejected items and resubmit them to your supervisors for approval"+"\n\n"+"Thank you");
            }
   
            
  else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==3){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(true); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(true); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(true); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" collateral and loan details have  been approved but the documentation  was  rejected."+"\n\n"+"Kindly edit the documentation and resubmit it to your supervisors for approval"+"\n\n"+"Thank you");
          }
   else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==3){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(true); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(true); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" loan details was approved but documentation was rejected but we are still waiting for collateral to be approved."+"\n\n"+"Kindly edit the two rejected documentation and resubmit to your supervisors for approval"+"\n\n"+"Thank you");
          }
   else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==1){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(true); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" collateral has sofar been rejected and we are still waiting for loan details and documentation to be approved."+"\n\n"+"Kindly edit the collateral and resubmit to supervisors for authorisation."+"\n\n"+"Thank you");
           }
   else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==2){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(true); 
jButton1.setEnabled(true); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" collateral was rejected though  documentation was   approved and we are still waiting for loan details to be approved."+"\n\n"+"Kindly edit collateral and resubmit to your supervisors for approval"+"\n\n"+"Thank you");
           }
   else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==3){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(true); 
jButton1.setEnabled(false); 
jButton9.setEnabled(true); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" collateral and documentation have  been rejected but the loan details is pending approval."+"\n\n"+"Kindly edit the two rejected items and resubmit them to your supervisors for approval"+"\n\n"+"Thank you");
           }
   else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==2){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(true); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(true); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" loan details was rejected but documentaion approved though we are waiting for collateral to be approved."+"\n\n"+"Kindly edit loan details and resubmit to your supervisors for approval"+"\n\n"+"Thank you");
           }
  else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==3){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(true); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(true); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" loan details and documentation have  been rejected and we are still waiting for collateral to be approved."+"\n\n"+"Kindly edit the two rejected items and resubmit them to your supervisors for approval"+"\n\n"+"Thank you");
  

           }
            
  else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==3){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(true); 
jButton8.setEnabled(false); 
jButton10.setEnabled(true); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(true); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" loan details and documentation have  been rejected though collateral was approved."+"\n\n"+"Kindly edit the two rejected items and resubmit them to your supervisors for approval"+"\n\n"+"Thank you");
         

           }
                      
else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==1){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(true); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(true); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" loan details was approved and collateral rejected, we are still waiting for documentaion to be approved."+"\n\n"+"Kindly edit collateral and  resubmit it to your supervisors for approval"+"\n\n"+"Thank you");
         

           }
           else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==2){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(true); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(true); 
jButton1.setEnabled(true); 
jButton9.setEnabled(false); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" loan details and documentation have  been approved and  collateral was rejected ."+"\n\n"+"Kindly edit collateral and resubmit it to your supervisors for approval"+"\n\n"+"Thank you");
 

           }
  else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==3){ 
jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(true); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"  documentation has been rejected and we are still waiting for collateral and loan details  to be approved."+"\n\n"+"Kindly edit collateral and resubmit it to your supervisors for approval"+"\n\n"+"Thank you");

           }
            else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+statusOfLoanApprovalsAccount+".txt"))==1&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+statusOfLoanApprovalsAccount+".txt"))==3){ 

                
                
 jButton4.setEnabled(false); 
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(true); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(true); 
jButton12.setEnabled(false); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false);  
         jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+" collateral has been approved, documentation rejected and  loan details is still waiting for  approval."+"\n\n"+"Kindly edit documention and resubmit it to your supervisors for approval"+"\n\n"+"Thank you");

           }
       
            
            
            break;
            case 3:
  
                                 
                break;
                case 4:
                    
 if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+ statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+ statusOfLoanApprovalsAccount+".txt"))==2&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+ statusOfLoanApprovalsAccount+".txt"))==2){
                    
 jButton4.setEnabled(false);
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(true); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false); 
jButton12.setText("Loan Approved");
jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"loan has been completely approved."+"\n\n"+"Thank you");
                    } else if(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","collateral"+ statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","document"+ statusOfLoanApprovalsAccount+".txt"))==3&&fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","loandetails"+ statusOfLoanApprovalsAccount+".txt"))==3){
    jButton4.setEnabled(false);
jButton3.setEnabled(false); 
jButton5.setEnabled(false); 
jButton8.setEnabled(false); 
jButton10.setEnabled(false); 
jButton11.setEnabled(false); 
jButton1.setEnabled(false); 
jButton9.setEnabled(false); 
jButton12.setEnabled(true); 
jButton6.setEnabled(false); 
jButton2.setEnabled(false); 
jButton12.setText("Loan Rejected");                 
 jTextArea1.setText("\n"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]+"'s "+""+"loan has been completely rejected."+"\n\n"+"Thank you");                   
                    
                    }

                    break;
                    case 5:
                        
                        
                        
                        
                        break;
        
        
        }
        jLabel1.setText("LOAN APPROVAL FOR "+"  "+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[10]);
    
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String accountg=fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt")); 
        Integer xxy=4;
    
 fios.stringFileWriter(fios.createFileName("loanApplication", "amortValues", "amortizeStatus"+accountg+ ".txt"), xxy.toString());
 LoanManagmentWindow f = new  LoanManagmentWindow (userId);
        f.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        f.setSize(screen.getSize());
        f.pack();
        this.dispose();  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       loanApprovalsMaker f = new  loanApprovalsMaker(userId);
        f.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        f.setSize(screen.getSize());
        f.pack();
        this.dispose();  
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    int i=1;
     while(i<=5){
     
     JOptionPane.showMessageDialog(this, "SYSTEM LOG OUT ERROR!!!!!!!!!");
     }
    }//GEN-LAST:event_formWindowClosing

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
jButton8.setEnabled(true);
jButton5.setEnabled(false);
jTextArea1.setText(fios.stringFileReader(fios.createFileName("loanAuthorisation", "displayWindow", "rejectedComments"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

               loan.deleteLoanAppStore(fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt")));
//               loan.dropTableLoan(fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt")));
               fios.deleteFileExistance(fios.createFileName("loanApplication", "amortValues", "loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt")+".txt"))); 
               Integer mercy=1;
               fios.intFileWriterReplace(fios.createFileName("loanApplication", "amortValues", "amortizeStatus"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"),mercy.toString());     
          
          
    LoanManagmentWindow f = new  LoanManagmentWindow (userId);
        f.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        f.setSize(screen.getSize());
        f.pack();
        this.dispose();        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

     if(  fios.intFileReader(fios.createFileName("loanApplication", "fromLoanApprovals", "statusOfLoanApprovals"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"))==4){
     
     loan.updateLoanStoreAll(fios.intFileReader(fios.createFileName("loanAuthorisation", "displayWindow","authorisorId"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"))+"", fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt")),"Approved","newloan"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt")),fios.stringFileReader(fios.createFileName("loanApplication", "amortValues","loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")).split("[,]", 15)[14].replaceAll("[,]", " "));
     
     }   
        
        
        
        if(jButton12.getText().equalsIgnoreCase("Loan Approved")&&jButton12.isEnabled()==true){   
        jButton12.setEnabled(false); 
        jButton2.setEnabled(true); 
        jButton12.setText(" Loan Approval Status");
      String loandetails =fios.stringFileReader(fios.createFileName("loanApplication", "amortValues","loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"));       
        List loanDetails= new ArrayList();
       loanDetails.add(loandetails.split("[,]", 15)[1]);//Princimpal amount
         loanDetails.add(loandetails.split("[,]", 15)[2]);//interest amount
  loanDetails.add(loandetails.split("[,]", 15)[4]);//instalment start date
  loanDetails.add(loandetails.split("[,]", 15)[5]);//instalment start date
    loanDetails.add(loandetails.split("[,]", 15)[0]);//instalment start date
   loanDetails.add("Approved");//loan cycle status
    loanDetails.add(dbq.AccountName(fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))));//loan cycle status
    loanDetails.add(fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt")));//loan cycle status
  loan.updateLoanReportATable(loanDetails);  
} else if(jButton12.getText().equalsIgnoreCase("Loan Rejected")&&jButton12.isEnabled()==true){
               loan.deleteLoanAppStore(fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt")));
//               loan.dropTableLoan(fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt")));
               Integer mercy=1;
fios.intFileWriterReplace(fios.createFileName("loanApplication", "amortValues", "amortizeStatus"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"),mercy.toString());     
fios.deleteFileExistance(fios.createFileName("loanApplication","amortValues","loanStore"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 

fios.deleteFileExistance(fios.createFileName("loanApplication","amortValues","amortizeStatus"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"));
fios.deleteFileExistance(fios.createFileName("loanApplication", "collateralSDocumentation","collDisplay"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 

fios.deleteFileExistance(fios.createFileName("loanApplication" ,"collateralSDocumentation","colls"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 
fios.deleteFileExistance(fios.createFileName("loanApplication", "collateralSDocumentation","docDisplay"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount.txt"))+".txt"));
fios.deleteFileExistance(fios.createFileName("loanApplication" ,"collateralSDocumentation","docs"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 

fios.deleteFileExistance(fios.createFileName("loanApplication","fromLoanApprovals","statusOfCollateral"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 

fios.deleteFileExistance(fios.createFileName("loanApplication","fromLoanApprovals","statusOfDocumentation"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 

fios.deleteFileExistance(fios.createFileName("loanApplication","fromLoanApprovals","statusOfLoanApprovals"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"));

fios.deleteFileExistance(fios.createFileName("loanApplication","fromLoanApprovals","statusOfLoandetails"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"));

fios.deleteFileExistance(fios.createFileName("loanApplication","fromLoanApprovals","statusOfMovementDoc"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 

fios.deleteFileExistance(fios.createFileName("loanAuthorisation","displayWindow","authorisedCollateral"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"));
fios.deleteFileExistance(fios.createFileName("loanAuthorisation","displayWindow","authorisedDocement"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"));
fios.deleteFileExistance(fios.createFileName("loanAuthorisation","displayWindow","authorisedLoanDetails"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"));

fios.deleteFileExistance(fios.createFileName("loanAuthorisation","displayWindow","collateral"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 

fios.deleteFileExistance(fios.createFileName("loanAuthorisation","displayWindow","document"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt"));
fios.deleteFileExistance(fios.createFileName("loanAuthorisation","displayWindow","loandetails"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 
fios.deleteFileExistance(fios.createFileName("loanAuthorisation","displayWindow","loanInitialisation"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 
fios.deleteFileExistance(fios.createFileName("loanAuthorisation","displayWindow","rejectedComments"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 


fios.deleteFileExistance(fios.createFileName("loanAuthorisation","userIdDetails","currentHolder"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 
 
fios.deleteFileExistance(fios.createFileName("loanAuthorisation","loanDetails","loanDetailsValues"+fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"))+".txt")); 

 jButton12.setEnabled(false);
jButton12.setText(" Loan Approval Status");


  LoanManagmentWindow f = new  LoanManagmentWindow (userId);
        f.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        f.setSize(screen.getSize());
        f.pack();
        this.dispose();        
}


       
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   
   String account=fios.stringFileReader(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"));      
        
        Integer xxy=2;
    
 fios.stringFileWriter(fios.createFileName("loanApplication", "amortValues", "amortizeStatus"+account+ ".txt"), xxy.toString());
 
   Integer xxys=1;
  fios.intFileWriterReplace(fios.createFileName("loanApplication", "fromLoanApprovals", "statusOfLoanApprovals"+account+".txt"),xxys.toString()); 
 
 
 
 
 
 LoanManagmentWindow f = new  LoanManagmentWindow (userId);
        f.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        f.setSize(screen.getSize());
        f.pack();
        this.dispose();   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
   jButton9.setEnabled(false);
   jButton6.setEnabled(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
     jButton11.setEnabled(false);
   jButton6.setEnabled(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(loanApprovalsMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(loanApprovalsMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(loanApprovalsMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(loanApprovalsMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new loanApprovalsMaker().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        if (e.getClickCount()==2){

    if(e.getSource()==jTree2){
    DefaultMutableTreeNode node = (DefaultMutableTreeNode)jTree2.getLastSelectedPathComponent();
    String window =node.toString();
    switch (window){
    case "Loan Application":
        fios.forceFileExistanceAppend(fios.createFileName("loanApplication", "amortValues", "fromLoanManagementTable.txt"));
          Integer xl=0;
   fios.intFileWriterReplace(fios.createFileName("loanApplication", "amortValues", "fromLoanManagementTable.txt"),xl.toString());
     
       Object[] options = {"Continue",  "Cancel"};
        int n = JOptionPane.showOptionDialog(this,  "Work may not be saved!!!\n"+"Do you want to  continue ?",
        "SAVE PLEASE", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,options, options[0]);
        if(n==JOptionPane.YES_OPTION){
        NewLoanApplication frm = new NewLoanApplication(userId);
        frm.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        frm.setSize(screen.getSize());
        frm.pack();
        this.dispose();
        }
        else if (n==JOptionPane.NO_OPTION){ this.setVisible(true);}
        break;
    case "Amotization Calculator":
        JOptionPane.showMessageDialog(rootPane, "Module is still under construction");
        
      Object[] optionsES = {"Continue",  "Cancel"};
        int nES = JOptionPane.showOptionDialog(this,  "Work may not be saved!!!\n"+"Do you want to  continue ?",
        "SAVE PLEASE", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,optionsES, optionsES[0]);
        if(nES==JOptionPane.YES_OPTION){
         amortDetails=new ArrayList();
        AmotizationCalculator frm1 = new AmotizationCalculator(userId,amortDetails);
        frm1.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        frm1.setSize(screen.getSize());
        frm1.pack();
        this.dispose();
        }
        else if (nES==JOptionPane.NO_OPTION){ this.setVisible(true);}
        break;
        case "Loan Calculator":
            JOptionPane.showMessageDialog(rootPane, "Module is still under construction");
        
            Object[] optionsSF = {"Continue",  "Cancel"};
            int nSF = JOptionPane.showOptionDialog(this,  "Work may not be saved!!!\n"+"Do you want to  continue ?",
            "SAVE PLEASE", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,optionsSF, optionsSF[0]);
            if(nSF==JOptionPane.YES_OPTION){
            LoanCalculator f = new LoanCalculator(userId);
            f.setVisible(true);
            Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
            f.setSize(screen.getSize());
            f.pack();
            this.dispose();
            }
            else if (nSF==JOptionPane.NO_OPTION){ this.setVisible(true);}
            break;
    case "Collateral and Documents":
        JOptionPane.showMessageDialog(rootPane, "Module is still under construction");
        
        Object[] optionsSSV = {"Continue",  "Cancel"};
        int nSSV = JOptionPane.showOptionDialog(this,  "Work may not be saved!!!\n"+"Do you want to  continue ?",
        "SAVE PLEASE", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, optionsSSV,  optionsSSV[0]);
        if(nSSV==JOptionPane.YES_OPTION){
        CollateralandDocuments frm3 = new  CollateralandDocuments(userId);
        frm3.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        frm3.setSize(screen.getSize());
        frm3.pack();
        this.dispose();
        }
        else if (nSSV==JOptionPane.NO_OPTION){ this.setVisible(true);}
        break;
       
    case "Log Out":
         Integer zx=1;
      fios.forceFileExistance(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"));
     fios.stringFileWriter(fios.createFileName("loanApplication", "amortValues", "activeAccount"+this.userId+".txt"), zx.toString());
        Object[] optionsSGS1 = {"Continue",  "Cancel"};
        int nSGS1 = JOptionPane.showOptionDialog(this,  "Work may not be saved!!!\n"+"Do you want to  continue ?",
        "SAVE PLEASE", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,optionsSGS1, optionsSGS1[0]);
        if(nSGS1==JOptionPane.YES_OPTION){
       fios.forceFileExistanceAppend(fios.createFileName("loanApplication", "amortValues", "fromLoanManagementTable.txt"));
          Integer xlS=0;
           fios.intFileWriterReplace(fios.createFileName("loanApplication", "amortValues", "fromLoanManagementTable.txt"),xlS.toString());
            LoanManagmentWindow frm5 = new LoanManagmentWindow(userId);
        frm5.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        frm5.setSize(screen.getSize());
        frm5.pack();
        this.dispose();
        }
        else if (nSGS1==JOptionPane.NO_OPTION){ this.setVisible(true);}
        break;
      }}}}
    

    @Override
    public void mousePressed(MouseEvent e) {
       
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
      
    }

    @Override
    public void mouseExited(MouseEvent e) {
       
    }
}
