/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package googo.pmms.project2.smallFrames;

import googo.pmms.project2.accountsHelper.Formartter;
import googo.pmms.project2.accountsHelper.PostingMain;
import googo.pmms.project2.accountsHelper.PostingModal;
import googo.pmms.project2.accountsHelper.fileInputOutPutStreams;
import googo.pmms.project2.databases.DatabaseQuaries;
import googo.pmms.project2.databases.loanDatabaseQuaries;
import googo.pmms.project2.excel.CreateExcelWorkBook;
import googo.pmms.project2.frameHelper.IUpdateText;
import googo.pmms.project2.frameHelper.ListDataModel;
import googo.pmms.project2.frameHelper.ListDataModelCreateInt;
import googo.pmms.project2.frameHelper.ListDataModel_1;
import googo.pmms.project2.frames.Calender;
import googo.pmms.project2.frames.ReportView;
import googo.pmms.project2.frames.Reportx;
import googo.pmms.project2.loanHelper.MaxBorrowed;
import googo.pmms.project2.loanHelper.MaxmumAmountBorrowedFormulas;
import googo.pmms.project2.reportsHelper.OtherLoanReports;
import googo.pmms.project2.reportsHelper.ProfitAndLoss;
import googo.pmms.project2.reportsHelper.ReportsPDFFormulars;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author STAT SOLUTIONS
 */
public class QuickReports extends javax.swing.JFrame implements MouseListener, IUpdateText, ActionListener{
String userId,theRepoType;

fileInputOutPutStreams fios= new fileInputOutPutStreams();

DatabaseQuaries dbq =new DatabaseQuaries();

OtherLoanReports otherLoans=new  OtherLoanReports();

 ReportsPDFFormulars pdf = new ReportsPDFFormulars();
 
     ProfitAndLoss pAndL = new  ProfitAndLoss();

ListDataModel result;

ListDataModel_1 result1;
ListDataModelCreateInt result1v;
int InterestWaive=0,AccumulatedInterestWaive=0,LoanPenaltyWaive=0,SelectAdjustTableWaive=0,In5=0;

Formartter fmt= new Formartter();

 double oldAmount = 0, newAmount,newQaulified=0.0,finalQualified=0;
    List<Object> topups;
   MaxBorrowed mxb=new MaxBorrowed();
//    fileInputOutPutStreams fios= new fileInputOutPutStreams();
    DecimalFormat NumberFormat =new DecimalFormat("#,###.##");
    ArrayList<String> data4, column1;
 ArrayList<ArrayList<String>> data5;
          JOptionPane p;
    PostingModal model ;
    JFrame fi, f,fa,fb,fc;
    Date date;
  SimpleDateFormat sdf =new SimpleDateFormat("dd/MM/yyyy");
  SimpleDateFormat sdk =new SimpleDateFormat("dd.MM.yyyy");
       CreateExcelWorkBook writeExcel= new CreateExcelWorkBook();
// DatabaseQuaries dbq= new DatabaseQuaries();
 MaxmumAmountBorrowedFormulas maxValue= new MaxmumAmountBorrowedFormulas();
 loanDatabaseQuaries loan=new loanDatabaseQuaries();
  DecimalFormat df1 = new DecimalFormat("#,###");
   PostingMain post= new PostingMain(QuickReports.this);
//    Formartter fmt = new Formartter();


public QuickReports(String userId,String reportType) {
        initComponents();
 this.userId=userId;
  theRepoType=reportType;
 
        Image img = new ImageIcon(System.getProperty("user.dir")+"/"+"ICON_LOGO.jpg").getImage();
      this.setIconImage(img);
       this.setTitle("WAIVE INCOME"); 
//        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        jTextField60 = new javax.swing.JTextField();
        jButton237 = new javax.swing.JButton();
        jLabel101 = new javax.swing.JLabel();
        jTextField59 = new javax.swing.JTextField();
        jButton236 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        JBTrnSqNo4 = new javax.swing.JButton();
        debitAccountField1 = new javax.swing.JFormattedTextField();
        jButton51 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 153), new java.awt.Color(0, 204, 153)));
        jPanel1.setLayout(null);

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel102.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel102.setText("START DATE");
        jLabel102.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel102);
        jLabel102.setBounds(100, 90, 100, 30);

        jTextField60.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(jTextField60);
        jTextField60.setBounds(210, 90, 180, 30);

        jButton237.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton237.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton237ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton237);
        jButton237.setBounds(400, 90, 30, 30);

        jLabel101.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel101.setText("END DATE");
        jLabel101.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel101);
        jLabel101.setBounds(100, 130, 100, 30);

        jTextField59.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(jTextField59);
        jTextField59.setBounds(210, 130, 180, 30);

        jButton236.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/calender.png"))); // NOI18N
        jButton236.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton236ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton236);
        jButton236.setBounds(400, 130, 30, 30);

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(140, 180, 250, 40);

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("EXCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(100, 230, 160, 40);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(280, 230, 160, 40);

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Ledger Id");
        jLabel44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel44);
        jLabel44.setBounds(100, 40, 150, 30);

        JBTrnSqNo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googo/pmms/project2/images/find-icon.png"))); // NOI18N
        JBTrnSqNo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTrnSqNo4ActionPerformed(evt);
            }
        });
        jPanel3.add(JBTrnSqNo4);
        JBTrnSqNo4.setBounds(250, 40, 20, 30);
        JBTrnSqNo4.setEnabled(false);

        debitAccountField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 255), null));
        debitAccountField1.setForeground(new java.awt.Color(0, 51, 255));
        try {
            debitAccountField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#######-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        debitAccountField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        debitAccountField1.setValue(null);
        debitAccountField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitAccountField1ActionPerformed(evt);
            }
        });
        debitAccountField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                debitAccountField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                debitAccountField1KeyReleased(evt);
            }
        });
        jPanel3.add(debitAccountField1);
        debitAccountField1.setBounds(270, 40, 120, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(100, 50, 540, 290);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 470);

        jButton51.setBackground(new java.awt.Color(0, 51, 51));
        jButton51.setText("jButton5");
        getContentPane().add(jButton51);
        jButton51.setBounds(1800, 360, 73, 23);

        jButton50.setBackground(java.awt.SystemColor.controlLtHighlight);
        jButton50.setText("jButton5");
        getContentPane().add(jButton50);
        jButton50.setBounds(1790, 330, 73, 23);

        jButton49.setBackground(new java.awt.Color(255, 204, 204));
        jButton49.setText("jButton5");
        getContentPane().add(jButton49);
        jButton49.setBounds(1870, 320, 73, 23);

        jButton31.setBackground(new java.awt.Color(255, 204, 153));
        jButton31.setText("Blue");
        getContentPane().add(jButton31);
        jButton31.setBounds(1810, 310, 53, 23);

        jButton38.setBackground(new java.awt.Color(204, 204, 0));
        jButton38.setText("Blue");
        getContentPane().add(jButton38);
        jButton38.setBounds(1810, 290, 53, 23);

        jButton32.setBackground(new java.awt.Color(0, 153, 153));
        jButton32.setText("Blue");
        getContentPane().add(jButton32);
        jButton32.setBounds(1870, 290, 53, 23);

        jButton47.setBackground(new java.awt.Color(204, 255, 204));
        jButton47.setText("Blue");
        getContentPane().add(jButton47);
        jButton47.setBounds(1930, 290, 53, 23);

        jButton29.setBackground(new java.awt.Color(0, 204, 204));
        jButton29.setText("Blue");
        getContentPane().add(jButton29);
        jButton29.setBounds(1920, 270, 53, 23);

        jButton37.setBackground(new java.awt.Color(204, 153, 255));
        jButton37.setText("Blue");
        getContentPane().add(jButton37);
        jButton37.setBounds(1870, 270, 53, 23);

        jButton33.setBackground(new java.awt.Color(152, 198, 94));
        jButton33.setText("Blue");
        getContentPane().add(jButton33);
        jButton33.setBounds(1810, 270, 53, 23);

        jButton35.setBackground(new java.awt.Color(255, 204, 204));
        jButton35.setText("Blue");
        getContentPane().add(jButton35);
        jButton35.setBounds(1810, 250, 53, 23);

        jButton45.setBackground(new java.awt.Color(255, 255, 204));
        jButton45.setText("Blue");
        getContentPane().add(jButton45);
        jButton45.setBounds(1870, 250, 53, 23);

        jButton42.setBackground(new java.awt.Color(0, 204, 102));
        jButton42.setText("Blue");
        getContentPane().add(jButton42);
        jButton42.setBounds(1920, 230, 53, 23);

        jButton43.setBackground(new java.awt.Color(204, 204, 204));
        jButton43.setText("Blue");
        getContentPane().add(jButton43);
        jButton43.setBounds(1870, 230, 53, 23);

        jButton30.setBackground(new java.awt.Color(0, 153, 255));
        jButton30.setText("Blue");
        getContentPane().add(jButton30);
        jButton30.setBounds(1810, 230, 53, 23);

        jButton36.setBackground(java.awt.SystemColor.activeCaption);
        jButton36.setText("Blue");
        getContentPane().add(jButton36);
        jButton36.setBounds(1810, 210, 53, 23);

        jButton44.setBackground(new java.awt.Color(204, 165, 165));
        jButton44.setText("Blue");
        getContentPane().add(jButton44);
        jButton44.setBounds(1870, 210, 53, 23);

        jButton39.setBackground(new java.awt.Color(204, 204, 255));
        jButton39.setText("Blue");
        getContentPane().add(jButton39);
        jButton39.setBounds(1920, 210, 53, 23);

        jButton41.setBackground(java.awt.SystemColor.activeCaption);
        jButton41.setText("Blue");
        getContentPane().add(jButton41);
        jButton41.setBounds(1920, 190, 53, 23);

        jButton46.setBackground(java.awt.SystemColor.activeCaption);
        jButton46.setText("Blue");
        getContentPane().add(jButton46);
        jButton46.setBounds(1870, 190, 53, 23);

        jButton40.setBackground(java.awt.SystemColor.activeCaption);
        jButton40.setText("Blue");
        getContentPane().add(jButton40);
        jButton40.setBounds(1810, 190, 53, 23);

        jButton48.setBackground(new java.awt.Color(201, 222, 223));
        jButton48.setText("Blue");
        getContentPane().add(jButton48);
        jButton48.setBounds(1870, 170, 53, 23);

        jButton52.setBackground(new java.awt.Color(0, 51, 51));
        jButton52.setText("jButton5");
        getContentPane().add(jButton52);
        jButton52.setBounds(1800, 360, 73, 23);

        jButton53.setBackground(java.awt.SystemColor.controlLtHighlight);
        jButton53.setText("jButton5");
        getContentPane().add(jButton53);
        jButton53.setBounds(1790, 330, 73, 23);

        jButton54.setBackground(new java.awt.Color(255, 204, 204));
        jButton54.setText("jButton5");
        getContentPane().add(jButton54);
        jButton54.setBounds(1870, 320, 73, 23);

        jButton34.setBackground(new java.awt.Color(255, 204, 153));
        jButton34.setText("Blue");
        getContentPane().add(jButton34);
        jButton34.setBounds(1810, 310, 53, 23);

        jButton55.setBackground(new java.awt.Color(204, 204, 0));
        jButton55.setText("Blue");
        getContentPane().add(jButton55);
        jButton55.setBounds(1810, 290, 53, 23);

        jButton56.setBackground(new java.awt.Color(0, 153, 153));
        jButton56.setText("Blue");
        getContentPane().add(jButton56);
        jButton56.setBounds(1870, 290, 53, 23);

        jButton57.setBackground(new java.awt.Color(204, 255, 204));
        jButton57.setText("Blue");
        getContentPane().add(jButton57);
        jButton57.setBounds(1930, 290, 53, 23);

        jButton58.setBackground(new java.awt.Color(0, 204, 204));
        jButton58.setText("Blue");
        getContentPane().add(jButton58);
        jButton58.setBounds(1920, 270, 53, 23);

        jButton59.setBackground(new java.awt.Color(204, 153, 255));
        jButton59.setText("Blue");
        getContentPane().add(jButton59);
        jButton59.setBounds(1870, 270, 53, 23);

        jButton60.setBackground(new java.awt.Color(152, 198, 94));
        jButton60.setText("Blue");
        getContentPane().add(jButton60);
        jButton60.setBounds(1810, 270, 53, 23);

        jButton61.setBackground(new java.awt.Color(255, 204, 204));
        jButton61.setText("Blue");
        getContentPane().add(jButton61);
        jButton61.setBounds(1810, 250, 53, 23);

        jButton62.setBackground(new java.awt.Color(255, 255, 204));
        jButton62.setText("Blue");
        getContentPane().add(jButton62);
        jButton62.setBounds(1870, 250, 53, 23);

        jButton63.setBackground(new java.awt.Color(0, 204, 102));
        jButton63.setText("Blue");
        getContentPane().add(jButton63);
        jButton63.setBounds(1920, 230, 53, 23);

        jButton64.setBackground(new java.awt.Color(204, 204, 204));
        jButton64.setText("Blue");
        getContentPane().add(jButton64);
        jButton64.setBounds(1870, 230, 53, 23);

        jButton65.setBackground(new java.awt.Color(0, 153, 255));
        jButton65.setText("Blue");
        getContentPane().add(jButton65);
        jButton65.setBounds(1810, 230, 53, 23);

        jButton66.setBackground(java.awt.SystemColor.activeCaption);
        jButton66.setText("Blue");
        getContentPane().add(jButton66);
        jButton66.setBounds(1810, 210, 53, 23);

        jButton67.setBackground(new java.awt.Color(204, 165, 165));
        jButton67.setText("Blue");
        getContentPane().add(jButton67);
        jButton67.setBounds(1870, 210, 53, 23);

        jButton68.setBackground(new java.awt.Color(204, 204, 255));
        jButton68.setText("Blue");
        getContentPane().add(jButton68);
        jButton68.setBounds(1920, 210, 53, 23);

        jButton69.setBackground(java.awt.SystemColor.activeCaption);
        jButton69.setText("Blue");
        getContentPane().add(jButton69);
        jButton69.setBounds(1920, 190, 53, 23);

        jButton70.setBackground(java.awt.SystemColor.activeCaption);
        jButton70.setText("Blue");
        getContentPane().add(jButton70);
        jButton70.setBounds(1870, 190, 53, 23);

        jButton71.setBackground(java.awt.SystemColor.activeCaption);
        jButton71.setText("Blue");
        getContentPane().add(jButton71);
        jButton71.setBounds(1810, 190, 53, 23);

        jButton72.setBackground(new java.awt.Color(201, 222, 223));
        jButton72.setText("Blue");
        getContentPane().add(jButton72);
        jButton72.setBounds(1870, 170, 53, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//   JOptionPane.showMessageDialog(this, theRepoType);
        switch(theRepoType){
      
        
                case "Cash":
                    this.debitAccountField1.setValue(fmt.putSeparatorsOnNormaAccount("01123000110"));
                    
                    break;
                    
                case "Profit":
                  debitAccountField1.setVisible(false);
                  JBTrnSqNo4.setVisible(false);
                  jLabel44.setVisible(false);
                  jButton1.setVisible(false);
                          jButton3.setVisible(false);
                    break;
                    
                case "ARREARS":break;
                 case "PORTFOLIO":break;
                  case "LOAN PAYMENT":break;
                  case "INTEREST":break;
                  case "SUMMURY":break;
        }
        
        
     

    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
switch(theRepoType){
        
                
                
                
                
                
                
        
                case "CASH A/C":
                    
               
        if(debitAccountField1.getValue()==null){JOptionPane.showMessageDialog(this, "Please Select a Valid Account Number"); return;}
        else if(dbq.testTable("bsanca"+fmt.formatAccountWithSeperators(debitAccountField1.getValue().toString()))==false){JOptionPane.showMessageDialog(this, "Account  does not exist");return;}
        
        else if (jTextField60.getText().equalsIgnoreCase("")||jTextField59.getText().equalsIgnoreCase("")) {
        JOptionPane.showMessageDialog(this, "Please Select a valid date from the calender");
        return;
        }else if (fmt.convertTdate(jTextField60.getText().trim()).after(fmt.getTodayDate())||fmt.convertTdate(jTextField59.getText().trim()).after(fmt.getTodayDate())) {
         JOptionPane.showMessageDialog(this, "The selected date should not be greater than today");
         return;
        }else{
   
            
     if(pdf.createStatement(fmt.formatAccountWithSeperators(debitAccountField1.getValue().toString()),fmt.forDatabaseWithFullYearBeginningWithDate(jTextField60.getText().trim()), fmt.forDatabaseWithFullYearBeginningWithDate(jTextField59.getText().trim()),"customer_Statement")){
  
generateFile("customer_Statement"); 
this.dispose();
        } else{
        
        JOptionPane.showMessageDialog(this, "First Close the Opened pdf File");
       
        }  
        
        
         
       
     
    }                                        
     
                    
                    
                    break;
                case "Profit":break;
                case "ARREARS":break;
                 case "PORTFOLIO":break;
                  case "LOAN PAYMENT":break;
                  case "INTEREST":break;
                  case "SUMMURY":break;
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        
       switch(theRepoType){
        
                
                
                
                
                
                
        
                case "Cash":
                    
           if(debitAccountField1.getValue()==null){JOptionPane.showMessageDialog(this, "Please Select a Valid Account Number"); return;}
        else if(dbq.testTable("bsanca"+fmt.formatAccountWithSeperators(debitAccountField1.getValue().toString()))==false){JOptionPane.showMessageDialog(this, "Account  does not exist");return;}
        
        else if (jTextField60.getText().equalsIgnoreCase("")||jTextField59.getText().equalsIgnoreCase("")) {
        JOptionPane.showMessageDialog(this, "Please Select a valid date from the calender");
        return;
        }else if (fmt.convertTdate(jTextField60.getText().trim()).after(fmt.getTodayDate())||fmt.convertTdate(jTextField59.getText().trim()).after(fmt.getTodayDate())) {
         JOptionPane.showMessageDialog(this, "The selected date should not be greater than today");
         return;
        }else{
            
    
            List theOtherDetailsStatement= new ArrayList();
      theOtherDetailsStatement.add(fmt.formatAccountWithSeperators(debitAccountField1.getValue().toString()));
        theOtherDetailsStatement.add(jTextField60.getText());  
         theOtherDetailsStatement.add(jTextField59.getText().trim());  
            ReportView f1 = new ReportView(userId,"CustomerStatment",theOtherDetailsStatement);
        f1.setVisible(true);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        f1.setSize(screen.getSize());
        f1.pack();  
          this.dispose();
       
      
         
       
     
    }                                        
     
                    
                    
                    break;
                case "Profit":
                    
                  if (jTextField60.getText().equalsIgnoreCase("")||jTextField59.getText().equalsIgnoreCase("")) {
        JOptionPane.showMessageDialog(this, "Please Select a valid date from the calender");
        return;
        }else if (fmt.convertTdate(jTextField60.getText().trim()).after(fmt.getTodayDate())||fmt.convertTdate(jTextField59.getText().trim()).after(fmt.getTodayDate())) {
         JOptionPane.showMessageDialog(this, "The selected date should not be greater than today");
         return;
        }
            
     if(pAndL.createPAndL(fmt.forDatabaseWithFullYearBeginningWithDate(jTextField60.getText().trim()),fmt.forDatabaseWithFullYearBeginningWithDate(jTextField59.getText().trim()),"pAndL",QuickReports.this)){
  
     generateFile("pAndL"); 
        } else{
        
        JOptionPane.showMessageDialog(this, "First Close the Opened pdf File");
       
        }  
        
           
                    
                    break;
                case "ARREARS":break;
                 case "PORTFOLIO":break;
                  case "LOAN PAYMENT":break;
                  case "INTEREST":break;
                  case "SUMMURY":break;
        }
        
        
     

        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton237ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton237ActionPerformed
        fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"806");
        Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton237ActionPerformed

    private void jButton236ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton236ActionPerformed
        fios.intFileWriterReplace(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"),"807");
        Calender frmMain = new Calender();
        frmMain.setIUpdateText(this);
        frmMain.pack();
        frmMain.setVisible(true);
    }//GEN-LAST:event_jButton236ActionPerformed

    private void JBTrnSqNo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTrnSqNo4ActionPerformed

       

    }//GEN-LAST:event_JBTrnSqNo4ActionPerformed

    private void debitAccountField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitAccountField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debitAccountField1ActionPerformed

    private void debitAccountField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_debitAccountField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_debitAccountField1KeyPressed

    private void debitAccountField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_debitAccountField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_debitAccountField1KeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
////        public static String u=AddBatch.this.userId;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddBatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddBatch().setVisible(true);
//            }
//        });
//    }
   private void sortTable(JTable table,JTextField textField){

   
    
TableRowSorter<TableModel> rowSorter  = new TableRowSorter<>(table.getModel());
                     
                      table.setRowSorter(rowSorter);
                     textField.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = textField.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = textField.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    

}
   
   private void generateFile(String fileName){
  JOptionPane.showMessageDialog(this, fileName);  
   
     if (Desktop.isDesktopSupported()) {
      try {
          // no application registered for PDFs
          
          File myFile = new File(fios.createFileName("PMMS_Statements", "PMMS_Statements1", fileName+".pdf"));
        
          Desktop.getDesktop().open(myFile);
      } catch (IOException ex) {
          Logger.getLogger(Reportx.class.getName()).log(Level.SEVERE, null, ex);
      }
     }
    
  }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTrnSqNo4;
    private javax.swing.JFormattedTextField debitAccountField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton236;
    private javax.swing.JButton jButton237;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField60;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
      
    }

    @Override
    public void mousePressed(MouseEvent e) {
      
    }

    @Override
    public void mouseReleased(MouseEvent e) {
      
    }

    @Override
    public void mouseEntered(MouseEvent e) {
      
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }

    @Override
    public void updateText(String text) {
       switch( fios.intFileReader(fios.createFileName("PMMS_Statements", "reports", "calSelection.txt"))){ 
              
                  
                   case 806:jTextField60.setText(text);break;
                    case 807:jTextField59.setText(text);break;
                
//                   
                    
                
     }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
       
    }
}
